#include "gui/ui/screens/management6b/Management6BController.h"
#include <cstdlib>
#include <iostream>
using namespace ingnomia::ui;
using namespace ingnomia::ui::management6b;
namespace
{
void check(bool v,const char*m){if(!v){std::cerr<<m<<'\n';std::exit(1);}}
struct Port:CommandPort{std::vector<UiActionEnvelope>actions;CommandResult dispatch(const UiActionEnvelope&a)override{actions.push_back(a);return{};}};
struct Screen:ViewPort{Management6BState state;int changes{};void stateChanged(const Management6BState&s)override{state=s;++changes;}};
InventoryRow item(const char*id,const char*name,unsigned total){InventoryRow r;r.id={CatalogId{"resources"},CatalogId{"bars"},CatalogId{id},CatalogId{},InventoryDepth::Item};r.name=name;r.total=total;return r;}
}
int main()
{
	Port p;Screen v;Management6BController c(p,v);
	check(!c.state().open,"startup hidden");c.beginWorld(WorldEpoch{41});check(!c.state().open,"world start hidden");c.openPopulation();check(c.state().open&&p.actions.back().id.value=="population.refresh","population opens");c.close();check(!c.state().open,"close hides");c.open(View::Citizens);
	PopulationRow ada{CreatureId{7},"Ada",ProfessionId{"Miner"},{{CatalogId{"Mining"},"Mining","Industry",4,.5f,true}}};PopulationRow bera{CreatureId{9},"Bera",ProfessionId{"Smith"},{}};
	check(c.applyPopulation({WorldEpoch{41},Revision{1},{bera,ada}}),"population snapshot");c.setPopulationSort(Sort::Name);check(c.visiblePopulation().front().id.value==7,"stable sort");c.movePopulationSelection(1);check(c.state().selectedCreature->value==7,"keyboard enters first row");c.movePopulationSelection(1);check(c.state().selectedCreature->value==9,"keyboard row selection");c.selectCreature(CreatureId{7});check(std::get<SelectPayload>(p.actions.back().payload).target.id==7,"creature stable id");
	check(c.applyPopulationPatch({WorldEpoch{41},Revision{1},Revision{2},PopulationRow{CreatureId{7},"Zada",ProfessionId{"Miner"},{}}}),"row patch");check(c.state().selectedCreature->value==7,"selection survives patch");c.setPopulationFilter("smith");check(c.state().selectedCreature->value==7,"filter preserves stable selection");c.movePopulationSelection(1);check(c.state().selectedCreature->value==9,"keyboard enters filtered rows");const auto before=p.actions.size();check(!c.applyPopulationPatch({WorldEpoch{41},Revision{1},Revision{3},ada}),"wrong base");check(p.actions.size()==before+1,"refresh once");check(!c.applyPopulationPatch({WorldEpoch{41},Revision{1},Revision{4},ada})&&p.actions.size()==before+1,"refresh dedupe");check(!c.applyPopulation({WorldEpoch{40},Revision{99},{ada}}),"old epoch");
	c.setSkill(CreatureId{7},CatalogId{"Mining"},false);check(std::get<SetSkillPayload>(p.actions.back().payload).skill.value=="Mining","skill action");ScheduleRow sa;sa.creature=CreatureId{7};ScheduleRow sb;sb.creature=CreatureId{9};check(c.applySchedules({WorldEpoch{41},Revision{1},{sa,sb}}),"schedules");c.selectScheduleCell({CreatureId{7},23});c.moveScheduleFocus(1,1);check(c.state().selectedScheduleCell->creature.value==9&&c.state().selectedScheduleCell->hour==23,"schedule keyboard");c.activateScheduleCell(ScheduleActivity::Training);check(std::get<SetScheduleCellPayload>(p.actions.back().payload).activity==ScheduleActivity::Training,"training action");const auto invalid=p.actions.size();c.setScheduleCell(CreatureId{7},24,ScheduleActivity::Sleep);check(p.actions.size()==invalid,"invalid hour");
	c.openInventory();auto copper=item("bar","Copper bar",12),iron=item("ingot","Iron ingot",30);InventoryRow category;category.id={CatalogId{"resources"},CatalogId{},CatalogId{},CatalogId{},InventoryDepth::Category};category.name="Resources";InventoryRow group;group.id={CatalogId{"resources"},CatalogId{"bars"},CatalogId{},CatalogId{},InventoryDepth::Group};group.name="Bars";check(c.applyInventory({WorldEpoch{41},Revision{1},{category,group,iron,copper}}),"inventory");c.setInventorySort(Sort::Total);check(c.visibleInventory().front().name=="Resources","inventory hierarchy root");check(c.visibleInventory()[1].name=="Bars"&&c.visibleInventory()[2].name=="Iron ingot","inventory sibling sort");c.toggleInventoryExpanded(category.id);check(c.visibleInventory().size()==1&&c.visibleInventory().front().name=="Resources","inventory collapse");c.toggleInventoryExpanded(category.id);c.moveInventorySelection(1);check(c.state().selectedInventory==category.id,"inventory keyboard enters section");c.moveInventorySelection(1);check(c.state().selectedInventory==group.id,"inventory keyboard enters group");c.moveInventorySelection(1);check(c.state().selectedInventory==iron.id,"inventory keyboard enters first child");c.moveInventorySelection(1);check(c.state().selectedInventory==copper.id,"inventory keyboard");check(c.applyInventoryPatch({WorldEpoch{41},Revision{1},Revision{2},InventoryRow{copper.id,"Copper bar",99}}),"inventory patch");check(c.state().selectedInventory==copper.id,"inventory selection survives");c.toggleSelectedWatch();check(std::get<WatchPayload>(p.actions.back().payload).row==copper.id,"typed watch");
	 c.setInventoryCategory("resources");check(c.visibleInventory().size()==3,"inventory category keeps group and matching rows");c.setInventoryCategory("other");check(c.visibleInventory().empty(),"inventory category filters rows");c.setInventoryCategory("");c.setInventoryOwnedOnly(true);check(c.visibleInventory().size()==4&&c.visibleInventory()[0].name=="Resources"&&c.visibleInventory()[2].total>0,"inventory owned filter keeps hierarchy");c.setInventoryOwnedOnly(false);
	std::vector<InventoryRow> large;for(std::uint32_t i=0;i<1000;++i){auto row=item(("item-"+std::to_string(i)).c_str(),("Material "+std::to_string(i)).c_str(),i);large.push_back(std::move(row));}check(c.applyInventory({WorldEpoch{41},Revision{3},std::move(large)}),"large inventory");check(c.inventoryPage().size()==Management6BState::pageSize,"bounded first page");c.changeInventoryPage(1);check(c.inventoryPage().size()==Management6BState::pageSize,"bounded next page");c.setInventoryFilter("");for(int i=0;i<70;++i)c.moveInventorySelection(1);check(c.state().inventoryPage>0,"keyboard selection follows page");
	c.setPopulationFilter("");c.selectCreature(CreatureId{7});CreatureDetail detail;detail.id=CreatureId{7};detail.name="Ada";check(c.applyCreature({WorldEpoch{41},Revision{1},detail}),"creature detail");c.endWorld();const auto count=p.actions.size();c.refresh();c.setSkill(CreatureId{7},CatalogId{"Mining"},true);check(p.actions.size()==count,"unload blocks");check(!c.state().open&&c.state().population.empty(),"unload clears");std::cout<<"Management 6B controller tests passed\n";
}
