#include "gui/ui/screens/management6b/Management6BController.h"
#include <cstdlib>
#include <iostream>
using namespace ingnomia::ui;
using namespace ingnomia::ui::management6b;
namespace
{
void check(bool v,const char*m){if(!v){std::cerr<<m<<'\n';std::exit(1);}}
struct Port:CommandPort{std::vector<UiActionEnvelope>actions;std::vector<UiActionEnvelope>confirmed;CommandResult dispatch(const UiActionEnvelope&a)override{actions.push_back(a);return{};}CommandResult dispatchConfirmed(const UiActionEnvelope&a)override{confirmed.push_back(a);return{};}};
struct Screen:ViewPort{Management6BState state;int changes{};void stateChanged(const Management6BState&s)override{state=s;++changes;}};
InventoryRow item(const char*id,const char*name,unsigned total){InventoryRow r;r.id={CatalogId{"resources"},CatalogId{"bars"},CatalogId{id},CatalogId{},InventoryDepth::Item};r.name=name;r.total=total;return r;}
}
int main()
{
	Port p;Screen v;Management6BController c(p,v);
	check(!c.state().open,"startup hidden");c.beginWorld(WorldEpoch{41});check(!c.state().open,"world start hidden");c.openPopulation();check(c.state().open&&p.actions.back().id.value=="population.refresh","population opens");c.close();check(!c.state().open,"close hides");c.open(View::Citizens);
	PopulationRow ada{CreatureId{7},"Ada",ProfessionId{"Miner"},{{CatalogId{"Mining"},"Mining","Industry",4,.5f,true}}};PopulationRow bera{CreatureId{9},"Bera",ProfessionId{"Smith"},{}};
	check(c.applyPopulation({WorldEpoch{41},Revision{1},{bera,ada}}),"population snapshot");c.setPopulationSort(Sort::Name);check(c.visiblePopulation().front().id.value==7,"stable sort");c.movePopulationSelection(1);check(c.state().selectedCreature->value==7,"keyboard enters first row");c.movePopulationSelection(1);check(c.state().selectedCreature->value==9,"keyboard row selection");c.selectCreature(CreatureId{7});check(std::get<SelectPayload>(p.actions.back().payload).target.id==7,"creature stable id");
	check(c.applyPopulationPatch({WorldEpoch{41},Revision{1},Revision{2},PopulationRow{CreatureId{7},"Zada",ProfessionId{"Miner"},{}}}),"row patch");check(c.state().selectedCreature->value==7,"selection survives patch");c.setPopulationFilter("smith");check(c.state().selectedCreature->value==9,"filter selects visible citizen");c.movePopulationSelection(1);check(c.state().selectedCreature->value==9,"keyboard stays in filtered rows");const auto before=p.actions.size();check(!c.applyPopulationPatch({WorldEpoch{41},Revision{1},Revision{3},ada}),"wrong base");check(p.actions.size()==before+1,"refresh once");check(!c.applyPopulationPatch({WorldEpoch{41},Revision{1},Revision{4},ada})&&p.actions.size()==before+1,"refresh dedupe");check(!c.applyPopulation({WorldEpoch{40},Revision{99},{ada}}),"old epoch");
	c.open(View::Skills);check(c.state().populationView==View::Skills,"skills route opens");check(c.applySkillCatalog(WorldEpoch{41},{{CatalogId{"Mining"},"Mining","Industry"},{CatalogId{"Smithing"},"Smithing","Industry"}}),"skill catalog loads");check(c.state().selectedSkill->value=="Mining","first skill focused");c.selectSkill(CatalogId{"Smithing"});check(c.state().selectedSkill->value=="Smithing","skill focus changes");c.setSkillForAll(CatalogId{"Smithing"},true);check(std::get<SetSkillForAllPayload>(p.actions.back().payload).active,"all citizens scope");c.setAllSkills(CreatureId{7},false);check(!std::get<SetGnomeSkillsPayload>(p.actions.back().payload).active,"one citizen scope");
	c.open(View::Professions);check(c.applyProfessions({WorldEpoch{41},Revision{1},{{ProfessionId{"Gnomad"},"Gnomad",{}},{ProfessionId{"Miner"},"Miner",{CatalogId{"Mining"}}}}}),"profession roster loads");c.createProfession("Miner");check(c.state().status=="management.population.error_duplicate_name","duplicate profession rejected");c.createProfession("Carpenter");check(p.actions.back().id.value=="profession.create","profession create dispatched");c.selectProfession(ProfessionId{"Miner"});check(p.actions.back().id.value=="profession.request_skills","selected profession requests skills");c.selectAvailableSkill(CatalogId{"Smithing"});c.addProfessionSkill();check(c.state().professionDraftSkills.size()==2,"skill added to draft");c.selectProfessionSkill(CatalogId{"Smithing"});c.moveProfessionSkill(-1);check(c.state().professionDraftSkills.front().value=="Smithing","profession skill order changes");c.setProfessionDraftName("Prospector");c.saveProfession();check(p.actions.back().id.value=="profession.update","profession edit dispatched");c.selectProfession(ProfessionId{"Gnomad"});const auto protectedCount=p.confirmed.size();c.deleteProfession();check(p.confirmed.size()==protectedCount,"base profession protected");c.selectProfession(ProfessionId{"Miner"});c.deleteProfession();check(p.confirmed.size()==protectedCount+1&&p.confirmed.back().id.value=="profession.delete","delete uses confirmed dispatch");
	c.setSkill(CreatureId{7},CatalogId{"Mining"},false);check(std::get<SetSkillPayload>(p.actions.back().payload).skill.value=="Mining","skill action");ScheduleRow sa;sa.creature=CreatureId{7};ScheduleRow sb;sb.creature=CreatureId{9};check(c.applySchedules({WorldEpoch{41},Revision{1},{sa,sb}}),"schedules");c.open(View::Schedules);c.selectScheduleCell({CreatureId{7},23});c.moveScheduleFocus(1,1);check(c.state().selectedScheduleCell->creature.value==9&&c.state().selectedScheduleCell->hour==23,"schedule keyboard");c.activateScheduleCell(ScheduleActivity::Training);check(std::get<SetScheduleCellPayload>(p.actions.back().payload).activity==ScheduleActivity::Training,"training action");c.setScheduleRow(CreatureId{7},ScheduleActivity::Eat);check(std::get<SetScheduleRowPayload>(p.actions.back().payload).creature.value==7,"whole citizen schedule action");c.setScheduleColumn(23,ScheduleActivity::Sleep);check(std::get<SetScheduleColumnPayload>(p.actions.back().payload).hour==23,"same hour schedule action");const auto invalid=p.actions.size();c.setScheduleCell(CreatureId{7},24,ScheduleActivity::Sleep);check(p.actions.size()==invalid,"invalid hour");
	c.openInventory();check(p.actions.back().id.value=="inventory.refresh","inventory auto-refreshes on open");auto copper=item("bar","Copper bar",12),iron=item("ingot","Iron ingot",30);copper.stockpiled=12;iron.stockpiled=3;InventoryRow copperMaterial;copperMaterial.id={CatalogId{"resources"},CatalogId{"bars"},CatalogId{"bar"},CatalogId{"copper"},InventoryDepth::Material};copperMaterial.name="Copper";copperMaterial.total=12;copperMaterial.stockpiled=12;InventoryRow category;category.id={CatalogId{"resources"},CatalogId{},CatalogId{},CatalogId{},InventoryDepth::Category};category.name="Resources";InventoryRow group;group.id={CatalogId{"resources"},CatalogId{"bars"},CatalogId{},CatalogId{},InventoryDepth::Group};group.name="Bars";check(c.applyInventory({WorldEpoch{41},Revision{1},{category,group,iron,copper,copperMaterial}}),"inventory");check(c.visibleInventory().size()==2,"inventory projects deepest entries as flat rows");c.setInventorySort(Sort::Total);check(c.visibleInventory().front().name=="Iron ingot","inventory total sort applies to flat rows");c.setInventorySort(Sort::Stock);check(c.visibleInventory().front().name=="Copper","inventory stock sort uses leaf stockpiled quantity");c.moveInventorySelection(1);check(c.state().selectedInventory==copperMaterial.id,"inventory keyboard enters first flat row");c.moveInventorySelection(1);check(c.state().selectedInventory==iron.id,"inventory keyboard reaches next flat row");check(c.applyInventoryPatch({WorldEpoch{41},Revision{1},Revision{2},InventoryRow{copperMaterial.id,"Copper",99}}),"inventory patch");check(c.state().selectedInventory==iron.id,"inventory selection survives unrelated patch");c.selectInventory(copperMaterial.id);c.toggleSelectedWatch();check(std::get<WatchPayload>(p.actions.back().payload).row==copperMaterial.id,"typed watch targets flat leaf");const auto liveBefore=p.actions.size();c.inventoryChanged();check(p.actions.size()==liveBefore+1&&p.actions.back().id.value=="inventory.refresh","open inventory refreshes on item change");c.inventoryChanged();check(p.actions.size()==liveBefore+1,"live inventory refresh coalesces");check(c.applyInventory({WorldEpoch{41},Revision{3},{category,group,iron,copper,copperMaterial}}),"live inventory refresh snapshot");
	c.openInventoryDetail(copperMaterial.id);check(c.state().inventoryDetail==copperMaterial.id&&p.actions.back().id.value=="inventory.request_history","item drilldown requests live history");
	check(c.applyInventoryHistory(WorldEpoch{41},copperMaterial.id,{{0,12,3,1}})&&c.state().inventoryHistory.size()==1,"item history arrives for the selected material");
	c.openRelatedInventoryItem("ingot");check(c.state().inventoryDetail==iron.id&&c.state().inventoryDetailBack.size()==1,"recipe link drills into another item");
	check(!c.applyInventoryHistory(WorldEpoch{41},copperMaterial.id,{{1,99,0,0}}),"late history cannot overwrite a linked item");
	c.backInventoryDetail();check(c.state().inventoryDetail==copperMaterial.id&&c.state().inventoryDetailBack.empty(),"back restores the previous item");
	c.backInventoryDetail();check(!c.state().inventoryDetail,"back returns to inventory list");
	c.setInventoryCategory("resources");check(c.visibleInventory().size()==2,"inventory category keeps matching flat rows");c.setInventoryCategory("other");check(c.visibleInventory().empty(),"inventory category filters rows");c.setInventoryCategory("");c.setInventoryOwnedOnly(true);check(c.visibleInventory().size()==2&&c.visibleInventory()[0].total>0,"inventory owned filter keeps stocked leaves");c.setInventoryOwnedOnly(false);c.setInventoryFilter("bars");check(c.visibleInventory().size()==2,"inventory search matches ancestor columns");c.setInventoryFilter("ax");check(c.state().inventoryFilter=="ax","inventory filter accepts replacement text");c.setInventoryFilter("");check(c.state().inventoryFilter.empty()&&c.visibleInventory().size()==2,"inventory filter accepts deletion and restores all flat rows");c.setInventoryFilter("iron");check(c.state().inventoryFilter=="iron"&&c.visibleInventory().size()==1,"inventory filter accepts new word");c.setInventoryFilter("");c.setInventoryColumnFilter(0,"resources");c.setInventoryColumnFilter(1,"bars");c.setInventoryColumnFilter(2,"copper");c.setInventoryColumnFilter(3,"copper");c.setInventoryColumnFilter(4,"Has (>0)");c.setInventoryColumnFilter(5,"Has (>0)");check(c.visibleInventory().size()==1&&c.visibleInventory().front().name=="Copper","each Inventory header filters its own column");for(std::size_t column=0;column<6;++column)c.setInventoryColumnFilter(column,"");check(c.visibleInventory().size()==2,"clearing header filters restores all Inventory rows");c.toggleInventoryColumnSelection(2,"Copper bar");check(c.visibleInventory().size()==1&&c.visibleInventory().front().name=="Copper","one checklist value filters Inventory exactly");c.toggleInventoryColumnSelection(2,"Iron ingot");check(c.visibleInventory().size()==2,"multiple checklist values use OR within one Inventory column");c.toggleInventoryColumnSelection(2,"Copper bar");check(c.visibleInventory().size()==1&&c.visibleInventory().front().name=="Iron ingot","checklist values toggle independently");c.toggleInventoryColumnSelection(2,"");check(c.visibleInventory().size()==2&&c.state().inventoryColumnSelections[2].empty(),"Inventory All clears the checklist");c.setInventorySort(Sort::Category);c.setInventorySort(Sort::Group);c.setInventorySort(Sort::Item);c.setInventorySort(Sort::Material);check(c.state().inventorySort==Sort::Material,"each text header selects its sort key");c.closeInventory();check(!c.state().inventoryDetail && !c.state().historyTarget,"closing inventory clears drilldown");const auto closedBefore=p.actions.size();c.inventoryChanged();check(p.actions.size()==closedBefore,"closed inventory ignores item changes");c.openInventory();check(p.actions.back().id.value=="inventory.refresh","inventory auto-refreshes on reopen");check(c.visibleInventory().size()==2,"inventory reopens as flat rows");
	InventoryRow foodCategory;foodCategory.id={CatalogId{"food"},{},{},{},InventoryDepth::Category};foodCategory.name="Food";InventoryRow vegetables;vegetables.id={CatalogId{"food"},CatalogId{"vegetables"},{},{},InventoryDepth::Group};vegetables.name="Vegetables";InventoryRow vegetable;vegetable.id={CatalogId{"food"},CatalogId{"vegetables"},CatalogId{"vegetable"},{},InventoryDepth::Item};vegetable.name="Vegetable";InventoryRow carrot;carrot.id={CatalogId{"food"},CatalogId{"vegetables"},CatalogId{"vegetable"},CatalogId{"carrot"},InventoryDepth::Material};carrot.name="Carrot";check(c.applyInventory({WorldEpoch{41},Revision{4},{foodCategory,vegetables,vegetable,carrot}}),"four-level inventory");const auto flattened=c.visibleInventory();check(flattened.size()==1&&flattened[0].name=="Carrot","four-level hierarchy becomes one flat row");c.setInventoryFilter("vegetables");check(c.visibleInventory().size()==1&&c.visibleInventory()[0].name=="Carrot","flat row remains searchable by an ancestor column");c.setInventoryFilter("");
	std::vector<InventoryRow> large;for(std::uint32_t i=0;i<1000;++i){auto row=item(("item-"+std::to_string(i)).c_str(),("Material "+std::to_string(i)).c_str(),i);large.push_back(std::move(row));}check(c.applyInventory({WorldEpoch{41},Revision{5},std::move(large)}),"large inventory");check(c.inventoryPage().size()==1000,"continuous inventory list");c.setInventorySort(Sort::Name);for(int i=0;i<70;++i)c.moveInventorySelection(1);check(c.state().selectedInventory.has_value()&&c.inventoryPage().size()==1000,"keyboard selection traverses continuous list");
	c.setPopulationFilter("");c.selectCreature(CreatureId{7});CreatureDetail detail;detail.id=CreatureId{7};detail.name="Ada";check(c.applyCreature({WorldEpoch{41},Revision{1},detail}),"creature detail");c.endWorld();const auto count=p.actions.size();c.refresh();c.setSkill(CreatureId{7},CatalogId{"Mining"},true);check(p.actions.size()==count,"unload blocks");check(!c.state().open&&c.state().population.empty(),"unload clears");
	c.beginWorld(WorldEpoch{42});c.open(View::Professions);check(c.applyPopulation({WorldEpoch{42},Revision{1},{}}),"empty colony loads");check(c.applySkillCatalog(WorldEpoch{42},{{CatalogId{"Mining"},"Mining","Industry"}}),"full skill catalog works without citizens");check(c.applyProfessions({WorldEpoch{42},Revision{1},{{ProfessionId{"Gnomad"},"Gnomad",{}}}}),"base profession loads without citizens");c.createProfession("Scout");check(p.actions.back().id.value=="profession.create","profession creation remains available without citizens");
	std::cout<<"Management 6B controller tests passed\n";
}
