set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BState.h" STATE)
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BController.cpp" CONTROLLER)
file(READ "${ROOT}/src/gui/ui/controllers/management6b/Management6BQtDataAdapter.cpp" DATA)
file(READ "${ROOT}/src/gui/ui/controllers/management6b/Management6BQtCommandPort.cpp" PORT)
file(READ "${ROOT}/src/gui/aggregatorinventory.cpp" AGGREGATOR)
foreach(FORBIDDEN "QObject" "QString" "QPixmap" "Game\\*" "Aggregator")
  if(STATE MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "Pointer-free state contract violated by ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "WorldEpoch" "Revision" "InventoryRowId" "CreatureId" "baseRevision" "stalePopulation" "staleInventory")
  if(NOT STATE MATCHES "${NEEDLE}" AND NOT CONTROLLER MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing stable update contract ${NEEDLE}")
  endif()
endforeach()
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BRmlBinding.cpp" BINDING)
file(READ "${ROOT}/content/rmlui/windows/management6b.rcss" STYLES)
if(NOT EXISTS "${ROOT}/content/tilesheet/plants.tga")
  message(FATAL_ERROR "Missing RmlUi TGA companion for grown-item plants")
endif()
foreach(NEEDLE "population_creature_" "inventory_row_" "inventory_sort_name" "inventory_sort_total" "inventory_sort_value" "inventory_filter_owned" "setInventoryOwnedOnly" "inventory_search" "ElementFormControl" "input" "Focus" "toggleInventoryExpanded" "inventoryExpanded" "collapsedInventory" "isChildOf" "aria-expanded" "aria-pressed" "l-m6b-disclosure" "data-creature" "data-hour" "data-category" "data-material" "KI_LEFT" "KI_RIGHT" "KI_UP" "KI_DOWN" "KI_HOME" "KI_END" "KI_PRIOR" "KI_NEXT" "KI_RETURN" "KI_SPACE" "activateScheduleCell" "focusPopulationRow" "focusInventoryRow" "focusScheduleCell" "applyRmlText" "SetClass" "is-selected")
  if(NOT BINDING MATCHES "${NEEDLE}" AND NOT CONTROLLER MATCHES "${NEEDLE}" AND NOT STATE MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing stable-row or schedule keyboard binding ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "l-m6b-inventory__name-head" "text-align: left" "l-m6b-toolbar .c-dropdown-button" "l-m6b-toolbar .c-dropdown-button.is-selected" "#f1ca4f" "#edf3f3" "#536b78")
  if(NOT STYLES MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing inventory alignment/sort styling rule ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "select_first" "schedule_sleep_selected" "schedule_eat_hour")
  if(BINDING MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "Fixture shortcut leaked into production binding: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "case ::ScheduleActivity::None" "case ::ScheduleActivity::Eat" "case ::ScheduleActivity::Sleep" "case ::ScheduleActivity::Training" "!a.empty")
  if(NOT DATA MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing explicit adapter rule ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "plants.png" "food_drink_ingredients.png" "384, 144" "build_" "inventoryThumbnailFallbacks" "spriteX" "spriteY" "spriteSheetWidth" "sheetDimensions")
  if(NOT AGGREGATOR MATCHES "${NEEDLE}" AND NOT DATA MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing authoritative inventory sprite crop rule ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "aggregatorPopulation" "aggregatorInventory" "aggregatorCreatureInfo" "Qt::QueuedConnection" "UiActionRegistry" "case ScheduleActivity::None" "case ScheduleActivity::Training" "onSetActive" "onRequestCategories")
  if(NOT PORT MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing queued authoritative bridge rule ${NEEDLE}")
  endif()
endforeach()
message(STATUS "Management 6B integration contract verified")
