set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BState.h" STATE)
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BController.cpp" CONTROLLER)
file(READ "${ROOT}/src/gui/ui/controllers/management6b/Management6BQtDataAdapter.cpp" DATA)
file(READ "${ROOT}/src/gui/ui/controllers/management6b/Management6BQtCommandPort.cpp" PORT)
file(READ "${ROOT}/src/gui/aggregatorinventory.cpp" AGGREGATOR)
file(READ "${ROOT}/scripts/generate_build_icons.py" ICON_GENERATOR)
foreach(FORBIDDEN "QObject" "QString" "QPixmap" "Game\\*" "Aggregator")
  if(STATE MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "Pointer-free state contract violated by ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "WorldEpoch" "Revision" "InventoryRowId" "CreatureId" "baseRevision" "stalePopulation" "staleInventory")
  if(NOT STATE MATCHES "${NEEDLE}" AND NOT CONTROLLER MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing stable update contract ${NEEDLE}")
  endif()
endforeach()
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BRmlBinding.cpp" BINDING)
file(READ "${ROOT}/content/rmlui/windows/management6b.rcss" STYLES)
file(READ "${ROOT}/src/gui/MainWindow.cpp" WINDOW)
if(NOT EXISTS "${ROOT}/content/tilesheet/plants.tga")
  message(FATAL_ERROR "Missing RmlUi TGA companion for grown-item plants")
endif()
foreach(NEEDLE "population_creature_" "inventory_row_" "inventory_sort_name" "inventory_sort_stock" "inventory_sort_total" "inventory_filter_owned" "setInventoryOwnedOnly" "inventory_search" "ElementFormControl" "input" "GetFocusElement" "Focus" "toggleInventoryExpanded" "inventoryExpanded" "collapsedInventory" "collapseInventorySections" "inventoryExpansionInitialized_" "return visibleInventory" "isChildOf" "aria-expanded" "aria-pressed" "l-m6b-disclosure" "data-creature" "data-hour" "data-category" "data-material" "KI_LEFT" "KI_RIGHT" "KI_UP" "KI_DOWN" "KI_HOME" "KI_END" "KI_PRIOR" "KI_NEXT" "KI_RETURN" "KI_SPACE" "activateScheduleCell" "focusPopulationRow" "focusInventoryRow" "focusScheduleCell" "applyRmlText" "SetClass" "is-selected")
  if(NOT BINDING MATCHES "${NEEDLE}" AND NOT CONTROLLER MATCHES "${NEEDLE}" AND NOT STATE MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing stable-row or schedule keyboard binding ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "l-m6b-inventory__name-head" "text-align: left" "l-m6b-sort-button.is-selected" "#c0c0c0" "#000080" "border-top-color: #404040")
  if(NOT STYLES MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing inventory alignment/sort styling rule ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "baseSize( 400, 720 )" "UiWindow.population_inventory.compact2" "minimumSize( 360, 420 )" "expandedTo( minimumSize )" "setResizeMinimumSize( minimumSize )")
  string(FIND "${WINDOW}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing inventory detached-window width contract ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "state_.view = v" "refresh()" "signalInventoryCategories" "signalInventoryChanged" "inventoryChanged")
  string(FIND "${CONTROLLER}${WINDOW}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing event-driven inventory auto-refresh contract ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "select_first" "schedule_sleep_selected" "schedule_eat_hour")
  if(BINDING MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "Fixture shortcut leaked into production binding: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "case ::ScheduleActivity::None" "case ::ScheduleActivity::Eat" "case ::ScheduleActivity::Sleep" "case ::ScheduleActivity::Training" "!a.empty")
  if(NOT DATA MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing explicit adapter rule ${NEEDLE}")
  endif()
endforeach()
string(FIND "${DATA}" "mr.name=displayName(m.name,m.id);" MATERIAL_NAME_ONLY)
if(MATERIAL_NAME_ONLY EQUAL -1 OR DATA MATCHES "displayName\(m.name,m.id\).*displayName\(it.name,it.id\)")
  message(FATAL_ERROR "Inventory material rows must not repeat the parent item name")
endif()
foreach(NEEDLE "inventory_" "inventoryThumbnailSize = 40" "INVENTORY_THUMBNAIL_SIZE = 40" "INVENTORY_THUMBNAIL_INSET = 2" "make_thumbnail")
  string(FIND "${AGGREGATOR}${ICON_GENERATOR}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing normalized Inventory thumbnail rule ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "plants.png" "food_drink_ingredients.png" "384, 144" "build_" "inventoryThumbnailFallbacks" "Sprites_ByMaterials" "Sprites_ByMaterialTypes" "Sprites_Combine" "MaterialID" "setInventoryMaterialSprite" "spriteX" "spriteY" "spriteSheetWidth" "sheetDimensions")
  if(NOT AGGREGATOR MATCHES "${NEEDLE}" AND NOT DATA MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing authoritative inventory sprite crop rule ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "aggregatorPopulation" "aggregatorInventory" "aggregatorCreatureInfo" "Qt::QueuedConnection" "UiActionRegistry" "case ScheduleActivity::None" "case ScheduleActivity::Training" "onSetActive" "onRequestCategories")
  if(NOT PORT MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing queued authoritative bridge rule ${NEEDLE}")
  endif()
endforeach()
message(STATUS "Management 6B integration contract verified")
