set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/content/rmlui/windows/population_manager.rml" POP)
file(READ "${ROOT}/content/rmlui/windows/inventory_browser.rml" INV)
file(READ "${ROOT}/content/rmlui/windows/management6b.rcss" STYLE)
file(READ "${ROOT}/content/rmlui/templates/management_window.rml" WINDOW_TEMPLATE)
file(READ "${ROOT}/content/rmlui/styles/management_window.rcss" WINDOW_TEMPLATE_STYLE)
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BText.h" TEXT)
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BRmlBinding.cpp" BINDING)
foreach(ID population_root population_heading population_close population_search population_tab_citizens population_tab_professions population_tab_schedules population_rows profession_rows schedule_rows schedule_set_none schedule_set_eat schedule_set_sleep schedule_set_training creature_detail creature_attributes creature_needs creature_equipment population_loading population_page_status)
  if(NOT POP MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Population RML missing ${ID}")
  endif()
endforeach()
foreach(ID population_shell population_rail population_views_toggle population_tab_skills population_skills skills_catalog_rows skill_citizen_rows skill_enable_all skill_disable_all profession_create_name profession_create profession_name profession_selected_skills profession_available_skills profession_skill_add profession_skill_remove profession_skill_up profession_skill_down profession_save profession_delete population_delete_confirm schedule_apply_cell schedule_apply_row schedule_apply_column creature_skills_enable_all creature_skills_disable_all)
  if(NOT POP MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Population side-menu or legacy action missing ${ID}")
  endif()
endforeach()
foreach(NEEDLE "c-management-shell" "c-management-rail" "c-management-main" "aria-orientation=\"vertical\"" "data-l10n-title=" "data-l10n-aria-label=")
  string(FIND "${POP}" "${NEEDLE}" FOUND)
  if(FOUND EQUAL -1)
    message(FATAL_ERROR "Population theme or accessibility contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(ID inventory_root inventory_heading inventory_close inventory_rows inventory_column_head inventory_sort_category inventory_sort_group inventory_sort_item inventory_sort_material inventory_sort_stock inventory_sort_total inventory_filter_category inventory_filter_group inventory_filter_item inventory_filter_material inventory_filter_stock inventory_filter_total)
  if(NOT INV MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Inventory RML missing ${ID}")
  endif()
endforeach()
foreach(ID inventory_filter_category_toggle inventory_filter_group_toggle inventory_filter_item_toggle inventory_filter_material_toggle inventory_filter_stock_toggle inventory_filter_total_toggle inventory_filter_category_options inventory_filter_group_options inventory_filter_item_options inventory_filter_material_options inventory_filter_stock_options inventory_filter_total_options)
  if(NOT INV MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Inventory filter combo missing ${ID}")
  endif()
endforeach()
foreach(NEEDLE "name=\"management-window\"" "content=\"management-window-content\"" "id=\"management-window-content\"" "/styles/base.rcss" "/styles/components.rcss" "/styles/accessibility.rcss" "/styles/management_window.rcss")
  string(FIND "${WINDOW_TEMPLATE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Management window template missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "type=\"text/template\"" "/templates/management_window.rml" "<template src=\"management-window\">")
  foreach(DOCUMENT_NAME POP INV)
    string(FIND "${${DOCUMENT_NAME}}" "${NEEDLE}" POS)
    if(POS EQUAL -1)
      message(FATAL_ERROR "${DOCUMENT_NAME} production document is not consuming template contract ${NEEDLE}")
    endif()
  endforeach()
endforeach()
string(FIND "${INV}" "l-m6b-title-icon" INVENTORY_TITLE_ICON)
if(INVENTORY_TITLE_ICON EQUAL -1)
  message(FATAL_ERROR "Inventory production document is missing its title icon")
endif()
foreach(NEEDLE "c-management-window-template" "width: 100%" "height: 100%" "pointer-events: none" "> *" "pointer-events: auto")
  string(FIND "${WINDOW_TEMPLATE_STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Management window template style missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE ".c-management-shell" ".c-management-rail" "flex: 0 0 112dp" "background-color: #c0c0c0" "border-top-color: #808080" "border-right-color: #ffffff" ".c-management-views-toggle")
  string(FIND "${WINDOW_TEMPLATE_STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Management window theme contract missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${WINDOW_TEMPLATE_STYLE}" "var(" UNSUPPORTED_VARIABLE)
if(NOT UNSUPPORTED_VARIABLE EQUAL -1)
  message(FATAL_ERROR "RmlUi cannot parse CSS var() in management window styles")
endif()
foreach(NEEDLE "#inventory_workbench { color: #000000; background-color: #c0c0c0" "min-height: 27dp" "margin: 0 0 3dp" "font-size: 13dp" "background-color: #d4d0c8" "border-top-color: #404040" "border-right-color: #ffffff")
  string(FIND "${STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Management 6B does not match the Build window control contract ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "@spritesheet inventory-window-icons" "src: /tilesheet/build_Bag.tga" "inventory-window-bag: 0px 0px 32px 36px" "decorator: image(inventory-window-bag contain)")
  string(FIND "${STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inventory sprite/decorator contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "management6b.rcss" "data-l10n=" "data-l10n-placeholder=" "role=\"listbox\"" "role=\"grid\"" "tab-index=\"0\"" "l-m6b-inventory-layout" "l-m6b-inventory-main" "c-excel-header")
  if(NOT POP MATCHES "${NEEDLE}" AND NOT INV MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B RML missing localization/accessibility contract ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "l-m6b-window" "l-m6b-schedule" "l-m6b-depth-material" "l-m6b-row__sprite" "l-m6b-row__sprite-image" "min-height: 48dp" "height: 40dp" "l-m6b-inventory__metric" "l-m6b-inventory-row" "l-m6b-inventory-tabs" "scrollbarvertical" "slidertrack" "sliderbar" "sliderarrowdec" "sliderarrowinc" "overflow-y: scroll" "pointer-events: auto" "overflow: auto")
  if(NOT STYLE MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B RCSS missing classic workbench rule ${NEEDLE}")
  endif()
endforeach()
foreach(ARROW "decorator: text(\"^\")" "decorator: text(\"v\")")
  string(FIND "${STYLE}" "${ARROW}" ARROW_POS)
  if(ARROW_POS EQUAL -1)
    message(FATAL_ERROR "Management 6B RCSS missing font-safe scrollbar arrow ${ARROW}")
  endif()
endforeach()
foreach(NEEDLE "inventorySprite" "/tilesheet/" "spriteSheet" "spriteWidth" "spriteHeight")
  if(NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B inventory binding missing thumbnail rule ${NEEDLE}")
  endif()
endforeach()
string(FIND "${BINDING}" "constexpr double frame = 40.0;" INVENTORY_ICON_FRAME)
if(INVENTORY_ICON_FRAME EQUAL -1)
  message(FATAL_ERROR "Inventory icons must fill the 40dp sprite cell")
endif()
if(NOT BINDING MATCHES "l-m6b-inventory__metric" OR NOT BINDING MATCHES "l-m6b-inventory-row")
  message(FATAL_ERROR "Management 6B inventory binding does not emit aligned metric columns")
endif()
foreach(NEEDLE "management.population.title" "management.population.schedule_note" "management.inventory.title" "management.inventory.tab_all" "management.inventory.filter_owned" "management.inventory.watching_selected" "management.inventory.row_summary" "management.inventory.column.resource" "management.inventory.filters" "management.inventory.categories" "\"Item\"" "\"In Stock\"" "status.refreshing")
  if(NOT TEXT MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B owned localization catalog missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "role=\"tablist\"" "role=\"tab\"" "aria-selected=\"false\"" "c-management-rail__button")
  if(NOT POP MATCHES "${NEEDLE}" AND NOT INV MATCHES "${NEEDLE}" AND NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B property-sheet tab contract missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${INV}" "id=\"inventory_column_item\"" STATIC_ITEM_HEADER)
string(FIND "${INV}" "id=\"inventory_column_category\"" STATIC_CATEGORY_HEADER)
string(FIND "${INV}" "id=\"inventory_column_group\"" STATIC_GROUP_HEADER)
string(FIND "${INV}" "id=\"inventory_column_material\"" STATIC_MATERIAL_HEADER)
string(FIND "${INV}" "data-l10n=\"management.inventory.column.stock\">In Stock</span>" STATIC_STOCK_HEADER)
string(FIND "${INV}" "data-l10n=\"management.inventory.column.total\">Total</span>" STATIC_TOTAL_HEADER)
if(STATIC_ITEM_HEADER EQUAL -1 OR STATIC_CATEGORY_HEADER EQUAL -1 OR STATIC_GROUP_HEADER EQUAL -1 OR STATIC_MATERIAL_HEADER EQUAL -1 OR STATIC_STOCK_HEADER EQUAL -1 OR STATIC_TOTAL_HEADER EQUAL -1)
  message(FATAL_ERROR "Inventory flat catalog and quantity headers must be present")
endif()
foreach(FORBIDDEN "management.inventory.column.jobs" "management.inventory.column.equipped" "management.inventory.column.built" "management.inventory.column.loose" "management.inventory.column.value")
  if(INV MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "Removed Inventory metric is still present: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "flex-direction: column" "l-m6b-inventory-main--full" "l-inventory-flat__category" "l-inventory-flat__group" "l-inventory-flat__item" "l-inventory-flat__material" "flex: 0 0 62dp" "c-excel-header__sort" "c-excel-header__filter")
  string(FIND "${STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing compact vertical Inventory layout rule ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "std::to_string( r.inJobs )" "std::to_string( r.equipped )" "std::to_string( r.constructed )" "std::to_string( r.loose )" "std::to_string( r.totalValue )")
  string(FIND "${BINDING}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Removed Inventory metric is still emitted: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "c-excel-header" "c-excel-header__cell" "c-excel-header__sort.is-selected" "c-excel-filter-combo" "c-excel-filter-combo__toggle" "c-excel-filter-combo__options" "c-excel-filter-combo__option" "background-color: #d4d0c8" "border-top-color: #404040" "border-right-color: #ffffff" "box-sizing: border-box" "overflow-y: scroll")
  string(FIND "${STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Management 6B property-sheet tab style missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${STYLE}" "border-right-color: #404040; border-bottom-color: #404040" COMBO_COMPLETE_FRAME)
if(COMBO_COMPLETE_FRAME EQUAL -1)
  message(FATAL_ERROR "Inventory combo popup must retain a visible right and bottom frame")
endif()
foreach(ID inventory_refresh inventory_request_history inventory_history inventory_page_status inventory_page_previous inventory_page_next inventory_toggle_watch)
  if(INV MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Removed inventory footer/history control still present: ${ID}")
  endif()
endforeach()
string(FIND "${BINDING}" "input->GetValue() != value" SEARCH_SYNC_GUARD)
if(SEARCH_SYNC_GUARD EQUAL -1)
  message(FATAL_ERROR "Inventory search binding must not rewrite an unchanged live form value")
endif()
foreach(FORBIDDEN "onclick=" "onchange=" "generateRandomData" "job backlog" "health alert" "reserved total" "in transit" "inventory history")
  if(POP MATCHES "${FORBIDDEN}" OR INV MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "Unsupported or inline behavior present: ${FORBIDDEN}")
  endif()
endforeach()
message(STATUS "Management 6B RML contract verified")
