set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/content/rmlui/windows/population_manager.rml" POP)
file(READ "${ROOT}/content/rmlui/windows/inventory_browser.rml" INV)
file(READ "${ROOT}/content/rmlui/windows/management6b.rcss" STYLE)
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BText.h" TEXT)
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BRmlBinding.cpp" BINDING)
foreach(ID population_root population_heading population_close population_search population_tab_citizens population_tab_professions population_tab_schedules population_rows profession_rows schedule_rows schedule_set_none schedule_set_eat schedule_set_sleep schedule_set_training creature_detail creature_attributes creature_needs creature_equipment population_loading population_page_status)
  if(NOT POP MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Population RML missing ${ID}")
  endif()
endforeach()
foreach(ID inventory_root inventory_heading inventory_close inventory_search inventory_filters_heading inventory_filter_owned inventory_categories_heading inventory_category_tabs inventory_rows inventory_sort_name inventory_sort_stock inventory_sort_total inventory_column_head)
  if(NOT INV MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Inventory RML missing ${ID}")
  endif()
endforeach()
foreach(NEEDLE "management6b.rcss" "data-l10n=" "data-l10n-placeholder=" "role=\"listbox\"" "role=\"grid\"" "role=\"tree\"" "tab-index=\"0\"" "aria-orientation=\"vertical\"" "l-m6b-inventory-layout" "l-m6b-inventory-rail" "l-m6b-rail-heading" "l-m6b-inventory-main")
  if(NOT POP MATCHES "${NEEDLE}" AND NOT INV MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B RML missing localization/accessibility contract ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "l-m6b-window" "l-m6b-schedule" "l-m6b-depth-material" "l-m6b-row__sprite" "l-m6b-row__sprite-image" "min-height: 48dp" "height: 40dp" "l-m6b-inventory__metric" "l-m6b-inventory-row" "l-m6b-inventory-tabs" "scrollbarvertical" "slidertrack" "sliderbar" "sliderarrowdec" "sliderarrowinc" "overflow-y: scroll" "pointer-events: auto" "overflow: auto")
  if(NOT STYLE MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B RCSS missing classic workbench rule ${NEEDLE}")
  endif()
endforeach()
foreach(ARROW "decorator: text(\"^\")" "decorator: text(\"v\")")
  string(FIND "${STYLE}" "${ARROW}" ARROW_POS)
  if(ARROW_POS EQUAL -1)
    message(FATAL_ERROR "Management 6B RCSS missing font-safe scrollbar arrow ${ARROW}")
  endif()
endforeach()
foreach(NEEDLE "inventorySprite" "/tilesheet/" "spriteSheet" "spriteWidth" "spriteHeight")
  if(NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B inventory binding missing thumbnail rule ${NEEDLE}")
  endif()
endforeach()
string(FIND "${BINDING}" "constexpr double frame = 40.0;" INVENTORY_ICON_FRAME)
if(INVENTORY_ICON_FRAME EQUAL -1)
  message(FATAL_ERROR "Inventory icons must fill the 40dp sprite cell")
endif()
if(NOT BINDING MATCHES "l-m6b-inventory__metric" OR NOT BINDING MATCHES "l-m6b-inventory-row")
  message(FATAL_ERROR "Management 6B inventory binding does not emit aligned metric columns")
endif()
foreach(NEEDLE "management.population.title" "management.population.schedule_note" "management.inventory.title" "management.inventory.tab_all" "management.inventory.filter_owned" "management.inventory.watching_selected" "management.inventory.row_summary" "management.inventory.column.resource" "management.inventory.filters" "management.inventory.categories" "\"Item\"" "\"In Stock\"" "status.refreshing")
  if(NOT TEXT MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B owned localization catalog missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "role=\"tablist\"" "role=\"tab\"" "aria-selected=\"false\"" "c-tabs__tab")
  if(NOT POP MATCHES "${NEEDLE}" AND NOT INV MATCHES "${NEEDLE}" AND NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B property-sheet tab contract missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${INV}" "<span class=\"l-m6b-inventory__name-head\"" STATIC_ITEM_HEADER)
string(FIND "${INV}" "data-l10n=\"management.inventory.column.stock\">In Stock</span>" STATIC_STOCK_HEADER)
string(FIND "${INV}" "<span class=\"l-m6b-inventory__metric-head\" data-l10n=\"management.inventory.column.total\"" STATIC_TOTAL_HEADER)
if(STATIC_ITEM_HEADER EQUAL -1 OR STATIC_STOCK_HEADER EQUAL -1 OR STATIC_TOTAL_HEADER EQUAL -1)
  message(FATAL_ERROR "Inventory Item, In Stock, and Total headers must be static labels")
endif()
foreach(FORBIDDEN "management.inventory.column.jobs" "management.inventory.column.equipped" "management.inventory.column.built" "management.inventory.column.loose" "management.inventory.column.value")
  if(INV MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "Removed Inventory metric is still present: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "flex-direction: column" "flex: 0 0 112dp" "l-m6b-inventory-main" "l-m6b-depth-item { padding-left: 16dp" "l-m6b-depth-material { padding-left: 24dp" "flex: 0 0 50dp")
  string(FIND "${STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing compact vertical Inventory layout rule ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "std::to_string( r.inJobs )" "std::to_string( r.equipped )" "std::to_string( r.constructed )" "std::to_string( r.loose )" "std::to_string( r.totalValue )")
  string(FIND "${BINDING}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Removed Inventory metric is still emitted: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "l-m6b-inventory-rail" "l-m6b-rail-section--categories" "l-m6b-rail-heading" "text-transform: uppercase" "l-m6b-rail-button.is-checked" "padding: 5dp 5dp 3dp 7dp" "background-color: #d4d0c8" "border-top-color: #404040" "border-right-color: #ffffff" "box-sizing: border-box" "overflow-x: hidden" "overflow-y: scroll")
  string(FIND "${STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Management 6B property-sheet tab style missing ${NEEDLE}")
  endif()
endforeach()
foreach(ID inventory_refresh inventory_request_history inventory_history inventory_page_status inventory_page_previous inventory_page_next inventory_toggle_watch)
  if(INV MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Removed inventory footer/history control still present: ${ID}")
  endif()
endforeach()
string(FIND "${BINDING}" "control->GetValue() != s.inventoryFilter" SEARCH_SYNC_GUARD)
if(SEARCH_SYNC_GUARD EQUAL -1)
  message(FATAL_ERROR "Inventory search binding must not rewrite an unchanged live form value")
endif()
foreach(FORBIDDEN "onclick=" "onchange=" "generateRandomData" "job backlog" "health alert" "reserved total" "in transit" "inventory history")
  if(POP MATCHES "${FORBIDDEN}" OR INV MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "Unsupported or inline behavior present: ${FORBIDDEN}")
  endif()
endforeach()
message(STATUS "Management 6B RML contract verified")
