set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/content/rmlui/windows/population_manager.rml" POP)
file(READ "${ROOT}/content/rmlui/windows/inventory_browser.rml" INV)
file(READ "${ROOT}/content/rmlui/windows/management6b.rcss" STYLE)
file(READ "${ROOT}/content/rmlui/styles/components.rcss" REPORT_STYLES)
string(APPEND STYLE "${REPORT_STYLES}")
file(READ "${ROOT}/content/rmlui/templates/management_window.rml" WINDOW_TEMPLATE)
file(READ "${ROOT}/content/rmlui/styles/management_window.rcss" WINDOW_TEMPLATE_STYLE)
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BText.h" TEXT)
file(READ "${ROOT}/src/gui/ui/screens/management6b/Management6BRmlBinding.cpp" BINDING)
foreach(ID population_root population_heading population_close population_search population_tab_citizens population_tab_professions population_tab_schedules population_rows profession_rows schedule_rows schedule_set_none schedule_set_eat schedule_set_sleep schedule_set_training population_loading population_page_status)
  if(NOT POP MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Population RML missing ${ID}")
  endif()
endforeach()
# Stage 12: Population is a Windows 98 property sheet with connected tabs, sortable list view headings,
# a drop-down list of professions, the two-list skill editor and a single Close button.
foreach(ID population_tabs population_workbench population_tab_skills population_skills skills_catalog_rows skill_citizen_rows skill_enable_all skill_disable_all profession_create profession_delete profession_name profession_selected_skills profession_available_skills profession_skill_add profession_skill_remove profession_skill_up profession_skill_down profession_save profession_discard population_sort_name population_sort_profession population_open_citizen population_refresh population_close_button)
  if(NOT POP MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Population property sheet missing ${ID}")
  endif()
endforeach()
foreach(NEEDLE "w98-sheet" "w98-caption" "c-connected-tabs" "w98-listview" "w98-buttonbar" "role=\"tablist\"")
  string(FIND "${POP}" "${NEEDLE}" FOUND)
  if(FOUND EQUAL -1)
    message(FATAL_ERROR "Population Windows 98 contract missing ${NEEDLE}")
  endif()
endforeach()
# Stage 21b: Inventory is a Windows 98 report window (Close only) and Item Properties a subordinate sheet.
foreach(ID inventory_root inventory_workbench inventory_heading inventory_close inventory_close_button inventory_search inventory_category inventory_rows inventory_sort_item inventory_sort_material inventory_sort_stock inventory_sort_total inventory_owned_only inventory_matches inventory_open_item
    inventory_detail inventory_detail_title inventory_detail_close inventory_detail_close_button inventory_detail_tabs inventory_detail_tab_general inventory_detail_tab_stockpiles inventory_detail_tab_recipes inventory_detail_tab_history
    inventory_detail_watch inventory_detail_locations inventory_detail_open_stockpile inventory_detail_made_by inventory_detail_used_in inventory_detail_open_product inventory_detail_history)
  if(NOT INV MATCHES "id=\"${ID}\"")
    message(FATAL_ERROR "Inventory window missing ${ID}")
  endif()
endforeach()
foreach(NEEDLE "w98-sheet" "w98-caption" "w98-listview" "w98-listview__heading" "w98-buttonbar" "(All)" ">Close</button>" ">Properties</button>" "Items (check an item to watch it):" "Watch this item" "Stored in these stockpiles:" "Made by:" "Used to make:")
  string(FIND "${INV}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inventory Windows 98 contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "c-excel-header" "c-excel-filter-combo" "inventory_filter_" "inventory_detail_back" "inventory_clear_filters" "l-m6b-item-detail" "inventory_tooltip")
  string(FIND "${INV}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Retired Inventory surface remains: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "setInventoryFilter" "setInventoryCategory" "setInventoryOwnedOnly" "setWatched" "openInventoryDetail" "closeInventoryDetail" "openRelatedInventoryItem" "stockpileOpenHandler_" "syncInventoryRows" "role='row'")
  string(FIND "${BINDING}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inventory binding missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "name=\"management-window\"" "content=\"management-window-content\"" "id=\"management-window-content\"" "/styles/base.rcss" "/styles/components.rcss" "/styles/management_window.rcss")
  string(FIND "${WINDOW_TEMPLATE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Management window template missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "type=\"text/template\"" "/templates/management_window.rml" "<template src=\"management-window\">")
  foreach(DOCUMENT_NAME POP INV)
    string(FIND "${${DOCUMENT_NAME}}" "${NEEDLE}" POS)
    if(POS EQUAL -1)
      message(FATAL_ERROR "${DOCUMENT_NAME} production document is not consuming template contract ${NEEDLE}")
    endif()
  endforeach()
endforeach()
# Secondary windows use the Windows 98 caption; the title bar carries no icon.
string(FIND "${INV}" "w98-caption" INVENTORY_CAPTION)
if(INVENTORY_CAPTION EQUAL -1)
  message(FATAL_ERROR "Inventory production document is missing its Windows caption")
endif()
foreach(NEEDLE "c-management-window-template" "width: 100%" "height: 100%" "pointer-events: none" "> *" "pointer-events: auto")
  string(FIND "${WINDOW_TEMPLATE_STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Management window template style missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE ".c-management-shell" ".c-management-rail" ".c-management-views-toggle")
  string(FIND "${WINDOW_TEMPLATE_STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Management window theme contract missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${WINDOW_TEMPLATE_STYLE}" "var(" UNSUPPORTED_VARIABLE)
if(NOT UNSUPPORTED_VARIABLE EQUAL -1)
  message(FATAL_ERROR "RmlUi cannot parse CSS var() in management window styles")
endif()
foreach(ARROW "decorator: image(win98-up scale-none center center)" "decorator: image(win98-down scale-none center center)")
  string(FIND "${STYLE}" "${ARROW}" ARROW_POS)
  if(ARROW_POS EQUAL -1)
    message(FATAL_ERROR "Management 6B RCSS missing font-safe scrollbar arrow ${ARROW}")
  endif()
endforeach()
foreach(NEEDLE "management.population.title" "management.population.schedule_note" "management.inventory.title" "management.inventory.tab_all" "management.inventory.filter_owned" "management.inventory.watching_selected" "management.inventory.row_summary" "management.inventory.column.resource" "management.inventory.filters" "management.inventory.categories" "\"Item\"" "\"In Stock\"" "status.refreshing")
  if(NOT TEXT MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B owned localization catalog missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "role=\"tablist\"" "role=\"tab\"" "aria-selected=\"false\"")
  if(NOT POP MATCHES "${NEEDLE}" AND NOT INV MATCHES "${NEEDLE}" AND NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Management 6B property-sheet tab contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "onclick=" "onchange=" "generateRandomData" "job backlog" "health alert" "reserved total" "in transit" "inventory history")
  if(POP MATCHES "${FORBIDDEN}" OR INV MATCHES "${FORBIDDEN}")
    message(FATAL_ERROR "Unsupported or inline behavior present: ${FORBIDDEN}")
  endif()
endforeach()
message(STATUS "Management 6B RML contract verified")

# Accessibility overrides belong after the route stylesheet (Stage 02 cascade).
foreach(DOCUMENT_NAME POP INV)
  string(FIND "${${DOCUMENT_NAME}}" "/windows/management6b.rcss" ROUTE_STYLE)
  string(FIND "${${DOCUMENT_NAME}}" "/styles/accessibility.rcss" ACCESS_STYLE)
  if(ROUTE_STYLE EQUAL -1 OR ACCESS_STYLE LESS ROUTE_STYLE)
    message(FATAL_ERROR "${DOCUMENT_NAME} must load accessibility after its route style")
  endif()
endforeach()
# Stage 16 (POP-05): Properties opens the one creature inspector, so Population has no second citizen detail page.
string(FIND "${POP}" "id=\"creature_detail\"" DETAIL)
if(NOT DETAIL EQUAL -1)
  message(FATAL_ERROR "Population must not keep its own citizen detail page")
endif()
