#include "gui/ui/screens/management6a/Management6AController.h"
#include <cstdlib>
#include <iostream>
using namespace ingnomia::ui;using namespace ingnomia::ui::management6a;
namespace
{
void check(bool v,const char*m){if(!v){std::cerr<<m<<'\n';std::exit(1);}}
CatalogId cid(const char*v){return CatalogId{v};}
struct Port:CommandPort{std::vector<UiActionEnvelope>actions;std::vector<DispatchOrigin>origins;CommandResult next{};CommandResult dispatch(const UiActionEnvelope&a,DispatchOrigin origin)override{if(a.id.value=="trade.execute"&&origin!=DispatchOrigin::DestructiveConfirmation)return{CommandStatus::Rejected,false,"ui.error.confirmation_required"};actions.push_back(a);origins.push_back(origin);return next;}};
struct View:ViewPort{Management6AState state;int changes{};void stateChanged(const Management6AState&s)override{state=s;++changes;}};
WorkshopComponentRow component(const char*item,std::uint32_t amount,const char*material,std::uint32_t available){WorkshopComponentRow out;out.item=cid(item);out.amount=amount;out.requireSameMaterial=true;out.materials.push_back({cid(material),available});return out;}
CraftQueueRow job(std::uint32_t id,const char*craft,CraftRepeatMode mode,std::uint32_t count){CraftQueueRow out;out.id={id};out.craft=cid(craft);out.item=cid(craft);out.mode=mode;out.count=count;out.materials.push_back(cid("iron"));return out;}
}
void filterPreorderTest(){Port port;View view;Management6AController c(port,view);c.beginWorld(WorldEpoch{62});StockpileSnapshot sp;sp.id={20};StockpileFilterRowId category{sp.id,cid("raw"),{},{},{},FilterDepth::Category};StockpileFilterRowId group{sp.id,cid("raw"),cid("stone"),{},{},FilterDepth::Group};StockpileFilterRowId item{sp.id,cid("raw"),cid("stone"),cid("block"),{},FilterDepth::Item};StockpileFilterRowId material{sp.id,cid("raw"),cid("stone"),cid("block"),cid("granite"),FilterDepth::Material};sp.filters={{category,"Z Category",TriState::Mixed},{group,"A Group",TriState::Mixed},{item,"B Item",TriState::Mixed},{material,"C Material",TriState::On}};c.showStockpile(StockpileSnapshot{sp},Revision{1},WorldPosition{4,5,6});check(c.state().stockpile.visibleFilters.size()==4&&c.state().stockpile.visibleFilters[0].label=="Z Category"&&c.state().stockpile.visibleFilters[1].label=="A Group"&&c.state().stockpile.visibleFilters[3].label=="C Material","stockpile filter preorder preserves hierarchy");sp.filters[1].state=TriState::Off;c.showStockpile(std::move(sp),Revision{2},WorldPosition{4,5,6});check(c.state().stockpile.visibleFilters.size()==2&&c.state().stockpile.visibleFilters[0].label=="Z Category"&&c.state().stockpile.visibleFilters[1].label=="A Group","stockpile filter disclosure follows original tri-state expansion");}
void mixedFilterMutationTest(){Port port;View view;Management6AController c(port,view);c.beginWorld(WorldEpoch{63});StockpileSnapshot sp;sp.id={21};StockpileFilterRowId group{sp.id,cid("raw"),cid("stone"),{},{},FilterDepth::Group};sp.filters.push_back({group,"Stone",TriState::Mixed});c.showStockpile(sp,Revision{1},WorldPosition{4,5,6});c.selectStockpileFilter(group);c.toggleSelectedStockpileFilter();check(port.actions.back().id.value=="stockpile.set_filter"&&!std::get<SetStockpileFilterPayload>(port.actions.back().payload).active,"mixed stockpile filter resolves inactive like original nullable checkbox");}
void filterKeyboardSelectionTest(){Port port;View view;Management6AController c(port,view);c.beginWorld(WorldEpoch{65});StockpileSnapshot sp;sp.id={23};for(const auto& row:std::array<std::pair<const char*,FilterDepth>,3>{{{"category",FilterDepth::Category},{"group",FilterDepth::Group},{"item",FilterDepth::Item}}}){const auto state=row.second==FilterDepth::Item?TriState::On:TriState::Mixed;sp.filters.push_back({StockpileFilterRowId{sp.id,cid("raw"),row.second>=FilterDepth::Group?cid("stone"):CatalogId{},row.second>=FilterDepth::Item?cid("block"):CatalogId{},CatalogId{},row.second},row.first,state});}c.showStockpile(sp,Revision{1},WorldPosition{4,5,6});c.moveStockpileFilterSelection(1);check(c.state().stockpile.selectedFilter&&c.state().stockpile.selectedFilter->depth==FilterDepth::Group,"stockpile filter keyboard down moves visible preorder");c.moveStockpileFilterSelection(1);check(c.state().stockpile.selectedFilter&&c.state().stockpile.selectedFilter->depth==FilterDepth::Item,"stockpile filter keyboard down reaches last row");c.moveStockpileFilterSelection(1);check(c.state().stockpile.selectedFilter&&c.state().stockpile.selectedFilter->depth==FilterDepth::Item,"stockpile filter keyboard clamps at last row");c.moveStockpileFilterSelection(-2147483647);check(c.state().stockpile.selectedFilter&&c.state().stockpile.selectedFilter->depth==FilterDepth::Category,"stockpile filter keyboard Home clamps at first row");}
void stockpilePullPayloadTest(){Port port;View view;Management6AController c(port,view);c.beginWorld(WorldEpoch{64});StockpileSnapshot sp;sp.id={22};sp.name="Pull test";sp.priority=1;c.showStockpile(sp,Revision{1},WorldPosition{4,5,6});c.setStockpileBasics("Pull test",1,false,true,false);const auto& payload=std::get<SetStockpileBasicsPayload>(port.actions.back().payload);check(port.actions.back().id.value=="stockpile.set_basics"&&payload.priority==1&&payload.pull&&!payload.allowPull,"stockpile pull payload preserves original flag order");}
int main()
{
	filterPreorderTest();
	mixedFilterMutationTest();
	filterKeyboardSelectionTest();
	stockpilePullPayloadTest();
	Port port;View view;Management6AController c(port,view);c.beginWorld(WorldEpoch{61});c.showLoading(ManagementView::Workshop);check(c.state().workshop.request.status==RequestStatus::Loading,"workshop loading state");c.showError(ManagementView::Workshop,"ui.error.fixture");check(c.state().workshop.request.status==RequestStatus::Error,"workshop error state");
	WorkshopSnapshot ws;ws.id={10};ws.name="Forge";ws.priority=2;ws.maxPriority=5;WorkshopProductRow saw;saw.id=cid("saw");saw.components.push_back(component("blade",1,"iron",3));WorkshopProductRow axe;axe.id=cid("axe");axe.components.push_back(component("head",1,"iron",4));ws.products.push_back(saw);ws.products.push_back(axe);ws.queue.push_back(job(81,"saw",CraftRepeatMode::Once,2));ws.queue.push_back(job(82,"axe",CraftRepeatMode::Repeat,1));ws.queue.back().moveBack=true;c.showWorkshop(ws,Revision{1},WorldPosition{1,2,3});c.selectWorkshopProduct(cid("saw"));c.setSearch("axe");check(c.state().workshop.selectedProduct->value=="saw"&&c.state().workshop.selectionFiltered,"filter preserves hidden stable selection");c.toggleSort();check(c.state().workshop.selectedProduct->value=="saw","sort preserves selection");c.setSearch("");
	c.setWorkshopBasics("Forge II",3,true,true,false);check(port.actions.back().id.value=="workshop.set_basics"&&std::get<SetWorkshopBasicsPayload>(port.actions.back().payload).priority==3,"workshop basics action");c.setWorkshopBasics("Forge II",3,true,true,false,true);check(std::get<SetWorkshopBasicsPayload>(port.actions.back().payload).linkStockpile==std::optional<bool>{true},"workshop link action enables explicit link state");c.setWorkshopBasics("Forge II",3,true,true,false,false);check(std::get<SetWorkshopBasicsPayload>(port.actions.back().payload).linkStockpile==std::optional<bool>{false},"workshop link action disables explicit link state");c.queueSelectedCraftDefault();check(port.actions.back().id.value=="workshop.queue_craft"&&std::get<QueueCraftPayload>(port.actions.back().payload).materials.front().value=="iron","queue uses real available material");c.selectWorkshopJob(CraftJobId{82});c.moveSelectedJob(MoveDirection::Up);check(port.actions.back().id.value=="workshop.move_job"&&std::get<MoveCraftJobPayload>(port.actions.back().payload).job.value==82,"stable queue move action");c.cancelSelectedJob();check(port.actions.back().id.value=="workshop.cancel_job","queue cancel action");
	auto updated=job(82,"axe",CraftRepeatMode::Repeat,5);updated.moveBack=true;StableRowPatch<CraftJobId,CraftQueueRow> patch{PatchKind::Update,CraftJobId{82},updated,{}};check(c.patchWorkshopQueue(Revision{1},Revision{2},{patch}),"matching queue patch applies");check(c.state().workshop.selectedJob->value==82&&c.state().workshop.value.queue.back().count==5,"queue patch retains selection");const auto before=c.state().workshop.value.queue;check(!c.patchWorkshopQueue(Revision{1},Revision{3},{patch})&&c.state().workshop.value.queue==before,"stale patch is atomic");c.showWorkshop(ws,Revision{4},WorldPosition{1,2,3});
	TradeRow trade{{TradeParty::Trader,cid("cloth"),cid("wool"),0},"Cloth",4,1,12};c.setTradeRows(TradeParty::Trader,{trade});c.selectTradeRow(trade.id);check(c.state().workshop.selectedTradeRow==trade.id,"direct stable trade selection");c.setTradeValues(12,5);const auto actionCount=port.actions.size();c.executeTrade();check(port.actions.size()==actionCount&&c.state().status=="ui.trade.offer_value_too_low","trade value constraint blocks execution");c.setTradeValues(12,20);c.executeTrade();check(c.state().workshop.tradeConfirmationRequired&&port.actions.size()==actionCount,"trade requires explicit confirmation");c.setWorkshopBasics("blocked",1,false,false,false);check(port.actions.size()==actionCount&&c.state().status=="ui.error.input_blocked_by_confirmation","confirmation blocks workbench input");c.cancelTrade();check(!c.state().workshop.tradeConfirmationRequired,"cancel clears confirmation blocker");UiActionEnvelope direct{ActionId{"trade.execute"},RequestId{999},WorldEpoch{61},std::nullopt,WorkshopTargetPayload{WorkshopId{10}}};check(port.dispatch(direct,DispatchOrigin::Workbench).status==CommandStatus::Rejected,"direct unconfirmed trade execution rejected");c.executeTrade();c.confirmTrade();check(port.actions.back().id.value=="trade.execute"&&port.origins.back()==DispatchOrigin::DestructiveConfirmation,"confirmed trade uses exact action and origin");
	StockpileSnapshot sp;sp.id={20};sp.name="Stone";StockpileFilterRowId stoneId{sp.id,cid("raw"),cid("stone"),cid("block"),cid("granite"),FilterDepth::Material};sp.filters.push_back({stoneId,"Granite",TriState::On});StockpileContentRow content;content.id={cid("block"),cid("granite")};content.itemName="Block";content.materialName="Granite";content.count=7;sp.contents.push_back(content);for(std::uint32_t n=0;n<200;++n){StockpileContentRow large;large.id={CatalogId{"item_"+std::to_string(n)},cid("granite")};large.itemName="Synthetic item "+std::to_string(n);large.materialName="Granite";large.count=n;sp.contents.push_back(std::move(large));}c.showStockpile(sp,Revision{1},WorldPosition{4,5,6});check(c.state().stockpile.visibleContents.size()==201,"synthetic large list remains data-complete before DOM windowing");c.selectStockpileFilter(stoneId);c.setSearch("missing");check(c.state().stockpile.selectedFilter==stoneId&&c.state().stockpile.selectionFiltered,"stockpile filter preserves stable selection");c.setSearch("");c.toggleSelectedStockpileFilter();check(port.actions.back().id.value=="stockpile.set_filter"&&!std::get<SetStockpileFilterPayload>(port.actions.back().payload).active,"stockpile filter mutation");c.setStockpileBasics("Stone II",2,true,true,false);check(port.actions.back().id.value=="stockpile.set_basics","stockpile basics mutation");
	AgricultureSnapshot ag;ag.target={AgricultureKind::Pasture,DesignationId{30}};ag.name="Yak pasture";ag.maxMale=2;ag.maxFemale=4;PastureAnimalRow animal;animal.id={99};animal.name="Moss";animal.species=cid("yak");ag.animals.push_back(animal);PastureFoodRow food;food.item=cid("hay");food.material=cid("grass");food.name="Grass hay";food.allowed=true;ag.foods.push_back(food);c.showAgriculture(ag,Revision{1},WorldPosition{7,8,9});c.selectAgricultureAnimal(CreatureId{99});c.toggleSelectedAnimalButchering();check(port.actions.back().id.value=="agriculture.set_butchering"&&std::get<SetButcheringPayload>(port.actions.back().payload).creature.value==99,"pasture roster mutation");c.setPastureCap(Gender::Female,5);check(port.actions.back().id.value=="agriculture.set_population_caps","pasture cap mutation");c.setPastureFood(cid("hay"),cid("grass"),false);check(port.actions.back().id.value=="agriculture.set_food_allowed","pasture food mutation");c.locate();check(port.actions.back().id.value=="view.center_on","locate action");
	c.endWorld();const auto after=port.actions.size();c.refresh();c.setAgricultureBasics("late",1,false);check(port.actions.size()==after&&!c.state().world&&c.state().view==ManagementView::None,"world unload clears and blocks late actions");std::cout<<"Management 6A controller lifecycle, identity, patch, filter, and mutation tests passed\n";
}
