set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
set(ALL_RML)
foreach(FILE IN ITEMS content/rmlui/windows/workshop_manager.rml content/rmlui/windows/stockpile_manager.rml content/rmlui/panels/agriculture_manager.rml)
  file(READ "${ROOT}/${FILE}" RML)
  string(APPEND ALL_RML "${RML}")
  string(REGEX MATCHALL "id=\"[^\"]+\"" IDS "${RML}")
  set(SEEN)
  foreach(ID IN LISTS IDS)
    list(FIND SEEN "${ID}" INDEX)
    if(NOT INDEX EQUAL -1)
      message(FATAL_ERROR "Duplicate RML ID in ${FILE}: ${ID}")
    endif()
    list(APPEND SEEN "${ID}")
  endforeach()
  foreach(NEEDLE "../styles/base.rcss" "../styles/components.rcss" "management6a.rcss" "l-m6a-root is-hidden" "_loading" "_empty" "_error" "_close" "_locate" "_refresh")
    string(FIND "${RML}" "${NEEDLE}" POS)
    if(POS EQUAL -1)
      message(FATAL_ERROR "Missing management 6A RML contract ${NEEDLE} in ${FILE}")
    endif()
  endforeach()
endforeach()
file(READ "${ROOT}/content/rmlui/windows/workshop_manager.rml" WORKSHOP_RML)
file(READ "${ROOT}/content/rmlui/panels/agriculture_manager.rml" AGRICULTURE_RML)
foreach(SCREEN IN ITEMS WORKSHOP_RML AGRICULTURE_RML)
  foreach(NEEDLE "_search" "_sort" "_page_previous" "_page_next")
    string(FIND "${${SCREEN}}" "${NEEDLE}" POS)
    if(POS EQUAL -1)
      message(FATAL_ERROR "Missing paged management contract ${NEEDLE}")
    endif()
  endforeach()
endforeach()
foreach(NEEDLE "workshop_trade_confirmation" "workshop_trade_confirm" "workshop_trade_cancel")
  string(FIND "${ALL_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing blocking trade confirmation element: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "workshop_product_selection" "c-workshop-editor" "workshop_queue_once" "workshop_add_order" "workshop_job_selection")
  string(FIND "${WORKSHOP_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing placed-workshop order editor contract: ${NEEDLE}")
  endif()
endforeach()
file(READ "${ROOT}/content/rmlui/windows/stockpile_manager.rml" STOCKPILE_RML)
foreach(NEEDLE "stockpile_filters" "stockpile_rows" "stockpile_filter_count" "stockpile_content_count" "stockpile_filter_search" "stockpile_content_search" "stockpile_allow_bulk" "stockpile_block_bulk" "stockpile_view_contents" "stockpile_view_allow" "stockpile_hauling_toggle" "stockpile_hauling_options" "stockpile_toggle_suspended" "stockpile_toggle_pull" "stockpile_toggle_allow_pull" "stockpile_priority_up" "stockpile_priority_down" "type=\"number\"" "step=\"1\"" "stockpile_tooltip" "role=\"tooltip\"" "c-stockpile-table-header" "c-m6a-filter-list" "c-m6a-content-list" "stockpile_nothing_allowed")
  string(FIND "${STOCKPILE_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing truthful Stockpile content/unsupported-surface contract: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "role=\"tablist\"" "role=\"tab\"" "aria-selected=\"true\"" "c-tabs__tab")
  string(FIND "${STOCKPILE_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile property-sheet tab contract missing: ${NEEDLE}")
  endif()
endforeach()

foreach(FORBIDDEN "stockpile_copy" "stockpile_paste" "stockpile_limit" "stockpile_limits" "stockpile_page_previous" "stockpile_page_next" "stockpile_search" "stockpile_view_split" "view_split")
  string(FIND "${STOCKPILE_RML}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Fabricated unsupported Stockpile control remains: ${FORBIDDEN}")
  endif()
endforeach()
file(READ "${ROOT}/content/rmlui/screens/management6a.rcss" RCSS)
foreach(NEEDLE ".l-stockpile-view-tabs" "gap: 0" "margin: 0 -1dp -2dp 0" "border-bottom-color: #cbd5d9")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile property-sheet tab style missing: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE ".c-workshop-editor" ".c-workshop-mode-button" ".c-workshop-material-button" ".is-shortage")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing placed-workshop Windows 98 editor style: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "pointer-events: none" "pointer-events: auto" "overflow-y: auto" "overflow-x: auto" "display: flex" "flex-direction: column" "height: 100%" "min-height: 0" ".c-m6a-filter-icon" ".c-m6a-filter-icon-image" ".is-selected" ".is-error" ".c-m6a-blocker" ".c-m6a-filter-depth-0" ".c-m6a-filter-depth-3" ".c-m6a-section-heading" ".c-m6a-content-material" "min-width: max-content" "height: 34dp" "text-overflow: clip" "white-space: nowrap" "word-break: normal")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing management 6A input/responsive/state style: ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "estimated time" "items per hour" "hauling backlog" "editable limit")
  string(TOLOWER "${ALL_RML}" LOWER_RML)
  string(FIND "${LOWER_RML}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Fabricated unsupported management datum: ${FORBIDDEN}")
  endif()
endforeach()
string(FIND "${RCSS}" "@media" UNSUPPORTED_MEDIA)
if(NOT UNSUPPORTED_MEDIA EQUAL -1)
  message(FATAL_ERROR "Unsupported RmlUi @media rule remains in management 6A styles")
endif()
foreach(NEEDLE "workshop_product_selection" "c-workshop-editor" "workshop_queue_once" "workshop_add_order" "workshop_job_selection")
  string(FIND "${WORKSHOP_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing placed-workshop order editor contract: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE ".c-workshop-editor" ".c-workshop-mode-button" ".c-workshop-material-button" ".is-shortage")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing placed-workshop Windows 98 editor style: ${NEEDLE}")
  endif()
endforeach()
message(STATUS "Management 6A RML IDs, state surfaces, keyboard buttons, and map ownership passed")
