set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/src/gui/ui/controllers/management6a/Management6AQtCommandPort.cpp" PORT)
file(READ "${ROOT}/src/gui/ui/controllers/management6a/Management6AIntegration.cpp" INTEGRATION)
file(READ "${ROOT}/src/gui/ui/screens/management6a/Management6ARmlBinding.cpp" BINDING)
file(READ "${ROOT}/src/gui/ui/controllers/management6a/Management6AQtDataAdapter.cpp" ADAPTER)
foreach(NEEDLE onCraftItem onCraftJobParams onCraftJobCommand onTrade onSetActive onSetBasicOptions onSelectProduct onSetHarvestOptions onSetGroveOptions onSetMaxMale onSetMaxFemale onSetButchering onSetFoodItemChecked onCenterCamera Qt::QueuedConnection)
  string(FIND "${PORT}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing authoritative management 6A command route: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "DispatchOrigin::DestructiveConfirmation" "action.id.value == \"trade.execute\"" "ModalKind::DestructiveConfirmation")
  string(FIND "${PORT}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing scoped trade confirmation validation evidence: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE signalUpdateInfo signalUpdateContent signalUpdateCraftList signalTraderStock signalPlayerStock signalUpdateFarm signalUpdatePasture signalUpdateGrove signalGlobalPlantInfo signalGlobalAnimalInfo signalGlobalTreeInfo WorldEpoch Revision)
  string(FIND "${INTEGRATION}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing management 6A queued integration seam: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE RemoveEventListener UnloadDocument "windows/workshop_manager.rml" "windows/stockpile_manager.rml" "panels/agriculture_manager.rml" GetFocusElement pageSize_ workshopPage_ stockpilePage_ agriculturePage_ "\"input\"" "\"change\"" connectStockpile workshop_toggle_linked data-depth c-m6a-filter-depth- aria-expanded aria-selected aria-checked keydown KI_UP KI_DOWN KI_HOME KI_END KI_RETURN KI_SPACE moveStockpileFilterSelection Focus stockpile_filter_selection stateName "Selected: " setFormValueForProbe setStockpileSearchForProbe activateFirstStockpileFilterForProbe activateStockpileFilterForProbe dispatchStockpileFilterKeyForProbe stockpileFilterRowId "stockpile_priority\",s.priority+1,s.maxPriority)-1")
  string(FIND "${BINDING}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing management 6A binding/lifecycle/input evidence: ${NEEDLE}")
  endif()
endforeach()
file(READ "${ROOT}/src/gui/ui/controllers/management6a/Management6AQtDataAdapter.cpp" ADAPTER)
foreach(NEEDLE "if ( value.count > 0 )" "out.contents.push_back")
  string(FIND "${ADAPTER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing positive-count Stockpile current-contents projection guard: ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "QPointer<Game>" "QPixmap" "Game*" "QObject*")
  string(FIND "${ADAPTER}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Pointer/resource leaked into management 6A presentation adapter: ${FORBIDDEN}")
  endif()
endforeach()
message(STATUS "Management 6A pointer-free DTO copy, queued ports, and teardown evidence passed")
