set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
set(ALL_RML)
foreach(FILE IN ITEMS content/rmlui/windows/workshop_manager.rml content/rmlui/windows/stockpile_manager.rml content/rmlui/panels/agriculture_manager.rml)
  file(READ "${ROOT}/${FILE}" RML)
  string(APPEND ALL_RML "${RML}")
  string(REGEX MATCHALL "id=\"[^\"]+\"" IDS "${RML}")
  set(SEEN)
  foreach(ID IN LISTS IDS)
    list(FIND SEEN "${ID}" INDEX)
    if(NOT INDEX EQUAL -1)
      message(FATAL_ERROR "Duplicate RML ID in ${FILE}: ${ID}")
    endif()
    list(APPEND SEEN "${ID}")
  endforeach()
  foreach(NEEDLE "/templates/management_window.rml" "<template src=\"management-window\">" "management6a.rcss" "l-m6a-root is-hidden" "_loading" "_empty" "_error" "_close" "_locate")
    string(FIND "${RML}" "${NEEDLE}" POS)
    if(POS EQUAL -1)
      message(FATAL_ERROR "Missing management 6A RML contract ${NEEDLE} in ${FILE}")
    endif()
  endforeach()
endforeach()
file(READ "${ROOT}/content/rmlui/windows/workshop_manager.rml" WORKSHOP_RML)
file(READ "${ROOT}/content/rmlui/panels/agriculture_manager.rml" AGRICULTURE_RML)
foreach(NEEDLE "l-agriculture-body" "l-stockpile-rail" "agriculture_view_overview" "agriculture_view_products" "agriculture_view_settings" "agriculture_view_work" "agriculture_overview_pane" "agriculture_products_pane" "agriculture_settings_pane" "agriculture_work_pane" "agriculture_plots" "agriculture_tilled" "agriculture_planted" "agriculture_ready" "agriculture_product_seeds" "agriculture_product_items" "agriculture_product_plants" "agriculture_name" "agriculture_priority" "agriculture_toggle_suspended" "agriculture_toggle_harvest" "agriculture_toggle_pick" "agriculture_toggle_pasture_harvest")
  string(FIND "${AGRICULTURE_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Farm sidebar or legacy agriculture data/action missing: ${NEEDLE}")
  endif()
endforeach()
foreach(SCREEN IN ITEMS WORKSHOP_RML AGRICULTURE_RML)
  foreach(NEEDLE "_refresh" "_search" "_sort" "_page_previous" "_page_next")
    string(FIND "${${SCREEN}}" "${NEEDLE}" POS)
    if(POS EQUAL -1)
      message(FATAL_ERROR "Missing paged management contract ${NEEDLE}")
    endif()
  endforeach()
endforeach()
foreach(NEEDLE "workshop_trade_confirmation" "workshop_trade_confirm" "workshop_trade_cancel")
  string(FIND "${ALL_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing blocking trade confirmation element: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "workshop_product_selection" "c-workshop-editor" "workshop_queue_once" "workshop_add_order" "workshop_job_selection")
  string(FIND "${WORKSHOP_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing placed-workshop order editor contract: ${NEEDLE}")
  endif()
endforeach()
file(READ "${ROOT}/content/rmlui/windows/stockpile_manager.rml" STOCKPILE_RML)
foreach(NEEDLE "stockpile_filters" "stockpile_rows" "stockpile_filter_count" "stockpile_content_count" "stockpile_allow_bulk" "stockpile_block_bulk" "stockpile_template_name" "stockpile_template_toggle" "stockpile_template_save" "stockpile_template_options" "role=\"combobox\"" "role=\"listbox\"" "stockpile_template_confirmation" "role=\"alertdialog\"" "aria-modal=\"true\"" "stockpile_template_overwrite_confirm" "stockpile_template_overwrite_cancel" "stockpile_filter_column_head" "c-stockpile-filter-header" "c-stockpile-content-header" "stockpile_content_filter_category" "stockpile_content_filter_group" "stockpile_content_filter_item" "stockpile_content_filter_material" "stockpile_content_filter_stock" "stockpile_content_filter_total" "stockpile_allow_filter_category" "stockpile_allow_filter_group" "stockpile_allow_filter_item" "stockpile_allow_filter_material" "stockpile_allow_filter_status" "stockpile_content_sort_category" "stockpile_allow_sort_status" ">Item<" ">In Stock<" ">Total<" "stockpile_view_contents" ">Stock</button>" "stockpile_view_allow" "stockpile_view_settings" "stockpile_locate" ">Center on map</button>" "stockpile_settings_pane" "management.stockpile.name_priority" "l-stockpile-hauling-options" "l-stockpile-status-settings" "stockpile_toggle_suspended" "stockpile_toggle_pull" "stockpile_toggle_allow_pull" "stockpile_priority_up" "stockpile_priority_down" "type=\"number\"" "step=\"1\"" "stockpile_tooltip" "role=\"tooltip\"" "c-stockpile-table-header" "c-m6a-filter-list" "c-m6a-content-list")
  string(FIND "${STOCKPILE_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing truthful Stockpile content/unsupported-surface contract: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "class=\"c-window l-m6a-panel l-stockpile-panel\"" "class=\"c-window__body l-stockpile-body\"" "class=\"l-stockpile-rail\"" "l-stockpile-rail-heading" "l-stockpile-rail-button" "role=\"tablist\"" "role=\"tab\"" "role=\"tabpanel\"" "aria-orientation=\"vertical\"" "aria-selected=\"true\"" "c-list c-scroll-region")
  string(FIND "${STOCKPILE_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile property-sheet tab contract missing: ${NEEDLE}")
  endif()
endforeach()

foreach(FORBIDDEN "stockpile_refresh" "stockpile_copy" "stockpile_paste" "stockpile_limit" "stockpile_limits" "stockpile_page_previous" "stockpile_page_next" "stockpile_search" "stockpile_view_split" "view_split" "stockpile_action_settings" "stockpile_hauling_toggle" "stockpile_hauling_options")
  string(FIND "${STOCKPILE_RML}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Fabricated unsupported Stockpile control remains: ${FORBIDDEN}")
  endif()
endforeach()
file(READ "${ROOT}/content/rmlui/screens/management6a.rcss" RCSS)
string(FIND "${RCSS}" "#agriculture_workbench scrollbarvertical { width: 16dp" FARM_SCROLLBAR_WIDTH)
if(FARM_SCROLLBAR_WIDTH EQUAL -1)
  message(FATAL_ERROR "Farm scrollbars must leave crop rows available to pointer input")
endif()
foreach(NEEDLE "Inventory-aligned Storage Management workbench" "#stockpile_workbench" ".l-stockpile-body" ".l-stockpile-rail" "flex: 0 0 112dp" ".l-stockpile-rail-heading" ".l-stockpile-rail-button.is-selected" ".l-stockpile-main" "background-color: #c0c0c0" "background-color: #ffffff" "background-color: #000080" "border-top-color: #404040" "scrollbarvertical sliderarrowdec" "decorator: text(\"^\")" ".c-m6a-content-icon" ".c-m6a-content-icon-image" "min-height: 48dp" "flex: 0 0 40dp")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile Inventory-aligned Win98 style missing: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "stockpile_content_filter_category_toggle" "stockpile_content_filter_material_options" "stockpile_allow_filter_category_toggle" "stockpile_allow_filter_status_options" "c-excel-filter-combo" "c-excel-filter-combo__toggle" "c-excel-filter-combo__options")
  string(FIND "${STOCKPILE_RML}${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile editable filter combo contract missing: ${NEEDLE}")
  endif()
endforeach()
string(FIND "${RCSS}" "border-right-color: #404040; border-bottom-color: #404040" STOCKPILE_COMBO_COMPLETE_FRAME)
if(STOCKPILE_COMBO_COMPLETE_FRAME EQUAL -1)
  message(FATAL_ERROR "Stockpile combo popup must retain a visible right and bottom frame")
endif()
foreach(NEEDLE "c-stockpile-filter-toolbar" "c-excel-header" "c-excel-header__sort" "c-excel-header__filter")
  string(FIND "${STOCKPILE_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile single-row search/bulk toolbar contract missing: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "c-stockpile-bulk-button" "c-button l-stockpile-rail-button c-stockpile-bulk-button")
  string(FIND "${STOCKPILE_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile bulk buttons must use the themed rail-button treatment: ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "management.stockpile.rule_header" "c-m6a-content-rule" "stockpile_filter_selection" "stockpile_content_selection" "stockpile_template_list" "stockpile_template_button" "stockpile_nothing_allowed" "id=\"stockpile_status\"")
  string(FIND "${STOCKPILE_RML}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Stockpile Contents must not expose the obsolete Rule column: ${FORBIDDEN}")
  endif()
endforeach()
string(FIND "${STOCKPILE_RML}" "class=\"c-stockpile-bulk\"" LEGACY_STOCKPILE_BULK_POS)
if(NOT LEGACY_STOCKPILE_BULK_POS EQUAL -1)
  message(FATAL_ERROR "Stockpile search and bulk actions must share one toolbar row")
endif()
string(FIND "${STOCKPILE_RML}" "id=\"stockpile_view_contents\"" CONTENTS_VIEW_POS)
string(FIND "${STOCKPILE_RML}" "id=\"stockpile_view_allow\"" ALLOW_VIEW_POS)
string(FIND "${STOCKPILE_RML}" "id=\"stockpile_view_settings\"" SETTINGS_VIEW_POS)
string(FIND "${STOCKPILE_RML}" "id=\"stockpile_settings_pane\"" SETTINGS_PANE_POS)
string(FIND "${STOCKPILE_RML}" "id=\"stockpile_toggle_suspended\"" SUSPEND_CONTROL_POS)
if(CONTENTS_VIEW_POS EQUAL -1 OR ALLOW_VIEW_POS EQUAL -1 OR SETTINGS_VIEW_POS EQUAL -1 OR NOT CONTENTS_VIEW_POS LESS ALLOW_VIEW_POS OR NOT ALLOW_VIEW_POS LESS SETTINGS_VIEW_POS)
  message(FATAL_ERROR "Stockpile views must be ordered Stock, Allow list, Settings")
endif()
if(SETTINGS_PANE_POS EQUAL -1 OR SUSPEND_CONTROL_POS EQUAL -1 OR NOT SETTINGS_PANE_POS LESS SUSPEND_CONTROL_POS)
  message(FATAL_ERROR "Stockpile suspension must live inside the Settings pane")
endif()
foreach(NEEDLE ".c-workshop-editor" ".c-workshop-mode-button" ".c-workshop-material-button" ".is-shortage")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing placed-workshop Windows 98 editor style: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE ".c-m6a-disclosure-button[aria-expanded=\"true\"]" "background-color: #008000" "background-color: #a04040" "image-rendering: pixelated" ".c-m6a-filter-row.is-selected { color: #000000; background-color: #d4d0c8")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile disclosure/icon/non-blue selection style missing: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE ".c-stockpile-template-confirmation { z-index: 200; }" ".c-m6a-blocker { position: absolute" "pointer-events: auto")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile overwrite confirmation must stack above and intercept the template toolbar: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "pointer-events: none" "pointer-events: auto" "overflow-y: auto" "overflow-x: auto" "display: flex" "flex-direction: column" "height: 100%" "min-height: 0" ".c-m6a-filter-icon" ".c-m6a-filter-icon-image" ".is-selected" ".is-error" ".c-m6a-blocker" ".c-m6a-filter-depth-0" ".c-m6a-filter-depth-3" ".c-m6a-section-heading" ".c-m6a-content-material" "min-width: 100%" "height: 34dp" "text-overflow: clip" "white-space: nowrap" "word-break: normal")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing management 6A input/responsive/state style: ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "estimated time" "items per hour" "hauling backlog" "editable limit")
  string(TOLOWER "${ALL_RML}" LOWER_RML)
  string(FIND "${LOWER_RML}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Fabricated unsupported management datum: ${FORBIDDEN}")
  endif()
endforeach()
string(FIND "${RCSS}" "@media" UNSUPPORTED_MEDIA)
if(NOT UNSUPPORTED_MEDIA EQUAL -1)
  message(FATAL_ERROR "Unsupported RmlUi @media rule remains in management 6A styles")
endif()
foreach(NEEDLE "workshop_product_selection" "c-workshop-editor" "workshop_queue_once" "workshop_add_order" "workshop_job_selection")
  string(FIND "${WORKSHOP_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing placed-workshop order editor contract: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE ".c-workshop-editor" ".c-workshop-mode-button" ".c-workshop-material-button" ".is-shortage")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing placed-workshop Windows 98 editor style: ${NEEDLE}")
  endif()
endforeach()
message(STATUS "Management 6A RML IDs, state surfaces, keyboard buttons, and map ownership passed")

foreach(REMOVED stockpile_filter_pager stockpile_filter_previous stockpile_filter_next)
  if(STOCKPILE_RML MATCHES "id=\"${REMOVED}\"")
    message(FATAL_ERROR "Allow list must scroll without pagination: ${REMOVED}")
  endif()
endforeach()
