set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
set(ALL_RML)
foreach(FILE IN ITEMS content/rmlui/windows/workshop_manager.rml content/rmlui/windows/stockpile_manager.rml content/rmlui/panels/agriculture_manager.rml)
  file(READ "${ROOT}/${FILE}" RML)
  string(APPEND ALL_RML "${RML}")
  string(REGEX MATCHALL "id=\"[^\"]+\"" IDS "${RML}")
  set(SEEN)
  foreach(ID IN LISTS IDS)
    list(FIND SEEN "${ID}" INDEX)
    if(NOT INDEX EQUAL -1)
      message(FATAL_ERROR "Duplicate RML ID in ${FILE}: ${ID}")
    endif()
    list(APPEND SEEN "${ID}")
  endforeach()
  foreach(NEEDLE "../styles/base.rcss" "../styles/components.rcss" "management6a.rcss" "l-m6a-root is-hidden" "_loading" "_empty" "_error" "_close" "_locate" "_refresh" "_search" "_sort" "_page_previous" "_page_next")
    string(FIND "${RML}" "${NEEDLE}" POS)
    if(POS EQUAL -1)
      message(FATAL_ERROR "Missing management 6A RML contract ${NEEDLE} in ${FILE}")
    endif()
  endforeach()
endforeach()
foreach(NEEDLE "workshop_trade_confirmation" "workshop_trade_confirm" "workshop_trade_cancel")
  string(FIND "${ALL_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing blocking trade confirmation element: ${NEEDLE}")
  endif()
endforeach()
file(READ "${ROOT}/content/rmlui/windows/stockpile_manager.rml" STOCKPILE_RML)
foreach(NEEDLE "stockpile_filters" "stockpile_rows" "stockpile_next_content" "unsupported_projections_and_per_item_controls_ar")
  string(FIND "${STOCKPILE_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing truthful Stockpile content/unsupported-surface contract: ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "stockpile_copy" "stockpile_paste" "stockpile_limit" "stockpile_limits")
  string(FIND "${STOCKPILE_RML}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Fabricated unsupported Stockpile control remains: ${FORBIDDEN}")
  endif()
endforeach()
file(READ "${ROOT}/content/rmlui/screens/management6a.rcss" RCSS)
foreach(NEEDLE "pointer-events: none" "pointer-events: auto" "overflow-y: auto" ".is-selected" ".is-error" ".c-m6a-blocker" ".c-m6a-filter-depth-0" ".c-m6a-filter-depth-3")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing management 6A input/responsive/state style: ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "estimated time" "items per hour" "hauling backlog" "editable limit")
  string(TOLOWER "${ALL_RML}" LOWER_RML)
  string(FIND "${LOWER_RML}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Fabricated unsupported management datum: ${FORBIDDEN}")
  endif()
endforeach()
string(FIND "${RCSS}" "@media" UNSUPPORTED_MEDIA)
if(NOT UNSUPPORTED_MEDIA EQUAL -1)
  message(FATAL_ERROR "Unsupported RmlUi @media rule remains in management 6A styles")
endif()
message(STATUS "Management 6A RML IDs, state surfaces, keyboard buttons, and map ownership passed")
