set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/src/gui/ui/controllers/management6a/Management6AQtCommandPort.cpp" PORT)
file(READ "${ROOT}/src/gui/ui/controllers/management6a/Management6AIntegration.cpp" INTEGRATION)
file(READ "${ROOT}/src/gui/ui/screens/management6a/Management6ARmlBinding.cpp" BINDING)
file(READ "${ROOT}/src/gui/ui/screens/management6a/Management6AController.cpp" CONTROLLER)
file(READ "${ROOT}/src/gui/mainwindow.cpp" MAINWINDOW)
file(READ "${ROOT}/src/main.cpp" MAIN)
file(READ "${ROOT}/src/gui/ui/actions/UiActions.h" ACTIONS)
file(READ "${ROOT}/src/gui/aggregatorstockpile.cpp" STOCKPILE_AGGREGATOR)
foreach(NEEDLE workshop_order_mode data-material-index workshop_job_apply workshop_job_top workshop_job_bottom workshop_order_count workshop_job_count queueSelectedCraftOrder setWorkshopOrderMaterial "MoveDirection::Front" "MoveDirection::Back" applyWorkshopDraft editWorkshopOptions)
  string(FIND "${BINDING}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing placed-workshop order or queue control wiring: ${NEEDLE}")
  endif()
endforeach()
file(READ "${ROOT}/src/gui/ui/controllers/management6a/Management6AQtDataAdapter.cpp" ADAPTER)
foreach(NEEDLE onCraftItem onCraftJobParams onCraftJobCommand onReviewedTrade onSetTradeOffer onSetActive onSetBasicOptions onSelectProduct onSetHarvestOptions onSetGroveOptions onSetMaxMale onSetMaxFemale onSetButchering onSetFoodItemChecked onCenterCamera Qt::QueuedConnection)
  string(FIND "${PORT}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing authoritative management 6A command route: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "DispatchOrigin::DestructiveConfirmation" "action.id.value == \"trade.execute\"" "ModalKind::DestructiveConfirmation")
  string(FIND "${PORT}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing scoped trade confirmation validation evidence: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE signalUpdateInfo signalUpdateContent signalUpdateCraftList signalTradeSnapshot signalWorkshopRejected signalUpdateFarm signalUpdatePasture signalUpdateGrove signalGlobalPlantInfo signalGlobalAnimalInfo signalGlobalTreeInfo WorldEpoch Revision)
  string(FIND "${INTEGRATION}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing management 6A queued integration seam: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE RemoveEventListener UnloadDocument "windows/workshop_manager.rml" "windows/stockpile_manager.rml" "panels/agriculture_manager.rml" GetFocusElement pageSize_ workshopPage_ agriculturePage_ renderStockpileFilterViewport stockpileFilterMarkup_ "\"input\"" "\"change\"" workshop_linked_stockpiles data-link-id editWorkshopOptions workshop_trade_count workshop_trade_set workshopPriorityEditor_ applyWorkshopDraft stockpile_view_settings stockpile_settings_pane stockpile_priority_up stockpile_priority_down "StockpilePane::Settings" stockpilePriorityEditor_ dataElement data-depth data-rule aria-selected keydown KI_UP KI_DOWN KI_HOME KI_END KI_RETURN KI_SPACE moveStockpileFilterSelection Focus filter_ filterOptionMarkup setFormValueForProbe setStockpileSearchForProbe activateFirstStockpileFilterForProbe dispatchStockpileFilterKeyForProbe stockpileFilterRowId setStockpileAllowSort allowSortDirection StockpilePane StockpileSortKey stockpile_template_name stockpile_template_toggle stockpile_template_save stockpile_template_options setStockpileTemplateName toggleStockpileTemplateMenu selectStockpileTemplate saveStockpileTemplate confirmStockpileTemplateOverwrite cancelStockpileTemplateOverwrite templateOverwriteConfirmationRequired foldedLabel)
  string(FIND "${BINDING}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing management 6A binding/lifecycle/input evidence: ${NEEDLE}")
  endif()
endforeach()
string(FIND "${INTEGRATION}" "stockpileController_->setStockpilePane(StockpilePane::Contents)" STOCKPILE_OPEN_CONTENTS_POS)
if(STOCKPILE_OPEN_CONTENTS_POS EQUAL -1)
  message(FATAL_ERROR "Opening a stockpile must reset the main workbench to Contents")
endif()
string(REGEX MATCHALL "m_inspectorController->showStockpile" INSPECTOR_STOCKPILE_ROUTES "${MAINWINDOW}")
list(LENGTH INSPECTOR_STOCKPILE_ROUTES INSPECTOR_STOCKPILE_ROUTE_COUNT)
if(NOT INSPECTOR_STOCKPILE_ROUTE_COUNT EQUAL 3)
  message(FATAL_ERROR "Stockpile fixture and stable-target inspector refresh must both exist")
endif()
foreach(NEEDLE showManagementStockpileFixture stockpile_manager INGNOMIA_AUTOMATE_STOCKPILE_SEARCH_FIXTURE INGNOMIA_AUTOMATE_STOCKPILE_TEMPLATE_FIXTURE ui_fixture_stockpile_search "\"axe\", \"ax\", \"a\", \"\", \"wood\", \"\"" "filter_RawWood.tga" "filter_RawStone.tga" "filter_Apple.tga")
  string(FIND "${MAINWINDOW}${MAIN}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing populated main Stockpile runtime fixture contract: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "stockpileBaseSize( 720, 720 )" "UiWindow.stockpile.flat_columns1" "stockpileMinimumSize( 640, 420 )" "expandedTo( minimumSize )" "setResizeMinimumSize( minimumSize )")
  string(FIND "${MAINWINDOW}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile detached-window size must match Inventory & Resources: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "alphabetized( filter.categories() )" "alphabetized( filter.groups( category ) )" "alphabetized( filter.items( category, group ) )" "alphabetized( filter.materials( category, group, item ) )")
  string(FIND "${ADAPTER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Stockpile hierarchy must remain alphabetical at every level: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE SetStockpileFiltersPayload stockpile.set_filters onSetActiveBatch)
  string(FIND "${CONTROLLER}${ACTIONS}${PORT}${STOCKPILE_AGGREGATOR}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing atomic Stockpile bulk-action route: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE StockpileTemplatePayload stockpile.save_template stockpile.apply_template onSaveFilterTemplate onApplyFilterTemplate "stockpile-filter-templates.json" "stockpile->filter().serialize()" "DispatchOrigin::DestructiveConfirmation")
  string(FIND "${CONTROLLER}${ACTIONS}${PORT}${STOCKPILE_AGGREGATOR}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing persistent Stockpile allow-list template route: ${NEEDLE}")
  endif()
endforeach()
string(REGEX MATCHALL "bind\\( \"stockpile_filters\", \"click\"" STOCKPILE_FILTER_CLICK_BINDINGS "${BINDING}")
list(LENGTH STOCKPILE_FILTER_CLICK_BINDINGS STOCKPILE_FILTER_CLICK_BINDING_COUNT)
if(NOT STOCKPILE_FILTER_CLICK_BINDING_COUNT EQUAL 1)
  message(FATAL_ERROR "Stockpile filter list must have exactly one click handler; duplicate handlers toggle disclosures twice")
endif()
file(READ "${ROOT}/src/gui/ui/controllers/management6a/Management6AQtDataAdapter.cpp" ADAPTER)
foreach(NEEDLE "if ( value.count > 0 )" "out.contents.push_back" "filterRow.icon" "AggregatorInventory::inventoryIcon" "StockpileFilterRow::Icon" "displayFilterLabel")
  string(FIND "${ADAPTER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing positive-count Stockpile current-contents projection guard: ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "QPointer<Game>" "QPixmap" "Game*" "QObject*")
  string(FIND "${ADAPTER}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Pointer/resource leaked into management 6A presentation adapter: ${FORBIDDEN}")
  endif()
endforeach()
message(STATUS "Management 6A pointer-free DTO copy, queued ports, and teardown evidence passed")
