/* SPDX-License-Identifier: AGPL-3.0-or-later */
#pragma once

#include "../../localization/UiText.h"

namespace ingnomia::ui::management6b
{
inline localization::UiText management6BText()
{
	using Entries = std::map<std::string, std::string, std::less<>>;
	return localization::UiText( Entries {
		{ "common.search", "Search" },
		{ "common.cancel", "Cancel" },
		{ "management.population.title", "Population & Work" },
		{ "management.population.citizens", "Citizens" },
		{ "management.population.professions", "Professions" },
		{ "management.population.citizens_help", "Review citizens, assignments, activity, needs, and equipment." },
		{ "management.population.skills_help", "Compare one skill across all citizens and change who may use it." },
		{ "management.population.professions_help", "Create professions and edit their ordered skills." },
		{ "management.population.schedules_help", "Set hourly duties for one cell, a citizen, or everyone." },
		{ "management.population.schedules", "Schedules" },
		{ "management.population.search.placeholder", "Search citizens" },
		{ "management.population.views_help", "Open Population views." },
		{ "management.population.sort_name", "Name" },
		{ "management.population.sort_profession", "Profession" },
		{ "management.population.keyboard_hint", "Up/Down select | Enter opens details" },
		{ "management.population.citizen_roster", "Citizen roster" },
		{ "management.population.profession_roster", "Profession roster" },
		{ "management.population.profession_note", "Choose a citizen to review or change their assignment." },
		{ "management.population.schedule_title", "24-hour duty board" },
		{ "management.population.schedule_note", "Choose a citizen and hour, then choose an activity and scope. Arrow keys move; Enter or Space changes the focused cell." },
		{ "management.population.new_profession", "New profession" },
		{ "management.population.schedule_none", "[ ] None" },
		{ "management.population.schedule_eat", "[ ] Eat" },
		{ "management.population.schedule_sleep", "[ ] Sleep" },
		{ "management.population.schedule_train", "[ ] Train" },
		{ "management.population.schedule_keyboard_hint", "Home/End hour | Page Up/Down citizen" },
		{ "management.population.back", "Back to citizens" },
		{ "management.population.skills", "Skills" },
		{ "management.navigation.views", "Views" },
		{ "management.population.no_skill_catalog", "No skills are available." },
		{ "management.population.choose_skill", "Choose a skill" },
		{ "management.population.choose_skill_help", "Select a skill to compare citizens." },
		{ "management.population.skill_level_xp", "Level {level} · XP {xp}" },
		{ "management.population.skill_toggle_help", "Toggle this citizen's use of the selected skill." },
		{ "management.population.no_skill_citizens", "No citizens have this skill." },
		{ "management.population.choose_profession", "Choose a profession" },
		{ "management.population.choose_profession_help", "Select a profession to edit its skills." },
		{ "management.population.profession_editor_help", "Choose and order the skills this profession uses." },
		{ "management.population.gnomad_protected", "Gnomad is the base profession and cannot be edited or deleted." },
		{ "management.population.no_profession_skills", "No skills are assigned to this profession." },
		{ "management.population.no_available_skills", "All available skills are assigned." },
		{ "management.population.choose_cell", "Choose a citizen and hour" },
		{ "management.population.selected_cell", "{citizen}, hour {hour}" },
		{ "management.population.error_name_required", "Enter a profession name." },
		{ "management.population.error_duplicate_name", "A profession with that name already exists." },
		{ "management.population.views_label", "Population views" },
		{ "management.population.enable_skill_all", "Enable for all citizens" },
		{ "management.population.disable_skill_all", "Disable for all citizens" },
		{ "management.population.enable_skill_all_help", "Enable this skill for every citizen." },
		{ "management.population.disable_skill_all_help", "Disable this skill for every citizen." },
		{ "management.population.new_profession_name", "New profession name" },
		{ "management.population.create", "Create" },
		{ "management.population.name", "Name" },
		{ "management.population.profession_skills", "Profession skills" },
		{ "management.population.available_skills", "Available skills" },
		{ "management.population.move_up", "Move up" },
		{ "management.population.move_down", "Move down" },
		{ "management.population.remove_skill", "Remove" },
		{ "management.population.add_skill", "Add skill" },
		{ "management.population.save_profession", "Save profession" },
		{ "management.population.delete_profession", "Delete profession" },
		{ "management.population.set_cell", "Set cell" },
		{ "management.population.set_day", "Set citizen's day" },
		{ "management.population.set_hour_all", "Set hour for all" },
		{ "management.population.set_cell_help", "Only this citizen and hour." },
		{ "management.population.set_day_help", "All 24 hours for this citizen." },
		{ "management.population.set_hour_all_help", "This hour for every citizen." },
		{ "management.population.delete_confirm_title", "Delete profession?" },
		{ "management.population.delete", "Delete" },
		{ "management.population.active_hint", "[x] active" },
		{ "management.population.enable_person_skills", "Enable all skills" },
		{ "management.population.disable_person_skills", "Disable all skills" },
		{ "management.population.enable_person_skills_help", "Enable every skill for this citizen." },
		{ "management.population.disable_person_skills_help", "Disable every skill for this citizen." },
		{ "management.population.attributes", "Attributes" },
		{ "management.population.needs", "Needs" },
		{ "management.population.equipment", "Equipment" },
		{ "management.population.no_citizens", "No citizens match the loaded rows." },
		{ "management.population.no_professions", "No professions are loaded." },
		{ "management.population.no_schedules", "No schedules are loaded." },
		{ "management.population.no_profession", "No profession" },
		{ "management.population.profession_skill_count", "{count} assigned skills" },
		{ "management.population.creature_profession", "Profession: {profession}" },
		{ "management.population.activity", "Activity: {activity}" },
		{ "management.population.activity_unknown", "No current activity reported." },
		{ "management.population.attribute_summary", "STR {strength} | DEX {dexterity} | CON {constitution} | INT {intelligence} | WIS {wisdom} | CHA {charisma}" },
		{ "management.population.needs_summary", "Hunger {hunger} | Thirst {thirst} | Sleep {sleep} | Happiness {happiness}" },
		{ "management.population.no_equipment", "No equipped items are reported." },
		{ "management.population.no_skills", "No skills are reported." },
		{ "management.population.no_profession_choices", "No profession choices are reported." },
		{ "management.population.skill_state", "{skill} | level {level} | {state}" },
		{ "management.population.revision", "Population loaded" },
		{ "management.population.page", "Rows {first}-{last} of {total}" },
		{ "management.inventory.title", "Inventory & Resources" },
		{ "management.inventory.tab_all", "All" },
		{ "management.inventory.search.placeholder", "Filter inventory by name" },
		{ "management.inventory.filter_owned", "Items we have" },
		{ "management.inventory.filters", "Filters" },
		{ "management.inventory.categories", "Categories" },
		{ "management.inventory.sort_name", "Name" },
		{ "management.inventory.sort_stock", "In Stock" },
		{ "management.inventory.sort_total", "Total" },
		{ "management.inventory.columns", "Resource tree | Total | Jobs | Stock | Equipped | Built | Loose | Value" },
		{ "management.inventory.column.resource", "Item" },
		{ "management.inventory.column.total", "Total" },
		{ "management.inventory.column.jobs", "Jobs" },
		{ "management.inventory.column.stock", "In Stock" },
		{ "management.inventory.column.equipped", "Equipped" },
		{ "management.inventory.column.built", "Built" },
		{ "management.inventory.column.loose", "Loose" },
		{ "management.inventory.column.value", "Value" },
		{ "management.inventory.toggle_watch", "[ ] Watch selected" },
		{ "management.inventory.watching_selected", "[x] Watching selected" },
		{ "management.inventory.no_rows", "No inventory rows match the loaded tree." },
		{ "management.inventory.row_summary", "total {total} | jobs {jobs} | stock {stock} | equipped {equipped} | built {built} | loose {loose} | value {value}" },
		{ "management.inventory.watched", "[x]" },
		{ "management.inventory.revision", "Inventory loaded" },
		{ "management.inventory.page", "Rows {first}-{last} of {total}" },
		{ "management.inventory.history", "History" },
		{ "management.inventory.detail_back", "Back to inventory" },
		{ "management.inventory.detail_previous", "Back to previous item" },
		{ "management.inventory.made_by", "How to make it" },
		{ "management.inventory.used_in", "What it makes" },
		{ "management.inventory.stored_at", "Stored in stockpiles" },
		{ "management.inventory.detail_total", "Total {count}" },
		{ "management.inventory.detail_stock", "In stock {count}" },
		{ "management.inventory.detail_loose", "Loose {count}" },
		{ "management.inventory.detail_equipped", "Equipped {count}" },
		{ "management.inventory.detail_jobs", "In jobs {count}" },
		{ "management.inventory.recipe_makes", "Makes {count}" },
		{ "management.inventory.recipe_at", "at {workshop}" },
		{ "management.inventory.recipe_none", "No workshop recipe recorded." },
		{ "management.inventory.used_in_none", "No craftable items use this item." },
		{ "management.inventory.category_other", "Other items" },
		{ "management.inventory.locations_none", "None of this item is currently stored in a stockpile." },
		{ "management.inventory.history_loading", "Loading history..." },
		{ "management.inventory.history_empty", "No recorded history for this item." },
		{ "management.inventory.history_point", "Day {day}: total {total}, +{created}, -{destroyed}" },
		{ "management.inventory.history_day", "Day {day}" },
		{ "common.close", "Close" }, { "common.refresh", "Refresh" },
		{ "common.previous_rows", "Previous rows" }, { "common.next_rows", "Next rows" },
		{ "status.updating", "Updating..." },
		{ "status.refreshing", "Refreshing..." },
		{ "common.on", "on" }, { "common.off", "off" }
	} );
}
} // namespace ingnomia::ui::management6b
