/* SPDX-License-Identifier: AGPL-3.0-or-later */
#pragma once

#include "../../localization/UiText.h"

namespace ingnomia::ui::management6b
{
inline localization::UiText management6BText()
{
	using Entries = std::map<std::string, std::string, std::less<>>;
	return localization::UiText( Entries {
		{ "common.search", "Search" },
		{ "management.population.title", "Population & Work" },
		{ "management.population.citizens", "Citizens" },
		{ "management.population.professions", "Professions & Skills" },
		{ "management.population.schedules", "Schedules" },
		{ "management.population.search.placeholder", "Search citizens or professions" },
		{ "management.population.sort_name", "Name" },
		{ "management.population.sort_profession", "Profession" },
		{ "management.population.keyboard_hint", "Up/Down select | Enter opens details" },
		{ "management.population.citizen_roster", "Citizen roster" },
		{ "management.population.profession_roster", "Profession roster" },
		{ "management.population.profession_note", "Choose a citizen to review or change their assignment." },
		{ "management.population.schedule_title", "24-hour duty board" },
		{ "management.population.schedule_note", "Arrow keys move; Enter or Space changes the focused cell." },
		{ "management.population.schedule_none", "[ ] None" },
		{ "management.population.schedule_eat", "[ ] Eat" },
		{ "management.population.schedule_sleep", "[ ] Sleep" },
		{ "management.population.schedule_train", "[ ] Train" },
		{ "management.population.schedule_keyboard_hint", "Home/End hour | Page Up/Down citizen" },
		{ "management.population.back", "Back to citizens" },
		{ "management.population.skills", "Skills" },
		{ "management.population.attributes", "Attributes" },
		{ "management.population.needs", "Needs" },
		{ "management.population.equipment", "Equipment" },
		{ "management.population.no_citizens", "No citizens match the loaded rows." },
		{ "management.population.no_professions", "No professions are loaded." },
		{ "management.population.no_schedules", "No schedules are loaded." },
		{ "management.population.no_profession", "No profession" },
		{ "management.population.profession_skill_count", "{count} assigned skills" },
		{ "management.population.creature_profession", "Profession: {profession}" },
		{ "management.population.activity", "Activity: {activity}" },
		{ "management.population.activity_unknown", "No current activity reported." },
		{ "management.population.attribute_summary", "STR {strength} | DEX {dexterity} | CON {constitution} | INT {intelligence} | WIS {wisdom} | CHA {charisma}" },
		{ "management.population.needs_summary", "Hunger {hunger} | Thirst {thirst} | Sleep {sleep} | Happiness {happiness}" },
		{ "management.population.no_equipment", "No equipped items are reported." },
		{ "management.population.no_skills", "No skills are reported." },
		{ "management.population.no_profession_choices", "No profession choices are reported." },
		{ "management.population.skill_state", "{skill} | level {level} | {state}" },
		{ "management.population.revision", "Population loaded" },
		{ "management.population.page", "Rows {first}-{last} of {total}" },
		{ "management.inventory.title", "Inventory & Resources" },
		{ "management.inventory.tab_all", "All" },
		{ "management.inventory.search.placeholder", "Filter inventory by name" },
		{ "management.inventory.filter_owned", "Items we have" },
		{ "management.inventory.filters", "Filters" },
		{ "management.inventory.categories", "Categories" },
		{ "management.inventory.sort_name", "Name" },
		{ "management.inventory.sort_stock", "In Stock" },
		{ "management.inventory.sort_total", "Total" },
		{ "management.inventory.columns", "Resource tree | Total | Jobs | Stock | Equipped | Built | Loose | Value" },
		{ "management.inventory.column.resource", "Item" },
		{ "management.inventory.column.total", "Total" },
		{ "management.inventory.column.jobs", "Jobs" },
		{ "management.inventory.column.stock", "In Stock" },
		{ "management.inventory.column.equipped", "Equipped" },
		{ "management.inventory.column.built", "Built" },
		{ "management.inventory.column.loose", "Loose" },
		{ "management.inventory.column.value", "Value" },
		{ "management.inventory.toggle_watch", "[ ] Watch selected" },
		{ "management.inventory.watching_selected", "[x] Watching selected" },
		{ "management.inventory.no_rows", "No inventory rows match the loaded tree." },
		{ "management.inventory.row_summary", "total {total} | jobs {jobs} | stock {stock} | equipped {equipped} | built {built} | loose {loose} | value {value}" },
		{ "management.inventory.watched", "[x]" },
		{ "management.inventory.revision", "Inventory loaded" },
		{ "management.inventory.page", "Rows {first}-{last} of {total}" },
		{ "management.inventory.history", "History" },
		{ "management.inventory.history_loading", "Loading history..." },
		{ "management.inventory.history_empty", "No recorded history for this item." },
		{ "management.inventory.history_point", "Day {day}: total {total}, +{created}, -{destroyed}" },
		{ "common.close", "Close" }, { "common.refresh", "Refresh" },
		{ "common.previous_rows", "Previous rows" }, { "common.next_rows", "Next rows" },
		{ "status.updating", "Updating..." },
		{ "status.refreshing", "Refreshing..." },
		{ "common.on", "on" }, { "common.off", "off" }
	} );
}
} // namespace ingnomia::ui::management6b
