cmake_minimum_required(VERSION 3.16)

get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${ROOT}/src/gui/ui/screens/shell/ShellRmlBinding.cpp" BINDING)
file(READ "${ROOT}/src/gui/ui/screens/shell/ShellController.cpp" CONTROLLER)
file(READ "${ROOT}/src/gui/ui/controllers/shell/ShellQtCommandPort.cpp" PORT)
file(READ "${ROOT}/src/gui/aggregatorsettings.cpp" SETTINGS)
file(READ "${ROOT}/src/gui/eventconnector.h" EVENT)
file(READ "${ROOT}/src/gui/ui/runtime/RmlUiHost.cpp" HOST)
file(READ "${ROOT}/src/gui/mainwindow.cpp" WINDOW)
file(READ "${ROOT}/CMakeLists.txt" ROOT_CMAKE)

function(require source pattern description)
    if(NOT "${${source}}" MATCHES "${pattern}")
        message(FATAL_ERROR "Missing shell integration contract: ${description}")
    endif()
endfunction()

require(BINDING "CreateDataModel\\( \"ui_shell\" \\)" "ui_shell data model")
require(BINDING "CreateDataModel\\( \"ui_settings\" \\)" "ui_settings data model")
require(BINDING "AddEventListener\\( Rml::EventId::Click" "C++ callback registration")
require(BINDING "GetParameter<float>" "slider changes read the RmlUi change-event value")
require(BINDING "GetParameter<bool>" "toggle changes read the RmlUi change-event checked state")
require(BINDING "NewGameTabCallback" "new-game tab callback type")
require(BINDING "bindNewGameTabCallback" "new-game tab callback registration")
require(BINDING "syncNewGameTabs" "new-game tab state synchronization")
require(BINDING "new-tab-world" "new-game world tab binding")
require(BINDING "UiRegistries::findRoute" "registered route resolution")
require(PORT "Qt::QueuedConnection" "queued Qt bridge")
require(PORT "onContinueLastGame" "continue adapter")
require(PORT "onStartNewGame" "new-game adapter")
require(PORT "onLoadGame" "load adapter")
require(PORT "onSaveGame" "save adapter")
require(EVENT "signalSaveGameFinished" "save completion signal")
require(PORT "onEndGame" "end-world adapter")
require(PORT "onSetPause" "pause adapter")
require(PORT "onSetFullScreen" "settings adapter")
string(REPLACE "\\n" " " SETTINGS_FLAT "${SETTINGS}")
foreach(setting_setter IN ITEMS "onSetUIScale" "onSetFullScreen" "onSetKeyboardSpeed" "onSetLightMin" "onSetToggleMouseWheel")
    if(NOT SETTINGS_FLAT MATCHES "${setting_setter}[^}]*onRequestSettings")
        message(FATAL_ERROR "Settings setter does not emit a fresh authoritative snapshot: ${setting_setter}")
    endif()
endforeach()
if(PORT MATCHES "Game[ \\t]*\\*")
    message(FATAL_ERROR "Shell Qt command port retains or exposes a Game pointer")
endif()
require(HOST "createShellBinding" "host binding ownership hook")
require(HOST "m_shellBinding->shutdown\\(\\).*UnloadAllDocuments" "binding teardown before context teardown")
require(WINDOW "m_shellController" "production MainWindow shell initialization")
require(WINDOW "signalUpdateSettings" "live settings snapshot hook")
require(WINDOW "signalKingdoms" "live kingdom metadata hook")
require(WINDOW "signalSaveGames" "live save metadata hook")
require(WINDOW "signalLoadError" "live save-list error hook")
require(WINDOW "signalSaveGameFinished" "live save completion hook")
require(WINDOW "ShellControl::TogglePause" "HUD pause button uses pause-only shell control")
require(CONTROLLER "ShellControl::OpenPauseMenu" "ESC can open the pause menu independently")
if(ROOT_CMAKE MATCHES "INGNOMIA_ENABLE_RMLUI_MAINWINDOW")
    message(FATAL_ERROR "Root build must expose only the production RmlUi MainWindow path")
endif()
require(WINDOW "initializeRmlUi\\(" "sole RmlUi MainWindow path")

message(STATUS "Wave 3 shell host/Qt integration contract passed")
