set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/src/gui/mainwindow.cpp" MAIN)
file(READ "${ROOT}/src/gui/mainwindowrenderer.cpp" RENDERER)
file(READ "${ROOT}/src/gui/mainwindowrenderer.h" RENDERER_HEADER)
file(READ "${ROOT}/src/gui/aggregatorrenderer.cpp" AGGREGATOR)
file(READ "${ROOT}/src/gui/aggregatorrenderer.h" AGGREGATOR_HEADER)
file(READ "${ROOT}/src/gui/ui/controllers/inspector/InspectorQtCommandPort.cpp" PORT)
file(READ "${ROOT}/src/gui/ui/screens/inspector/InspectorRmlBinding.cpp" BINDING)
file(READ "${ROOT}/src/gui/aggregatortileinfo.cpp" TILE)
file(READ "${ROOT}/src/gui/aggregatorcreatureinfo.cpp" CREATURE)
file(READ "${ROOT}/src/gui/aggregatorselection.cpp" SELECTION)
file(READ "${ROOT}/src/gui/eventconnector.cpp" CONNECTOR)
file(READ "${ROOT}/content/shaders/water_v.glsl" WATER_VERTEX_SHADER)
file(READ "${ROOT}/content/shaders/water_f.glsl" WATER_FRAGMENT_SHADER)
foreach(NEEDLE createInspectorBinding signalUpdateTileInfo signalCreatureUpdate signalCreatureCleared signalProfessionList signalUpdateInfo signalUpdateFarm signalUpdatePasture signalUpdateGrove signalAction signalCursorPos setSelectionPointer position(value.position) "m_inspectorController&&m_inspectorController->state().creature")
  string(FIND "${MAIN}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing inspector integration seam: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE onCenterCamera onTerrainCommand onSetBasicOptions onUpdateWorkshopInfo onUpdateStockpileInfo onSetHarvestOptions onSetGroveOptions onRightClick onRotateSelection RemoveFloor FellTree RemovePlant population.set_profession onSetProfession onRequestProfessionList)
  string(FIND "${PORT}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing queued authoritative inspector route: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE RemoveEventListener UnloadDocument bindElement professionListeners skills equipment c-inspector-row__label c-inspector-row__detail creature_preview_details creature_preview_locate creatureDetailsOpen toggleCreatureDetails "IsVisible(true)")
  string(FIND "${BINDING}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing inspector listener teardown evidence: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "const bool tileWorldLabel=" "s.kind!=InspectorKind::None&&s.kind!=InspectorKind::Tile" "text(\"tile_world_label_text\",tileLabel)" "text(\"selection_pointer_tool\",title)" "text(\"selection_pointer_size\",pointerDetail)")
  string(FIND "${BINDING}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Tile inspection must stay compact and pointer-oriented: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "paintWater" "m_sceneFbo" "m_sceneDepth" "m_waterShader" "glBlitFramebuffer")
  string(FIND "${RENDERER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing dedicated water render seam: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "packedLevels" "vWaterFlow" "blocksSurface" "gl_InstanceID")
  string(FIND "${WATER_VERTEX_SHADER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing water surface geometry seam: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "uSceneColor" "uSceneDepth" "uWaterTime" "uWaterQuality" "uDuDvMap" "uNormalMap" "foam")
  string(FIND "${WATER_FRAGMENT_SHADER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing water compositing seam: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "m_info = GuiCreatureInfo{}" "gnome->getActivity()" "getSkillLevel" "getSkillActive" "needsReported" "inventoryItems" "inventoryReported")
string(FIND "${CREATURE}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "Missing creature authoritative refresh seam: ${NEEDLE}")
endif()
endforeach()
foreach(FORBIDDEN "m_info.hunger = 100" "m_info.thirst = 100" "m_info.sleep = 100" "m_info.happiness = 100")
string(FIND "${CREATURE}" "${FORBIDDEN}" POS)
if(NOT POS EQUAL -1)
  message(FATAL_ERROR "Creature producer still fabricates unsupported need data: ${FORBIDDEN}")
endif()
endforeach()
foreach(NEEDLE "needsReported" "inspector.static.not_reported" "meterColor" "SetClass(\"is-good\"" "SetClass(\"is-middle\"" "SetClass(\"is-danger\"")
string(FIND "${BINDING}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "Missing explicit unavailable creature-needs projection: ${NEEDLE}")
endif()
endforeach()
foreach(NEEDLE "m_info.position" "getPos().toString")
string(FIND "${CREATURE}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "Creature producer is missing the world anchor: ${NEEDLE}")
endif()
endforeach()
foreach(NEEDLE "signalSelectCreature" "gnomesAtPosition" "animalsAtPosition" "monstersAtPosition")
string(FIND "${SELECTION}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "World creature selection seam is missing: ${NEEDLE}")
endif()
endforeach()
foreach(NEEDLE "signalSelectCreature" "onRequestCreatureUpdate" "onRequestProfessionList")
string(FIND "${CONNECTOR}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "Creature selection bridge is missing: ${NEEDLE}")
endif()
endforeach()
foreach(NEEDLE "paintCameraPreview" "setCameraPreviewTexture" "cameraPreviewTexture")
  if(NOT MAIN MATCHES "${NEEDLE}" AND NOT RENDERER MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Inspector camera view bridge is missing: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "m_cameraPreviewFbo" "GL_DRAW_FRAMEBUFFER" "paintTiles()" "previewProjection" "previewZoom" "worldY + halfWorldHeight" "m_rotation = 0" "glDrawBuffers" "GL_COLOR_ATTACHMENT0")
  string(FIND "${RENDERER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inspector camera must render its own target-centered viewport: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "CameraPreviewTarget" "CreatureCameraTarget" "creatureCameraTargets" "m_creatureRenderTick" "previousWeight")
  if(NOT MAIN MATCHES "${NEEDLE}" AND NOT RENDERER MATCHES "${NEEDLE}" AND NOT RENDERER_HEADER MATCHES "${NEEDLE}" AND NOT AGGREGATOR MATCHES "${NEEDLE}" AND NOT AGGREGATOR_HEADER MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Inspector camera follow contract is missing: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "m_cameraPreviewWidth = 256" "m_cameraPreviewHeight = 256")
  string(FIND "${RENDERER_HEADER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inspector camera framebuffer must stay square: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "m_tileInfo.plantIsTree = false" "m_tileInfo.plantIsHarvestable = false")
  string(FIND "${TILE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing tile refresh stale-state reset: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "requiredItems" "workPositions" "canRaisePriority" "canLowerPriority")
  string(FIND "${TILE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing authoritative TileInfo job field: ${NEEDLE}")
  endif()
endforeach()
message(STATUS "Inspector queued bridge, lifecycle, and tile-state integration passed")
