set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/content/rmlui/screens/inspector.rml" RML)
file(READ "${ROOT}/content/rmlui/screens/inspector.rcss" RCSS)
foreach(ID inspector_root inspector_panel inspector_drag_handle creature_preview creature_preview_drag_handle creature_preview_kind creature_preview_title creature_preview_close creature_preview_close_label creature_preview_camera_image creature_preview_camera_position creature_preview_activity creature_preview_camera_actions creature_preview_camera_actions_heading creature_preview_stats_panel creature_preview_expertise_panel creature_preview_profession_heading creature_preview_profession_toggle creature_preview_profession_value creature_preview_profession_menu creature_preview_skill_sort_heading creature_preview_skill_sort creature_preview_skill_sort_name creature_preview_skill_sort_level creature_preview_skill_sort_active creature_preview_skills_scroll creature_preview_skills creature_preview_skills_empty creature_preview_strength creature_preview_dexterity creature_preview_constitution creature_preview_intelligence creature_preview_wisdom creature_preview_charisma creature_preview_strength_stat creature_preview_dexterity_stat creature_preview_constitution_stat creature_preview_intelligence_stat creature_preview_wisdom_stat creature_preview_charisma_stat creature_preview_attributes_heading creature_preview_hunger_meter creature_preview_hunger creature_preview_hunger_need creature_preview_thirst_meter creature_preview_thirst creature_preview_thirst_need creature_preview_sleep_meter creature_preview_sleep creature_preview_sleep_need creature_preview_happiness_meter creature_preview_happiness creature_preview_happiness_need creature_preview_needs_heading creature_preview_nav_camera creature_preview_nav_stats creature_preview_nav_expertise creature_preview_nav_equipment creature_preview_nav_inventory creature_preview_camera_panel creature_preview_professions_empty creature_preview_equipment_panel creature_preview_equipment creature_preview_equipment_scope creature_preview_equipment_empty creature_preview_equipment_editor creature_preview_equipment_editor_title creature_preview_equipment_current creature_preview_equipment_types creature_preview_equipment_materials creature_preview_equipment_apply creature_preview_equipment_cancel creature_equipment_slot_head creature_equipment_slot_chest creature_equipment_slot_arms creature_equipment_slot_hands creature_equipment_slot_legs creature_equipment_slot_feet creature_equipment_slot_left_hand creature_equipment_slot_right_hand creature_equipment_slot_back creature_preview_inventory_panel creature_preview_inventory creature_preview_inventory_empty creature_preview_stats_empty creature_preview_locate creature_preview_locate_label tile_world_label tile_world_label_text selection_pointer_tip selection_pointer_tool selection_pointer_size inspector_close inspector_close_label inspector_back inspector_locate inspector_refresh inspector_tile inspector_creature inspector_workshop inspector_stockpile inspector_agriculture selection_configuration tile_mine tile_remove_floor tile_harvest tile_fell tile_remove_plant tile_manage tile_cancel_job tile_raise_job tile_lower_job tile_job_work_positions tile_job_requirements_section tile_job_requirements creature_profession_choices_heading creature_professions creature_professions_empty creature_skills_heading creature_skills creature_skills_empty creature_equipment creature_equipment_empty creature_inventory creature_inventory_empty creature_attributes_heading creature_needs_heading workshop_toggle_suspended stockpile_toggle_suspended agriculture_toggle_suspended agriculture_toggle_primary selection_rotate selection_cancel)
  string(REGEX MATCHALL "id=\"${ID}\"" MATCHES "${RML}")
  list(LENGTH MATCHES COUNT)
  if(NOT COUNT EQUAL 1)
    message(FATAL_ERROR "Inspector ID must exist exactly once: ${ID}")
  endif()
endforeach()
foreach(FORBIDDEN "onclick=" "id=\"creature_preview_skills_heading\"" "id=\"creature_preview_nav_professions\"" "id=\"creature_preview_professions_panel\"" "id=\"creature_preview_profession_select\"" "id=\"creature_preview_profession_control\"" "onchange=" "id=\"creature_preview_stats_toggle\"" "id=\"creature_preview_details\"" "Game\\*" "Aggregator" "Mine\\(" "workshop.set_basics" "camera__reticle" "camera__live")
  string(REGEX MATCH "${FORBIDDEN}" HIT "${RML}")
  if(HIT)
    message(FATAL_ERROR "RML contains forbidden domain/action seam: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "pointer-events: none" "pointer-events: auto" "right: 12dp" "max-width: 40%" "top: 76dp" "bottom: 58dp" "l-creature-preview" "right: 16dp" "bottom: 62dp" "max-width: 42%" "c-inspector-row__label" "c-inspector-row__detail" "c-tile-world-label" "c-selection-pointer-tip" "c-creature-preview-activity-line" "c-creature-preview-meter" "display: flex" "align-items: center" "width: 330dp" "height: 330dp" "#creature_preview_skills_scroll scrollbarvertical" "object-fit: contain" "text-align: center" "flex-basis: 272dp" "overflow-y: auto" "decorator: text(\"^\")" "decorator: text(\"v\")" "padding-right: 8dp" "justify-content: center" "overflow: visible" "is-good" "is-middle" "is-danger" "align-self: stretch" "width: 376dp" "width: 360dp" "l-inspector-scroll > .c-inspector-section" "l-inspector-scroll > .c-inspector-section.is-hidden" "#inspector_tile.is-hidden" "#inspector_creature.is-hidden" "#inspector_creature" "flex-direction: column" "c-inspector-row > *" "white-space: nowrap" "z-index: 20" "z-index: 30" "Creature inspector workbench" "c-creature-preview-rail" "c-creature-preview-content" "c-equipment-doll" "c-equipment-slot" "c-equipment-editor" "image-rendering: pixelated" "border-right-color: #404040" "border-bottom-color: #404040")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing inspector map-gap/input constraint: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "inspector.preview.expertise" "inspector.preview.order_by" "inspector.preview.actions" "c-creature-preview-camera-actions" "c-creature-preview-skill-sort is-hidden" "creature_needs" "c-creature-attribute-grid" "c-creature-needs-summary" "c-creature-preview-camera" "?camera-preview://selected" "creature_preview_camera_position" "creature_skills_empty" "creature_equipment_empty" "creature_inventory_empty" "creature_preview" "tile_job_work_positions" "tile_job_requirements" "aria-disabled")
  string(FIND "${RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing creature inspector data surface: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "move_target=\"inspector_panel\"" "move_target=\"creature_preview\"" "edge_margin=\"76dp 12dp 58dp 12dp\"" "edge_margin=\"52dp 12dp 54dp 12dp\"" "white-space: nowrap")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT RCSS MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing inspector drag or value-layout contract: ${NEEDLE}")
  endif()
endforeach()
foreach(ID inspector_blueprint blueprint_status blueprint_missing_items blueprint_resources_ready blueprint_worker blueprint_priority blueprint_skill_row blueprint_skill blueprint_tool_row blueprint_tool blueprint_cancel_job blueprint_raise_job blueprint_lower_job)
  string(REGEX MATCHALL "id=\"${ID}\"" MATCHES "${RML}")
  list(LENGTH MATCHES COUNT)
  if(NOT COUNT EQUAL 1)
    message(FATAL_ERROR "Blueprint inspector ID must exist exactly once: ${ID}")
  endif()
endforeach()
foreach(NEEDLE "Waiting for materials" "Missing resources" "Status / material" "Cancel blueprint")
  string(FIND "${RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Blueprint inspector is missing its construction surface: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE ".l-inspector-panel.is-blueprint" ".c-blueprint-status" ".c-blueprint-list" ".c-blueprint-detail" "border-top-color: #404040")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Blueprint inspector is missing canonical Windows 98 styling: ${NEEDLE}")
  endif()
endforeach()
message(STATUS "Inspector RML IDs, action isolation, and map-gap ownership passed")

foreach(NEEDLE "class=\"c-window l-creature-preview is-hidden\"" "class=\"c-window__body c-creature-preview-body\"" "role=\"tablist\"" "role=\"tab\"" "role=\"tabpanel\"" "aria-controls=\"creature_preview_expertise_panel\"" "class=\"c-toolbar c-creature-preview-profession-editor\"" "class=\"c-creature-preview-profession-field\"" "class=\"c-list c-scroll-region c-creature-preview-skills-scroll\"" "c-window__resize-grip")
  string(FIND "${RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Detached inspector is missing the canonical inventory-window composition: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "Inventory-aligned detached inspector" "#creature_preview_skills .c-inspector-row:nth-child(even)" "background-color: #000080" "border-top-color: #404040" "font-weight: bold" "letter-spacing: .5dp")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Detached inspector is missing canonical Windows 98 styling: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "Inventory-search aligned Profession control" "min-height: 48dp" "position: absolute" "left: 72dp" "top: 35dp" "z-index: 50")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Profession picker does not match the Inventory search toolbar: ${NEEDLE}")
  endif()
endforeach()
