set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/src/gui/mainwindow.cpp" MAIN)
file(READ "${ROOT}/src/gui/mainwindowrenderer.cpp" RENDERER)
file(READ "${ROOT}/src/gui/mainwindowrenderer.h" RENDERER_HEADER)
file(READ "${ROOT}/src/gui/ui/runtime/RmlUiDetachedWindow.cpp" DETACHED_WINDOW)
file(READ "${ROOT}/src/gui/aggregatorrenderer.cpp" AGGREGATOR)
file(READ "${ROOT}/src/gui/aggregatorrenderer.h" AGGREGATOR_HEADER)
file(READ "${ROOT}/src/game/game.cpp" GAME)
file(READ "${ROOT}/src/game/game.h" GAME_HEADER)
file(READ "${ROOT}/src/game/gamemanager.cpp" GAME_MANAGER)
file(READ "${ROOT}/src/gui/ui/controllers/inspector/InspectorQtCommandPort.cpp" PORT)
file(READ "${ROOT}/src/gui/ui/controllers/inspector/InspectorQtDataAdapter.cpp" ADAPTER)
file(READ "${ROOT}/src/gui/ui/screens/inspector/InspectorRmlBinding.cpp" BINDING)
file(READ "${ROOT}/src/gui/aggregatortileinfo.cpp" TILE)
file(READ "${ROOT}/src/gui/aggregatorcreatureinfo.cpp" CREATURE)
file(READ "${ROOT}/src/gui/aggregatorselection.cpp" SELECTION)
file(READ "${ROOT}/src/gui/eventconnector.cpp" CONNECTOR)
file(READ "${ROOT}/content/shaders/water_v.glsl" WATER_VERTEX_SHADER)
file(READ "${ROOT}/content/shaders/water_f.glsl" WATER_FRAGMENT_SHADER)
foreach(NEEDLE createInspectorBinding openDetachedCreatureInspector m_creatureProfessionChoices setProfessionChoices signalUpdateTileInfo signalCreatureUpdate signalCreatureCleared signalProfessionList signalUpdateInfo signalUpdateFarm signalUpdatePasture signalUpdateGrove signalAction signalCursorPos setSelectionPointer position(value.position))
  string(FIND "${MAIN}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing inspector integration seam: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "independent window" "Parked inspectors retain" "stopRendering" "shared Qt OpenGL context" "RmlUi detached inspector shutdown failed")
  string(FIND "${MAIN}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Detached inspector close path is missing shutdown safety: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE onCenterCamera onTerrainCommand onSetBasicOptions onUpdateWorkshopInfo onUpdateStockpileInfo onSetHarvestOptions onSetGroveOptions onRightClick onRotateSelection RemoveFloor FellTree RemovePlant population.set_profession onSetProfession onRequestProfessionList military.set_uniform_slot onSetArmorType)
  string(FIND "${PORT}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing queued authoritative inspector route: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE RemoveEventListener UnloadDocument reloadDocument bindElement professionListeners renderedProfessionChoices_ "if(!detachedWindow_)clearListeners(professionListeners_)" "renderedProfessionChoices_!=professionOptions" equipmentListeners renderEquipment selectEquipmentSlot setEquipmentDraftType setEquipmentDraftMaterial applyEquipmentSlot skills lastSkillRows_ lastSkillCreatureId_ equipment c-inspector-row__label c-inspector-row__detail creature_preview_nav_camera creature_preview_nav_stats creature_preview_nav_expertise creature_preview_nav_equipment creature_preview_nav_inventory creature_preview_camera_actions creature_preview_locate_label creature_preview_camera_panel creature_preview_stats_panel creature_preview_expertise_panel creature_preview_profession_toggle creature_preview_profession_value creature_preview_profession_menu professionMenuOpen_ creature_preview_equipment_panel creature_preview_inventory_panel creature_preview_skills creature_preview_skill_sort_name creature_preview_skill_sort_level creature_preview_skill_sort_active setPreviewPage previewPageAvailable "visible(view.button,available)" syncPreviewPageButtons PreviewPage::Camera PreviewPage::Stats PreviewPage::Expertise PreviewPage::Equipment PreviewPage::Inventory setSkillSort syncSkillSortButtons SkillSort::Name SkillSort::Level SkillSort::Active creatureDetailsOpen "IsVisible(true)" "RemoveProperty(\"display\")" "SetProperty(\"display\",\"none\")")
  string(FIND "${BINDING}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing inspector listener teardown evidence: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "const bool tileWorldLabel=" "const bool open=s.kind!=InspectorKind::None;" "text(\"tile_world_label_text\",tileLabel)" "text(\"selection_pointer_tool\",title)" "text(\"selection_pointer_size\",pointerDetail)")
  string(FIND "${BINDING}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Tile inspection must expose its panel and pointer context: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "paintWater" "m_sceneFbo" "m_sceneDepth" "m_waterShader" "glBlitFramebuffer")
  string(FIND "${RENDERER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing dedicated water render seam: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "packedLevels" "vWaterFlow" "blocksSurface" "gl_InstanceID")
  string(FIND "${WATER_VERTEX_SHADER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing water surface geometry seam: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "uWaterTime" "uWaterQuality" "uDuDvMap" "uWorldRotation" "shadeWorldColor" "surfacePixel" "ripples" "shore")
  string(FIND "${WATER_FRAGMENT_SHADER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing water compositing seam: ${NEEDLE}")
  endif()
endforeach()
foreach(FORBIDDEN "uSceneColor" "uSceneDepth" "uNormalMap" "uViewportSize")
  string(FIND "${WATER_FRAGMENT_SHADER}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Pixel-art water shader still declares obsolete scene-compositing input: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "m_info = GuiCreatureInfo{}" "availableSkillIDs" "skillPrios" "m_gnomeSkillSnapshots" "gnome->getActivity()" "getSkillLevel" "getSkillActive" "skill.name = skillID" "attributesReported" "hasAttribute" "needsReported" "inventoryItems" "inventoryReported" "m_info.professionReported = true" "m_info.skillsReported = true" "m_info.equipmentReported = true" "m_info.roleID = gnome->roleID()" "m_info.roleName = g->mil()->roleName" "m_info.hunger = animal->hunger()" "gnome( m_currentID )")
string(FIND "${CREATURE}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "Missing creature authoritative refresh seam: ${NEEDLE}")
endif()
endforeach()
foreach(FORBIDDEN "wheel_delta_y" "visibleRows=6")
  string(FIND "${BINDING}" "${FORBIDDEN}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Detached skills still use manual paging instead of the native scrollbar: ${FORBIDDEN}")
  endif()
endforeach()
foreach(FORBIDDEN "refreshSkillCatalog" "DB::ids( \"Skills\" )" "g->gm()->gnomes()" "m_skillIds" "reportInventory( monster )" "reportInventory( animal )")
string(FIND "${CREATURE}" "${FORBIDDEN}" POS)
if(NOT POS EQUAL -1)
  message(FATAL_ERROR "Creature producer still uses a shared skill catalog: ${FORBIDDEN}")
endif()
endforeach()
foreach(FORBIDDEN "m_info.hunger = 100" "m_info.thirst = 100" "m_info.sleep = 100" "m_info.happiness = 100")
string(FIND "${CREATURE}" "${FORBIDDEN}" POS)
if(NOT POS EQUAL -1)
  message(FATAL_ERROR "Creature producer still fabricates unsupported need data: ${FORBIDDEN}")
endif()
endforeach()
foreach(NEEDLE "attributesReported" "creature_preview_attributes_heading" "creature_preview_needs_heading" "needsReported" "inspector.static.not_reported" "hasCreatureStats" "creature_preview_stats_empty" "professionSupported" "meterColor" "SetClass(\"is-good\"" "SetClass(\"is-middle\"" "SetClass(\"is-danger\"")
string(FIND "${BINDING}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "Missing explicit unavailable creature-needs projection: ${NEEDLE}")
endif()
endforeach()
foreach(NEEDLE "m_info.position" "getPos().toString")
string(FIND "${CREATURE}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "Creature producer is missing the world anchor: ${NEEDLE}")
endif()
endforeach()
foreach(NEEDLE "signalSelectCreature" "gnomesAtPosition" "animalsAtPosition" "monstersAtPosition")
string(FIND "${SELECTION}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "World creature selection seam is missing: ${NEEDLE}")
endif()
endforeach()
foreach(NEEDLE "signalSelectCreature" "onRequestCreatureUpdate" "onRequestProfessionList")
string(FIND "${CONNECTOR}" "${NEEDLE}" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "Creature selection bridge is missing: ${NEEDLE}")
endif()
endforeach()
foreach(NEEDLE "paintCameraPreview" "setCameraPreviewTexture" "cameraPreviewTexture" "m_cameraPreviewLastPaintMs" "previewIntervalMs")
  if(NOT MAIN MATCHES "${NEEDLE}" AND NOT RENDERER MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Inspector camera view bridge is missing: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "m_cameraPreviewFbo" "GL_DRAW_FRAMEBUFFER" "paintTiles()" "previewProjection" "previewZoom" "worldY + halfWorldHeight" "m_rotation = 0" "glDrawBuffers" "GL_COLOR_ATTACHMENT0" "Keep water visible in the inspector camera")
  string(FIND "${RENDERER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inspector camera must render its own target-centered viewport: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "resetView" "expanded document viewport" "UiWindow.creature_inspector.workbench.compact" "QSize( 508, 405 )")
  string(FIND "${MAIN}${DETACHED_WINDOW}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Detached inspector must reset its surface before reuse: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "CameraPreviewTarget" "CreatureCameraTarget" "creatureCameraTargets" "m_creatureRenderTick" "previousWeight")
  if(NOT MAIN MATCHES "${NEEDLE}" AND NOT RENDERER MATCHES "${NEEDLE}" AND NOT RENDERER_HEADER MATCHES "${NEEDLE}" AND NOT AGGREGATOR MATCHES "${NEEDLE}" AND NOT AGGREGATOR_HEADER MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Inspector camera follow contract is missing: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "trackedPosition = cameraTarget->currentPosition" "trackedPosition.x - radius" "trackedPosition.y - radius" "m_viewLevel = trackedPosition.z")
  string(FIND "${RENDERER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inspector camera must follow the live creature position instead of the selected tile: ${NEEDLE}")
  endif()
endforeach()
set(AGGREGATOR_CAMERA_MOTION "${AGGREGATOR}${AGGREGATOR_HEADER}")
foreach(NEEDLE "m_creatureMotionSegments" "cameraTargets.insert( creatureID, m_creatureMotionSegments.value( creatureID ) )" "creature.motionTick" "isAdjacentStep ? previousPosition : currentPosition")
  string(FIND "${AGGREGATOR_CAMERA_MOTION}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inspector camera must retain the creature pre/post motion segment until interpolation completes: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "previewIntervalMs = 12" "radius = 10")
  string(FIND "${RENDERER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inspector camera smoothing/performance contract is missing: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "simulationTick != 0" "simulationTick != m_lastCreatureMotionTick" "if ( isNewSimulationTick )")
  string(FIND "${RENDERER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Creature interpolation clock must advance from each fixed simulation snapshot: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "signalSimulationTick" "emit signalSimulationTick( GameState::tick )")
  string(FIND "${GAME}${GAME_HEADER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Game loop must publish every fixed simulation boundary: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "&Game::signalSimulationTick" "&AggregatorRenderer::onSimulationTick")
  string(FIND "${GAME_MANAGER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Fixed simulation boundary is not connected to the renderer bridge: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "m_latestSimulationTick = tick" "signalSimulationTick( tick )")
  string(FIND "${AGGREGATOR_CAMERA_MOTION}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Renderer aggregator does not retain and relay the fixed simulation tick: ${NEEDLE}")
  endif()
endforeach()
string(FIND "${RENDERER}" "containsCreatureMotion" POS)
if(NOT POS EQUAL -1)
  message(FATAL_ERROR "Creature interpolation clock is still gated by unrelated creature motion")
endif()
foreach(NEEDLE "Qt::PreciseTimer" "m_timer->start( 16 )")
  string(FIND "${DETACHED_WINDOW}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Detached inspector must present the follow camera at a smooth 60 FPS cadence: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "m_cameraPreviewWidth = 256" "m_cameraPreviewHeight = 256")
  string(FIND "${RENDERER_HEADER}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Inspector camera framebuffer must stay square: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "m_tileInfo.plantIsTree = false" "m_tileInfo.plantIsHarvestable = false")
  string(FIND "${TILE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing tile refresh stale-state reset: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "requiredItems" "workPositions" "canRaisePriority" "canLowerPriority")
  string(FIND "${TILE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing authoritative TileInfo job field: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "git.available = rim.available" "i.available" "pendingWorkshopBlueprint" "blueprint_missing_items" "blueprint_cancel_job" "blueprint_raise_job" "blueprint_lower_job")
  if(NEEDLE MATCHES "^git\\.")
    string(FIND "${TILE}" "${NEEDLE}" POS)
  elseif(NEEDLE STREQUAL "i.available")
    string(FIND "${ADAPTER}" "${NEEDLE}" POS)
  else()
    string(FIND "${BINDING}" "${NEEDLE}" POS)
  endif()
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing pending-blueprint inspector contract: ${NEEDLE}")
  endif()
endforeach()
message(STATUS "Inspector queued bridge, lifecycle, and tile-state integration passed")
