set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/content/rmlui/screens/inspector.rml" RML)
file(READ "${ROOT}/content/rmlui/screens/inspector.rcss" RCSS)
foreach(ID inspector_root inspector_panel inspector_drag_handle creature_preview creature_preview_drag_handle creature_preview_kind creature_preview_title creature_preview_close creature_preview_camera_image creature_preview_camera_position creature_preview_activity creature_preview_strength creature_preview_dexterity creature_preview_constitution creature_preview_intelligence creature_preview_wisdom creature_preview_charisma creature_preview_hunger_meter creature_preview_hunger creature_preview_thirst_meter creature_preview_thirst creature_preview_sleep_meter creature_preview_sleep creature_preview_happiness_meter creature_preview_happiness creature_preview_details creature_preview_locate tile_world_label tile_world_label_text selection_pointer_tip selection_pointer_tool selection_pointer_size inspector_close inspector_back inspector_locate inspector_refresh inspector_tile inspector_creature inspector_workshop inspector_stockpile inspector_agriculture selection_configuration tile_mine tile_remove_floor tile_harvest tile_fell tile_remove_plant tile_manage tile_cancel_job tile_raise_job tile_lower_job tile_job_work_positions tile_job_requirements_section tile_job_requirements creature_professions creature_professions_empty creature_skills creature_skills_empty creature_equipment creature_equipment_empty creature_inventory creature_inventory_empty workshop_toggle_suspended stockpile_toggle_suspended agriculture_toggle_suspended agriculture_toggle_primary selection_rotate selection_cancel)
  string(REGEX MATCHALL "id=\"${ID}\"" MATCHES "${RML}")
  list(LENGTH MATCHES COUNT)
  if(NOT COUNT EQUAL 1)
    message(FATAL_ERROR "Inspector ID must exist exactly once: ${ID}")
  endif()
endforeach()
foreach(FORBIDDEN "onclick=" "onchange=" "Game\\*" "Aggregator" "Mine\\(" "workshop.set_basics")
  string(REGEX MATCH "${FORBIDDEN}" HIT "${RML}")
  if(HIT)
    message(FATAL_ERROR "RML contains forbidden domain/action seam: ${FORBIDDEN}")
  endif()
endforeach()
foreach(NEEDLE "pointer-events: none" "pointer-events: auto" "right: 12dp" "max-width: 40%" "top: 76dp" "bottom: 58dp" "l-creature-preview" "right: 16dp" "bottom: 62dp" "max-width: 42%" "c-inspector-row__label" "c-inspector-row__detail" "c-tile-world-label" "c-selection-pointer-tip" "c-creature-preview-activity-line" "c-creature-preview-meter" "display: flex" "align-items: center" "width: 330dp" "height: 330dp" "padding-right: 8dp" "justify-content: center" "overflow: visible" "is-good" "is-middle" "is-danger" "align-self: stretch" "width: 376dp" "width: 360dp" "l-inspector-scroll > .c-inspector-section" "l-inspector-scroll > .c-inspector-section.is-hidden" "#inspector_tile.is-hidden" "#inspector_creature.is-hidden" "#inspector_creature" "flex-direction: column" "c-inspector-row > *" "white-space: nowrap" "z-index: 20" "z-index: 30")
  string(FIND "${RCSS}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing inspector map-gap/input constraint: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "creature_needs" "c-creature-attribute-grid" "c-creature-needs-summary" "c-creature-preview-camera" "?camera-preview://selected" "creature_preview_camera_position" "creature_skills_empty" "creature_equipment_empty" "creature_inventory_empty" "creature_preview" "tile_job_work_positions" "tile_job_requirements" "aria-disabled")
  string(FIND "${RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing creature inspector data surface: ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "move_target=\"inspector_panel\"" "move_target=\"creature_preview\"" "edge_margin=\"76dp 12dp 58dp 12dp\"" "edge_margin=\"52dp 12dp 54dp 12dp\"" "overflow-wrap: anywhere" "white-space: nowrap")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT RCSS MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing inspector drag or value-layout contract: ${NEEDLE}")
  endif()
endforeach()
message(STATUS "Inspector RML IDs, action isolation, and map-gap ownership passed")
