set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/content/rmlui/styles/accessibility.rcss" ACCESS)
foreach(NEEDLE ".is-high-contrast" ".is-reduced-motion" "transition: none" "animation: none" "border-width: 3dp")
 string(FIND "${ACCESS}" "${NEEDLE}" POS)
 if(POS EQUAL -1)
  message(FATAL_ERROR "Missing accessibility style ${NEEDLE}")
 endif()
endforeach()
foreach(FILE IN ITEMS content/rmlui/documents/app_shell.rml content/rmlui/screens/game_hud.rml content/rmlui/screens/inspector.rml content/rmlui/windows/workshop_manager.rml content/rmlui/windows/stockpile_manager.rml content/rmlui/panels/agriculture_manager.rml)
 file(READ "${ROOT}/${FILE}" DOC)
 string(FIND "${DOC}" "accessibility.rcss" POS)
 if(POS EQUAL -1)
  message(FATAL_ERROR "Accessibility stylesheet not linked: ${FILE}")
 endif()
endforeach()
message(STATUS "Wave 7 accessibility stylesheet and released-document contract passed")
foreach(FILE IN ITEMS content/rmlui/localization/en.json content/rmlui/localization/qps-long.json content/rmlui/fixtures/localization_long_strings.rml)
 if(NOT EXISTS "${ROOT}/${FILE}")
  message(FATAL_ERROR "Missing localization fixture ${FILE}")
 endif()
endforeach()
file(READ "${ROOT}/content/rmlui/localization/en.json" EN)
file(READ "${ROOT}/content/rmlui/localization/qps-long.json" QPS)
set(RELEASED
 content/rmlui/documents/app_shell.rml
 content/rmlui/screens/game_hud.rml
 content/rmlui/screens/inspector.rml
 content/rmlui/windows/workshop_manager.rml
 content/rmlui/windows/stockpile_manager.rml
 content/rmlui/panels/agriculture_manager.rml)
foreach(FILE IN LISTS RELEASED)
 file(READ "${ROOT}/${FILE}" DOC)
 string(REGEX MATCHALL "data-l10n=\"[A-Za-z0-9_.-]+\"" MATCHES "${DOC}")
 foreach(MATCH IN LISTS MATCHES)
  string(REGEX REPLACE "data-l10n=\"([^\"]+)\"" "\\1" KEY "${MATCH}")
  foreach(CATALOG IN ITEMS EN QPS)
   string(FIND "${${CATALOG}}" "\"${KEY}\"" FOUND)
   if(FOUND EQUAL -1)
    message(FATAL_ERROR "${FILE} key ${KEY} missing from ${CATALOG} catalog")
   endif()
  endforeach()
 endforeach()
endforeach()
foreach(BINDING IN ITEMS
 src/gui/ui/screens/shell/ShellRmlBinding.cpp
 src/gui/ui/screens/hud/HudRmlBinding.cpp
 src/gui/ui/screens/inspector/InspectorRmlBinding.cpp
 src/gui/ui/screens/management6a/Management6ARmlBinding.cpp)
 file(READ "${ROOT}/${BINDING}" SOURCE)
 string(FIND "${SOURCE}" "applyRmlText" APPLIED)
 if(APPLIED EQUAL -1)
  message(FATAL_ERROR "Released binding does not apply the selected text catalog: ${BINDING}")
 endif()
endforeach()
message(STATUS "Released localization keys have en/qps-long coverage and runtime injection")
execute_process(COMMAND powershell.exe -NoProfile -ExecutionPolicy Bypass -File "${CMAKE_CURRENT_LIST_DIR}/verify-released-literals.ps1" -Root "${ROOT}" RESULT_VARIABLE LITERAL_RESULT)
if(NOT LITERAL_RESULT EQUAL 0)
 message(FATAL_ERROR "Released player-facing literal verification failed")
endif()
file(READ "${ROOT}/src/gui/mainwindow.cpp" MAINWINDOW)
foreach(NEEDLE "preeditString()" "QGuiApplication::inputMethod()" "state().prompts.empty()" "accessibility::escapeTarget" "m_workbenchCoordinator->enterGame()" "m_workbenchCoordinator->leaveGame()")
 string(FIND "${MAINWINDOW}" "${NEEDLE}" FOUND)
 if(FOUND EQUAL -1)
  message(FATAL_ERROR "MainWindow navigation/input contract missing: ${NEEDLE}")
 endif()
endforeach()
foreach(LAYER Composition None Workbench Overlay ActiveTool)
 string(FIND "${MAINWINDOW}" "EscapeLayer::${LAYER}" LAYER_${LAYER})
 if(LAYER_${LAYER} EQUAL -1)
  message(FATAL_ERROR "MainWindow Escape arbiter does not handle ${LAYER}")
 endif()
endforeach()
message(STATUS "MainWindow world transition, IME, modal, workbench, and Escape ordering contract passed")
