/* SPDX-License-Identifier: AGPL-3.0-or-later */
#include "InspectorRmlBinding.h"
#include "../../localization/RmlText.h"
#include <RmlUi/Core/Context.h>
#include <RmlUi/Core/Element.h>
#include <RmlUi/Core/ElementDocument.h>
#include <RmlUi/Core/StringUtilities.h>
#include <algorithm>
#include <cstdio>
namespace ingnomia::ui::inspector
{
 void InspectorRmlBinding::Callback::ProcessEvent(Rml::Event&e){fn_(e);}
InspectorRmlBinding::InspectorRmlBinding(Rml::Context&c,int cameraSlot,int windowIndex):context_(c),cameraSlot_(cameraSlot),windowIndex_(windowIndex){cameraSource_=cameraSlot_==0?"?camera-preview://selected":"?camera-preview://slot-"+std::to_string(cameraSlot_);} InspectorRmlBinding::~InspectorRmlBinding(){shutdown();}
bool InspectorRmlBinding::initialize(InspectorController&c){controller_=&c;document_=context_.LoadDocument("screens/inspector.rml");if(!document_)return false;localization::applyRmlText(*document_,textCatalog_);if(auto*image=document_->GetElementById("creature_preview_camera_image"))image->SetAttribute("src",cameraSource_);if(windowIndex_>0)if(auto*preview=document_->GetElementById("creature_preview")){const int index=windowIndex_-1;preview->SetProperty("right",std::to_string(16+(index%3)*380)+"dp");preview->SetProperty("bottom",std::to_string(62+(index/3)*42)+"dp");}
	bind("inspector_back",[this]{controller_->back();});bind("inspector_close",[this]{controller_->close();});bind("inspector_locate",[this]{controller_->locate();});bind("inspector_refresh",[this]{controller_->refresh();});bind("creature_preview_close",[this]{controller_->close();});bind("creature_preview_details",[this]{controller_->toggleCreatureDetails();});bind("creature_preview_locate",[this]{controller_->locate();});
	bind("tile_open_creature",[this]{if(controller_->state().tile&&!controller_->state().tile->creatures.empty())controller_->openCreature(controller_->state().tile->creatures.front().id);});
	bind("tile_mine",[this]{controller_->executeContext(TileContextAction::Mine);});bind("tile_remove_floor",[this]{controller_->executeContext(TileContextAction::RemoveFloor);});bind("tile_harvest",[this]{controller_->executeContext(TileContextAction::Harvest);});bind("tile_fell",[this]{controller_->executeContext(TileContextAction::FellTree);});bind("tile_remove_plant",[this]{controller_->executeContext(TileContextAction::RemovePlant);});bind("tile_manage",[this]{controller_->executeContext(TileContextAction::Manage);});bind("tile_cancel_job",[this]{controller_->executeContext(TileContextAction::CancelJob);});bind("tile_raise_job",[this]{controller_->executeContext(TileContextAction::RaisePriority);});bind("tile_lower_job",[this]{controller_->executeContext(TileContextAction::LowerPriority);});
	bind("workshop_toggle_suspended",[this]{controller_->toggleWorkshopSuspended();});bind("stockpile_toggle_suspended",[this]{controller_->toggleStockpileSuspended();});bind("agriculture_toggle_suspended",[this]{controller_->toggleAgricultureSuspended();});bind("agriculture_toggle_primary",[this]{controller_->toggleAgriculturePrimaryOption();});bind("selection_cancel",[this]{controller_->cancelSelection();});bind("selection_rotate",[this]{controller_->rotateSelection();});
	stateChanged(c.state());document_->Show();return true;}
bool InspectorRmlBinding::activateElement(std::string_view id){if(!document_)return false;if(auto*e=document_->GetElementById(std::string(id))){if(e->HasAttribute("disabled")||!e->IsVisible(true))return false;e->DispatchEvent("click",Rml::Dictionary{});return true;}return false;}
void InspectorRmlBinding::shutdown(){clearListeners(professionListeners_);clearListeners(listeners_);if(document_){context_.UnloadDocument(document_);document_=nullptr;}controller_=nullptr;}
void InspectorRmlBinding::bind(const char*id,std::function<void()>fn){bindEvent(id,"click",[fn=std::move(fn)](Rml::Event&)mutable{fn();});}
void InspectorRmlBinding::bindEvent(const char*id,const char*event,std::function<void(Rml::Event&)>fn){if(auto*e=document_->GetElementById(id))bindElement(e,event,std::move(fn),listeners_);}
void InspectorRmlBinding::bindElement(Rml::Element*e,const char*event,std::function<void(Rml::Event&)>fn,std::vector<Listener>&store){if(!e)return;auto cb=std::make_unique<Callback>(std::move(fn));e->AddEventListener(event,cb.get());store.push_back({e,event,std::move(cb)});}
void InspectorRmlBinding::clearListeners(std::vector<Listener>&store){for(auto&l:store)if(l.target)l.target->RemoveEventListener(l.event.c_str(),l.callback.get());store.clear();}
void InspectorRmlBinding::text(const char*id,const std::string&v){if(auto*e=document_->GetElementById(id))e->SetInnerRML(Rml::StringUtilities::EncodeRml(v));}
void InspectorRmlBinding::rml(const char*id,const std::string&v){if(auto*e=document_->GetElementById(id))e->SetInnerRML(v);}
void InspectorRmlBinding::visible(const char*id,bool v){if(auto*e=document_->GetElementById(id))e->SetClass("is-hidden",!v);}
void InspectorRmlBinding::positionTileLabel(const SelectionConfigurationState&s){if(!document_)return;if(auto*e=document_->GetElementById("tile_world_label")){const auto p=s.pointer.value_or(PointerPosition{16,16});e->SetProperty("left",std::to_string(p.x-42)+"dp");e->SetProperty("top",std::to_string(p.y-10)+"dp");}}
void InspectorRmlBinding::positionSelectionTip(const SelectionConfigurationState&s){if(!document_)return;if(auto*e=document_->GetElementById("selection_pointer_tip")){const auto p=s.pointer.value_or(PointerPosition{16,16});e->SetProperty("left",std::to_string(p.x+14)+"dp");e->SetProperty("top",std::to_string(p.y+18)+"dp");}}
void InspectorRmlBinding::rows(const char*id,const std::vector<TextCountRow>&values){if(!document_)return;auto*e=document_->GetElementById(id);if(!e)return;std::string r;for(const auto&v:values){r+="<div class='c-inspector-row'><span class='c-inspector-row__label'>"+Rml::StringUtilities::EncodeRml(v.label)+"</span>";if(!v.detail.empty())r+="<span class='c-inspector-row__detail'>"+Rml::StringUtilities::EncodeRml(v.detail)+"</span>";if(v.count)r+="<span class='c-inspector-row__count'>x"+std::to_string(v.count)+"</span>";r+="</div>";}e->SetInnerRML(r);}
void InspectorRmlBinding::stateChanged(const InspectorState&s){if(!document_)return;clearListeners(professionListeners_);std::string tileLabel;if(s.tile)tileLabel=!s.tile->water.empty()?s.tile->water:!s.tile->wall.empty()?s.tile->wall:s.tile->construction;const bool tileWorldLabel=s.kind==InspectorKind::Tile&&!tileLabel.empty();const bool selectionTip=s.selection.active&&!s.selection.sizeLabel.empty();const bool creaturePreview=s.kind==InspectorKind::Creature&&s.creature&&!s.creatureDetailsOpen;const bool open=s.kind!=InspectorKind::None&&s.kind!=InspectorKind::Tile;visible("inspector_root",open||tileWorldLabel||selectionTip);visible("inspector_panel",open&&(!creaturePreview));visible("creature_preview",creaturePreview);visible("tile_world_label",tileWorldLabel);visible("selection_pointer_tip",selectionTip);text("tile_world_label_text",tileLabel);visible("inspector_tile",s.kind==InspectorKind::Tile);visible("inspector_creature",s.kind==InspectorKind::Creature);visible("inspector_workshop",s.kind==InspectorKind::Workshop);visible("inspector_stockpile",s.kind==InspectorKind::Stockpile);visible("inspector_agriculture",s.kind==InspectorKind::Agriculture);visible("selection_configuration",false);positionTileLabel(s.selection);positionSelectionTip(s.selection);
	auto tr=[this](const char* key,std::initializer_list<localization::TextArgument> args={}){return textCatalog_.format(LocalizationKey{key},args);};
	if(s.creature){const auto&c=*s.creature;const auto initial=c.name.empty()?std::string{"?"}:c.name.substr(0,1);text("creature_preview_kind",c.profession.empty()?tr("inspector.preview.creature"):tr("inspector.preview.gnome"));text("creature_preview_title",c.name);text("creature_preview_initial",initial);text("creature_preview_profession",c.profession.empty()?tr("inspector.preview.no_profession"):c.profession);text("creature_preview_activity",c.activity.empty()?tr("inspector.static.no_activity"):c.activity);text("creature_preview_strength",std::to_string(c.strength));text("creature_preview_dexterity",std::to_string(c.dexterity));text("creature_preview_constitution",std::to_string(c.constitution));text("creature_preview_intelligence",std::to_string(c.intelligence));text("creature_preview_wisdom",std::to_string(c.wisdom));text("creature_preview_charisma",std::to_string(c.charisma));const auto meter=[this,&tr](const char*valueId,const char*meterId,int value,bool reported){text(valueId,reported?std::to_string(value):tr("inspector.static.not_reported"));if(auto*e=document_->GetElementById(meterId))e->SetProperty("width",std::to_string(reported?std::clamp(value,0,100):0)+"%");};meter("creature_preview_hunger","creature_preview_hunger_meter",c.hunger,c.needsReported[0]);meter("creature_preview_thirst","creature_preview_thirst_meter",c.thirst,c.needsReported[1]);meter("creature_preview_sleep","creature_preview_sleep_meter",c.sleep,c.needsReported[2]);meter("creature_preview_happiness","creature_preview_happiness_meter",c.happiness,c.needsReported[3]);}
	// Need bars are projected separately from their text so unavailable data can
	// remain explicit while reported values receive a useful status color.
	if(s.creature){const auto&c=*s.creature;const auto meterColor=[this](const char*meterId,int value,bool reported){if(auto*e=document_->GetElementById(meterId)){const int normalized=std::clamp(value,0,100);e->SetProperty("width",std::to_string(reported?normalized:0)+"%");e->SetClass("is-good",reported&&normalized>=70);e->SetClass("is-middle",reported&&normalized>=40&&normalized<70);e->SetClass("is-danger",reported&&normalized<40);e->SetClass("is-unavailable",!reported);}};meterColor("creature_preview_hunger_meter",c.hunger,c.needsReported[0]);meterColor("creature_preview_thirst_meter",c.thirst,c.needsReported[1]);meterColor("creature_preview_sleep_meter",c.sleep,c.needsReported[2]);meterColor("creature_preview_happiness_meter",c.happiness,c.needsReported[3]);}
	std::string title=tr("inspector.selection"),kind=tr("inspector.selection"),pos;if(s.selected){if(s.selected->position){const auto&p=*s.selected->position;pos=tr("inspector.position",{{"x",std::to_string(p.x)},{"y",std::to_string(p.y)},{"z",std::to_string(p.z)}});}visible("inspector_locate",s.selected->position.has_value());}else visible("inspector_locate",false);
 if(s.tile){const auto&t=*s.tile;title=t.designationName.empty()?"Tile":t.designationName;kind="Tile";std::vector<std::string>pointerDetails;if(!t.floor.empty())pointerDetails.push_back(t.floor);if(!t.water.empty())pointerDetails.push_back(t.water);if(!t.wall.empty())pointerDetails.push_back(t.wall);if(!t.construction.empty())pointerDetails.push_back(t.construction);std::string pointerDetail;for(const auto&detail:pointerDetails){if(!pointerDetail.empty())pointerDetail+=" | ";pointerDetail+=detail;}text("selection_pointer_tool",title);text("selection_pointer_size",pointerDetail);visible("selection_pointer_size",!pointerDetail.empty());std::vector<TextCountRow>terrain;if(!t.wall.empty())terrain.push_back({t.wall,{},{}});if(!t.floor.empty())terrain.push_back({t.floor,{},{}});if(!t.embedded.empty())terrain.push_back({t.embedded,{},{}});if(!t.plant.empty())terrain.push_back({t.plant,{},{}});if(!t.water.empty())terrain.push_back({t.water,{},{}});rows("tile_terrain",terrain);visible("tile_construction_section",!t.construction.empty());text("tile_construction",t.construction);visible("tile_contents_section",!t.items.empty());rows("tile_contents",t.items);visible("tile_creatures_section",!t.creatures.empty());std::vector<TextCountRow>cr;for(const auto&v:t.creatures)cr.push_back({v.label,{},0});rows("tile_creatures",cr);visible("tile_job_section",t.hasJob);text("tile_job",t.jobName+" | worker "+(t.jobWorker.empty()?"unassigned":t.jobWorker)+" | priority "+t.jobPriority+" | skill "+t.requiredSkill+" | tool "+t.requiredTool+" ("+t.requiredToolAvailable+")");text("tile_job_work_positions","Work positions: "+t.workPositions);visible("tile_job_requirements_section",!t.requiredItems.empty());rows("tile_job_requirements",t.requiredItems);visible("tile_links_section",t.designation.has_value()||!t.roomSummary.empty()||!t.mechanismSummary.empty());text("tile_links",t.designationName+(t.roomSummary.empty()?"":" | "+t.roomSummary)+(t.mechanismSummary.empty()?"":" | "+t.mechanismSummary));visible("tile_mine",t.canMine);visible("tile_remove_floor",t.canRemoveFloor);visible("tile_harvest",t.canHarvest);visible("tile_fell",t.canFell);visible("tile_remove_plant",t.canRemovePlant);visible("tile_manage",t.canManage);if(auto*e=document_->GetElementById("tile_raise_job")){e->SetAttribute("aria-disabled",t.hasJob&&t.canRaisePriority?"false":"true");if(t.hasJob&&t.canRaisePriority)e->RemoveAttribute("disabled");else e->SetAttribute("disabled","disabled");}if(auto*e=document_->GetElementById("tile_lower_job")){e->SetAttribute("aria-disabled",t.hasJob&&t.canLowerPriority?"false":"true");if(t.hasJob&&t.canLowerPriority)e->RemoveAttribute("disabled");else e->SetAttribute("disabled","disabled");}}
 if(s.creature){const auto&c=*s.creature;title=c.name;kind="Creature";text("creature_profession","Profession: "+(c.profession.empty()?"None":c.profession));std::string choices;for(std::size_t i=0;i<s.professionChoices.size();++i){const auto&p=s.professionChoices[i];const auto selected=p==c.profession?" is-selected":"";choices+="<button id='inspector_profession_choice_"+std::to_string(i)+"' class='c-dropdown-button"+std::string(selected)+"' role='option' aria-selected='"+(p==c.profession?"true":"false")+"' data-profession='"+Rml::StringUtilities::EncodeRml(p)+"'>"+Rml::StringUtilities::EncodeRml(p)+"</button>";}if(auto*e=document_->GetElementById("creature_professions")){e->SetInnerRML(choices);for(std::size_t i=0;i<s.professionChoices.size();++i)if(auto*choice=document_->GetElementById("inspector_profession_choice_"+std::to_string(i))){const auto profession=s.professionChoices[i];bindElement(choice,"click",[this,profession](Rml::Event&){controller_->setProfession(profession);},professionListeners_);}}visible("creature_professions_empty",s.professionChoices.empty());text("creature_activity",c.activity.empty()?tr("inspector.static.no_activity"):"Activity: "+c.activity);rows("creature_skills",c.skills);visible("creature_skills_empty",c.skills.empty());const auto attribute=[](const char*label,int value){return std::string("<div class='c-creature-attribute'><span>")+label+"</span><strong>"+std::to_string(value)+"</strong></div>";};rml("creature_attributes",attribute("STR",c.strength)+attribute("DEX",c.dexterity)+attribute("CON",c.constitution)+attribute("INT",c.intelligence)+attribute("WIS",c.wisdom)+attribute("CHA",c.charisma));const auto need=[&](const char*label,std::size_t index,int value){return std::string("<div class='c-creature-need-summary'><span>")+label+"</span><strong>"+(c.needsReported[index]?std::to_string(value):tr("inspector.static.not_reported"))+"</strong></div>";};rml("creature_needs",need("Hunger",0,c.hunger)+need("Thirst",1,c.thirst)+need("Sleep",2,c.sleep)+need("Happiness",3,c.happiness));rows("creature_equipment",c.equipment);visible("creature_equipment_empty",c.equipment.empty());}
	if(s.creature){const auto&c=*s.creature;rows("creature_inventory",c.inventory);visible("creature_inventory_empty",c.inventoryReported&&c.inventory.empty());}
	if(s.workshop){const auto&w=*s.workshop;title=w.name;kind="Workshop";text("workshop_summary","Priority "+std::to_string(w.priority)+" / "+std::to_string(w.maxPriority)+" | products "+std::to_string(w.productCount)+" | queued "+std::to_string(w.queuedJobs));text("workshop_options",std::string(w.suspended?"Suspended":"Active")+" | generated "+(w.acceptGenerated?"accepted":"rejected")+" | auto missing "+(w.autoCraftMissing?"on":"off")+" | stockpile "+(w.linkedStockpile?"linked":"not linked"));text("workshop_toggle_suspended",w.suspended?"Resume workshop":"Suspend workshop");}
	if(s.stockpile){const auto&v=*s.stockpile;title=v.name;kind="Stockpile";text("stockpile_summary","Priority "+std::to_string(v.priority)+" / "+std::to_string(v.maxPriority)+" | "+std::to_string(v.itemCount)+" / "+std::to_string(v.capacity)+" items | "+std::to_string(v.reserved)+" reserved");text("stockpile_options",std::string(v.suspended?"Suspended":"Active")+" | pull from others "+(v.pullFromOthers?"yes":"no")+" | allow pull "+(v.allowPullFromHere?"yes":"no"));rows("stockpile_contents",v.contents);text("stockpile_toggle_suspended",v.suspended?"Resume stockpile":"Suspend stockpile");}
	if(s.agriculture){const auto&a=*s.agriculture;kind=a.target.kind==AgricultureKind::Farm?"Farm":a.target.kind==AgricultureKind::Pasture?"Pasture":"Grove";title=a.name;text("agriculture_kind",kind+" inspection");text("agriculture_summary","Priority "+std::to_string(a.priority)+" / "+std::to_string(a.maxPriority)+" | plots "+std::to_string(a.plots)+" | product "+a.product+" | planted "+std::to_string(a.planted)+" | ready "+std::to_string(a.ready));text("agriculture_options",std::string(a.suspended?"Suspended":"Active")+" | harvest "+(a.target.kind==AgricultureKind::Grove?(a.pick?"pick":"do not pick"):(a.harvest?"on":"off")));text("agriculture_toggle_suspended",a.suspended?"Resume":"Suspend");text("agriculture_toggle_primary",a.target.kind==AgricultureKind::Grove?(a.pick?"Stop picking":"Pick fruit"):(a.harvest?"Stop harvest":"Harvest"));}
	text("inspector_title",title);text("inspector_kind",kind);text("inspector_position",pos);text("creature_preview_camera_position",pos.empty()?tr("inspector.preview.camera_unavailable"):pos);visible("inspector_back",s.kind==InspectorKind::Creature&&(s.previous.has_value()||s.creatureDetailsOpen));visible("inspector_refresh",s.kind!=InspectorKind::None);text("selection_action","Active tool: "+s.selection.actionLabel);std::string geometry="Size "+(s.selection.sizeLabel.empty()?"not anchored":s.selection.sizeLabel);if(s.selection.cursor)geometry+=" | cursor "+std::to_string(s.selection.cursor->x)+","+std::to_string(s.selection.cursor->y)+","+std::to_string(s.selection.cursor->z);text("selection_geometry",geometry);visible("selection_rotate",s.selection.canRotate);text("selection_pointer_tool",s.selection.actionLabel);text("selection_pointer_size","Size "+s.selection.sizeLabel);visible("selection_pointer_size",!s.selection.sizeLabel.empty());text("inspector_status",s.status);
}
} // namespace ingnomia::ui::inspector
