/* SPDX-License-Identifier: AGPL-3.0-or-later */
#include "InspectorController.h"

namespace ingnomia::ui::inspector
{
InspectorController::InspectorController( InspectorCommandPort& commands, InspectorViewPort& view ) : commands_( commands ), view_( view ) { notify(); }
void InspectorController::notify() { ++state_.revision.value; view_.stateChanged( state_ ); }
void InspectorController::beginWorld( WorldEpoch world ) { state_ = {}; state_.world = world; state_.acceptsWorldActions = static_cast<bool>( world ); notify(); }
void InspectorController::endWorld() { state_ = {}; notify(); }
void InspectorController::select( EntityRef ref, InspectorKind kind ) { if( state_.selected != ref ) state_.previous = state_.selected; state_.selected=std::move(ref); state_.kind=kind; state_.status.clear(); }
void InspectorController::showTile( TileInspectorState value ) { if(!state_.acceptsWorldActions||!value.id)return; select({state_.world,EntityKind::Tile,value.id.value,value.position},InspectorKind::Tile);state_.tile=std::move(value);state_.creature.reset();state_.workshop.reset();state_.stockpile.reset();state_.agriculture.reset();state_.professionChoices.clear();state_.creatureDetailsOpen=false;notify(); }
void InspectorController::showCreature( CreatureInspectorState value, std::optional<WorldPosition> position ) { if(!state_.acceptsWorldActions||!value.id)return;const bool sameCreature=state_.kind==InspectorKind::Creature&&state_.creature&&state_.creature->id==value.id;select({state_.world,EntityKind::Creature,value.id.value,position},InspectorKind::Creature);state_.tile.reset();state_.creature=std::move(value);state_.workshop.reset();state_.stockpile.reset();state_.agriculture.reset();if(!sameCreature){state_.professionChoices.clear();state_.creatureDetailsOpen=false;}notify(); }
void InspectorController::setProfessionChoices( std::vector<std::string> value ) { state_.professionChoices=std::move(value);notify(); }
void InspectorController::setProfession( std::string value ) { if(state_.kind==InspectorKind::Creature&&state_.creature&&state_.creature->id&&!value.empty())dispatch("population.set_profession",SetProfessionPayload{state_.creature->id,ProfessionId{std::move(value)}}); }
void InspectorController::showWorkshop( WorkshopInspectorState value ) { if(!state_.acceptsWorldActions||!value.id)return;auto pos=state_.selected?state_.selected->position:std::nullopt;select({state_.world,EntityKind::Workshop,value.id.value,pos},InspectorKind::Workshop);state_.workshop=std::move(value);notify(); }
void InspectorController::showStockpile( StockpileInspectorState value ) { if(!state_.acceptsWorldActions||!value.id)return;auto pos=state_.selected?state_.selected->position:std::nullopt;select({state_.world,EntityKind::Stockpile,value.id.value,pos},InspectorKind::Stockpile);state_.stockpile=std::move(value);notify(); }
void InspectorController::showAgriculture( AgricultureInspectorState value ) { if(!state_.acceptsWorldActions||!value.target.designation)return;auto pos=state_.selected?state_.selected->position:std::nullopt;const auto kind=value.target.kind==AgricultureKind::Farm?EntityKind::Farm:value.target.kind==AgricultureKind::Pasture?EntityKind::Pasture:EntityKind::Grove;select({state_.world,kind,value.target.designation.value,pos},InspectorKind::Agriculture);state_.agriculture=std::move(value);notify(); }
void InspectorController::setSelectionAction( std::string action, bool canRotate ){state_.selection.actionLabel=std::move(action);state_.selection.active=!state_.selection.actionLabel.empty();state_.selection.canRotate=state_.selection.active&&canRotate;if(!state_.selection.active){state_.selection.anchor.reset();state_.selection.sizeLabel.clear();}notify();}
void InspectorController::setSelectionCursor( std::optional<WorldPosition> v ){state_.selection.cursor=v;notify();}
void InspectorController::setSelectionAnchor( std::optional<WorldPosition> v ){state_.selection.anchor=v;notify();}
void InspectorController::setSelectionSize( std::string v ){state_.selection.sizeLabel=std::move(v);notify();}
void InspectorController::setSelectionPointer( std::optional<PointerPosition> v ){if(state_.selection.pointer==v)return;state_.selection.pointer=std::move(v);if(state_.selection.active)notify();}
bool InspectorController::dispatch(std::string_view id,UiActionPayload payload){if(!state_.acceptsWorldActions||!state_.world)return false;UiActionEnvelope a{ActionId{id},RequestId{nextRequest_++},state_.world,std::nullopt,std::move(payload)};auto r=commands_.dispatch(a);if(r.status==CommandStatus::Rejected){state_.status=r.error;notify();return false;}state_.status.clear();if(r.pending)state_.pendingAction=a.request;notify();return true;}
void InspectorController::openCreature(CreatureId id){if(!id)return;dispatch("inspect.select",SelectPayload{{state_.world,EntityKind::Creature,id.value,state_.selected?state_.selected->position:std::nullopt}});}
void InspectorController::toggleCreatureDetails(){if(state_.kind==InspectorKind::Creature&&state_.creature){state_.creatureDetailsOpen=!state_.creatureDetailsOpen;notify();}}
void InspectorController::executeContext(TileContextAction action){if(state_.tile)dispatch("tile.execute_context_action",TileContextPayload{state_.tile->id,action});}
void InspectorController::toggleWorkshopSuspended(){if(!state_.workshop)return;const auto&s=*state_.workshop;dispatch("workshop.set_basics",SetWorkshopBasicsPayload{s.id,s.name,s.priority,!s.suspended,s.acceptGenerated,s.autoCraftMissing,std::nullopt});}
void InspectorController::toggleStockpileSuspended(){if(!state_.stockpile)return;const auto&s=*state_.stockpile;dispatch("stockpile.set_basics",SetStockpileBasicsPayload{s.id,s.name,s.priority,!s.suspended,s.pullFromOthers,s.allowPullFromHere});}
void InspectorController::toggleAgricultureSuspended(){if(!state_.agriculture)return;const auto&s=*state_.agriculture;dispatch("agriculture.set_basics",SetAgricultureBasicsPayload{s.target,s.name,s.priority,!s.suspended});}
void InspectorController::toggleAgriculturePrimaryOption(){if(!state_.agriculture)return;const auto&s=*state_.agriculture;if(s.target.kind==AgricultureKind::Grove)dispatch("agriculture.set_grove_options",SetGroveOptionsPayload{s.target.designation,!s.pick,s.plant,s.fell});else dispatch("agriculture.set_harvest_options",SetHarvestOptionsPayload{s.target,!s.harvest,s.harvestHay,s.tame});}
void InspectorController::refresh(){if(state_.workshop)dispatch("workshop.refresh",WorkshopTargetPayload{state_.workshop->id});else if(state_.stockpile)dispatch("stockpile.refresh",StockpileTargetPayload{state_.stockpile->id});else if(state_.agriculture)dispatch("agriculture.refresh",AgricultureTargetPayload{state_.agriculture->target});else if(state_.selected)dispatch("inspect.select",SelectPayload{*state_.selected});}
void InspectorController::locate(){if(state_.selected&&(state_.selected->position||state_.selected->id))dispatch("view.center_on",CenterPayload{*state_.selected});}
void InspectorController::cancelSelection(){dispatch("tool.cancel",NoPayload{});}
void InspectorController::rotateSelection(){if(state_.selection.canRotate)dispatch("tool.rotate",NoPayload{});}
void InspectorController::close(){if(dispatch("inspect.clear",NoPayload{})){state_.kind=InspectorKind::None;state_.selected.reset();state_.tile.reset();state_.creature.reset();state_.workshop.reset();state_.stockpile.reset();state_.agriculture.reset();notify();}}
void InspectorController::back(){if(state_.kind==InspectorKind::Creature&&state_.creatureDetailsOpen){state_.creatureDetailsOpen=false;notify();}else if(state_.kind==InspectorKind::Creature&&state_.previous){auto p=*state_.previous;dispatch("inspect.select",SelectPayload{p});}else close();}
void InspectorController::onActionFinished(RequestId id,CommandResult r){if(state_.pendingAction!=id)return;state_.pendingAction.reset();state_.status=r.status==CommandStatus::Rejected?r.error:std::string{};notify();}
} // namespace ingnomia::ui::inspector
