#include "gui/ui/screens/hud/HudController.h"
#include "gui/ui/controllers/hud/LegacyToolActionAdapter.h"
#include <cstdlib>
#include <iostream>
using UiGameSpeed = ingnomia::ui::GameSpeed;
#define GameSpeed UiGameSpeed
using namespace ingnomia::ui;
using namespace ingnomia::ui::hud;
namespace { void check(bool v,const char*m){if(!v){std::cerr<<m<<'\n';std::exit(1);}}
struct Port:HudCommandPort{std::vector<UiActionEnvelope> actions;std::vector<std::pair<PromptInstanceId,std::optional<EventResponseTargetId>>> prompts;CommandResult dispatch(const UiActionEnvelope&a)override{actions.push_back(a);return{};}void registerPrompt(PromptInstanceId a,std::optional<EventResponseTargetId>b)override{prompts.emplace_back(a,b);}};
struct View:HudViewPort{HudState state;int changes{};void stateChanged(const HudState&s)override{state=s;++changes;}}; }
int main(){Port port;View view;HudController hud(port,view);hud.beginWorld(WorldEpoch{7});hud.setCamera({{},5,0,9,0,1});hud.setPaused(true);check(port.actions.back().id.value=="sim.set_paused","pause action");check(std::get<SetPausedPayload>(port.actions.back().payload).paused,"pause payload");hud.setSpeed(GameSpeed::Fast);check(port.actions.back().id.value=="sim.set_speed","speed action");hud.changeLevel(99);check(std::get<ChangeLevelPayload>(port.actions.back().payload).absoluteLevel==9,"level clamp");hud.setOverlay(OverlayKind::Jobs,true);check(std::get<OverlayPayload>(port.actions.back().payload).overlay==OverlayKind::Jobs,"overlay");hud.activateTool(ToolId{"mine"});check(std::get<ActivateToolPayload>(port.actions.back().payload).tool.value=="mine","tool");hud.cancelTool();check(port.actions.back().id.value=="tool.cancel","cancel");hud.setTool({ToolId{"build"},ToolCategory::Build,ToolPhase::ChoosingCatalog,{}, {},false,true,0});hud.rotateTool();check(port.actions.back().id.value=="tool.rotate","rotate");BuildCatalogRow chair;chair.id=CatalogId{"chair"};chair.name="Chair";chair.components={ { CatalogId{"plank"}, 2, { { CatalogId{"oak"}, 4 }, { CatalogId{"pine"}, 7 } }, CatalogId{"oak"} } };chair.defaultMaterials={CatalogId{"oak"}};hud.setBuildCatalog({chair});hud.selectBuildMaterial(CatalogId{"chair"},0,CatalogId{"pine"});check(hud.state().buildCatalog.front().components.front().selected.value=="pine","material selection");check(hud.state().buildCatalog.front().defaultMaterials.front().value=="pine","material payload updated");hud.chooseBuild(CatalogId{"chair"});check(port.actions.back().id.value=="tool.choose_build","build");check(std::get<ChooseBuildPayload>(port.actions.back().payload).materials.front().value=="pine","selected material dispatched");check(!hud.enqueuePrompt({},"Broken","Missing",true,true),"malformed yes/no rejected");check(hud.enqueuePrompt({},"Notice","Text",false,false),"ack queued");check(!port.prompts.back().second,"ack no target");hud.respondToPrompt(EventResponse::Acknowledge);check(hud.state().prompts.empty(),"ack removed");check(hud.enqueuePrompt(EventResponseTargetId{42},"Question","Text",true,true),"yes/no queued");check(port.prompts.back().second->value==42,"target retained privately");hud.respondToPrompt(EventResponse::Yes);check(std::get<EventResponsePayload>(port.actions.back().payload).response==EventResponse::Yes,"event response");check(LegacyToolActionAdapter::action(ToolId{"mine"})=="Mine","legacy mapping");check(!LegacyToolActionAdapter::action(ToolId{"create_guard_area"}),"unsupported tool absent");hud.endWorld();const auto count=port.actions.size();hud.cancelTool();check(port.actions.size()==count,"world action blocked after unload");std::cout<<"HUD controller/actions/prompt/tool tests passed\n";}
