set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/src/gui/mainwindow.cpp" MAIN)
file(READ "${ROOT}/src/gui/ui/controllers/hud/HudQtCommandPort.cpp" PORT)
file(READ "${ROOT}/src/game/game.cpp" GAME)
file(READ "${ROOT}/src/gui/aggregatorrenderer.cpp" RENDERER_AGGREGATOR)
file(READ "${ROOT}/src/gfx/spritefactory.cpp" SPRITE_FACTORY)
foreach(NEEDLE signalHudSettlement signalHudClock signalUpdatePause signalUpdateGameSpeed signalUpdateRenderOptions signalEvent signalWatchList m_hudController setWatchRows)
  string(FIND "${MAIN}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing MainWindow HUD integration: ${NEEDLE}")
  endif()
endforeach()
foreach(ACTION onSetPause onSetGameSpeed onSetRenderOptions onCmdBuild onSetSelectionAction onSetSelectionMaterials onCancelSelection onRotateSelection onAnswer tool.set_material SetBuildMaterialPayload)
  string(FIND "${PORT}" "${ACTION}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing queued HUD bridge seam: ${ACTION}")
  endif()
endforeach()
foreach(NEEDLE "hud_tool_stockpile" "hud_tool_remove_designation" "hud_tool_fell_tree" "hud_tool_suspend_job" "ordersToolsPanelKeyForElement")
  string(FIND "${MAIN}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing detached orders-tools routing: ${NEEDLE}")
  endif()
endforeach()
string(FIND "${MAIN}" "isDetachedOrdersToolsElement" DETACHED_ROUTE)
string(FIND "${MAIN}" "return id == \"hud_tool_build\" || id.starts_with( \"hud_build_\" );" BUILD_ONLY_DETACHED_ROUTE)
if(DETACHED_ROUTE EQUAL -1 OR BUILD_ONLY_DETACHED_ROUTE EQUAL -1)
  message(FATAL_ERROR "Only Build should use detached orders-tools routing from the main HUD")
endif()
string(FIND "${MAIN}" "setPauseHandler" PAUSE_HANDLER)
if(PAUSE_HANDLER EQUAL -1)
  message(FATAL_ERROR "Missing HUD-to-shell pause route hook")
endif()
string(FIND "${MAIN}" "ShellControl::TogglePause" PAUSE_ONLY_HANDLER)
if(PAUSE_ONLY_HANDLER EQUAL -1)
  message(FATAL_ERROR "HUD pause handler must toggle simulation without opening the menu")
endif()
foreach(PRODUCER signalHudSettlement signalHudClock)
  string(FIND "${GAME}" "emit ${PRODUCER}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing typed real-data producer: ${PRODUCER}")
  endif()
endforeach()
foreach(NEEDLE "BuildWorkshop" "JobPhase::PENDING" "NeedsResources" "pendingResourcesSprite")
  if(NOT RENDERER_AGGREGATOR MATCHES "${NEEDLE}" AND NOT SPRITE_FACTORY MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Missing pending workshop resource marker: ${NEEDLE}")
  endif()
endforeach()
message(STATUS "HUD integration contract passed")
