file(READ "${CMAKE_CURRENT_LIST_DIR}/../../content/rmlui/screens/game_hud.rml" RML)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../src/gui/ui/screens/hud/HudRmlBinding.cpp" BINDING)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../src/gui/aggregatorinventory.cpp" INVENTORY)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../content/rmlui/screens/hud.rcss" STYLE)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../src/gui/MainWindow.cpp" MAIN_WINDOW)
foreach(ID hud_top_rail hud_watch_rows hud_clock hud_level hud_pause hud_speed_normal hud_speed_fast hud_overlay_designations hud_overlay_jobs hud_overlay_walls hud_overlay_axles hud_tool_shelf hud_sidebar_root hud_open_inventory hud_open_military hud_open_population hud_open_diplomacy hud_tool_build hud_tool_deconstruct hud_tool_mine hud_tool_agriculture hud_tool_designations hud_tool_jobs hud_tool_cancel hud_hint_strip hud_event_blocker hud_event_ack hud_event_yes hud_event_no hud_kingdom_panel hud_kingdom_drag_handle hud_kingdom_close hud_mine_menu hud_mine_heading hud_mine_back hud_mine_remove_floor hud_agriculture_menu hud_agriculture_back hud_tool_fell_tree hud_tool_plant_tree hud_tool_harvest_tree hud_tool_forage hud_tool_remove_plant hud_designations_menu hud_designations_back hud_tool_stockpile hud_tool_farm hud_tool_grove hud_tool_pasture hud_tool_personal_room hud_tool_dormitory hud_tool_dining_hall hud_tool_hospital hud_tool_forbidden hud_tool_remove_designation hud_jobs_menu hud_jobs_back hud_tool_suspend_job hud_tool_resume_job hud_tool_cancel_job hud_tool_lower_priority hud_tool_raise_priority hud_build_panel hud_build_categories hud_build_drag_handle hud_build_heading hud_build_close hud_build_furniture hud_build_workshop hud_build_containers hud_build_utility hud_build_wall hud_build_floor hud_build_stairs hud_build_ramps hud_build_fence hud_build_catalog)
  string(FIND "${RML}" "id=\"${ID}\"" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing HUD id ${ID}")
  endif()
endforeach()
string(FIND "${RML}" "id=\"hud_tool_build\"" BUILD_SIDEBAR_POS)
string(FIND "${RML}" "id=\"hud_tool_deconstruct\"" DECONSTRUCT_SIDEBAR_POS)
string(FIND "${RML}" "id=\"hud_tool_mine\"" MINE_SIDEBAR_POS)
string(FIND "${RML}" "id=\"hud_build_deconstruct\"" DECONSTRUCT_HEADER_POS)
if(BUILD_SIDEBAR_POS EQUAL -1 OR DECONSTRUCT_SIDEBAR_POS LESS BUILD_SIDEBAR_POS OR MINE_SIDEBAR_POS LESS DECONSTRUCT_SIDEBAR_POS)
  message(FATAL_ERROR "Deconstruct must appear in the sidebar between Build and Mine")
endif()
if(NOT DECONSTRUCT_HEADER_POS EQUAL -1)
  message(FATAL_ERROR "Deconstruct must not remain in the Build title bar")
endif()
string(FIND "${STYLE}" ".l-hud-build-panel #hud_build_close {" BUILD_CLOSE_OVERRIDE_POS)
if(NOT BUILD_CLOSE_OVERRIDE_POS EQUAL -1)
  message(FATAL_ERROR "Build Close must inherit the same shared title-bar size as Inventory Close")
endif()
string(FIND "${BINDING}" "tooltipTop -= ancestor->GetBox().GetSize().y" STALE_TOOLTIP_OFFSET_POS)
if(NOT STALE_TOOLTIP_OFFSET_POS EQUAL -1)
  message(FATAL_ERROR "Sidebar tooltip must not apply the removed transform-centering correction")
endif()
foreach(ID hud_pause hud_speed_normal hud_speed_fast hud_overlay_designations hud_overlay_jobs hud_overlay_walls hud_overlay_axles)
  string(FIND "${RML}" "id=\"${ID}\" class=\"c-button\" aria-pressed=\"false\"" PRESSED_POS)
  if(PRESSED_POS EQUAL -1)
    message(FATAL_ERROR "HUD pressed-state contract missing ${ID}")
  endif()
endforeach()
foreach(NEEDLE "c-title-bar" "l-hud-build-rail" "l-hud-build-type-list" "flex-direction: column" "flex-wrap: nowrap" "width: 400dp" "selectvalue" "selectarrow" "decorator: text" "overflow-y: auto" "scrollbarvertical sliderbar" "c-hud-build-actions" "role=\"dialog\"" "aria-modal=\"true\"" "aria-labelledby=\"hud_event_title\"" "aria-describedby=\"hud_event_body\"")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT STYLE MATCHES "${NEEDLE}")
    message(FATAL_ERROR "HUD build navigation contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "position: relative;" "min-width: 500dp;" "min-height: 300dp;" "justify-content: space-between;")
  string(FIND "${STYLE}" "${NEEDLE}" HUD_LAYOUT_POS)
  if(HUD_LAYOUT_POS EQUAL -1)
    message(FATAL_ERROR "HUD event modal geometry contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(ACTION sim.set_paused sim.set_speed view.change_level view.set_overlay tool.activate tool.cancel tool.rotate tool.choose_build event.respond)
  # Localization keys may legitimately contain the same dotted words (for
  # example hud.tool.cancel). Only authored action attributes are forbidden.
  string(REGEX MATCH "data-action[ \t]*=[ \t]*\"[^\"]*${ACTION}[^\"]*\"" ACTION_MATCH "${RML}")
  if(ACTION_MATCH)
    set(POS 0)
  else()
    set(POS -1)
  endif()
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "RML must not author action string ${ACTION}")
  endif()
endforeach()
string(FIND "${BINDING}" "AddEventListener" DIRECT)
if(DIRECT EQUAL -1)
  message(FATAL_ERROR "HUD lacks direct native callbacks")
endif()
string(FIND "${BINDING}" "aria-pressed" PRESSED_BINDING)
if(PRESSED_BINDING EQUAL -1)
  message(FATAL_ERROR "HUD does not project authoritative pressed state")
endif()
foreach(NEEDLE "aria-hidden" "focusedPrompt_" "hud_event_ack")
  if(NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "HUD event modal accessibility contract missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${BINDING}" "button->Focus(true)" EVENT_FOCUS)
if(EVENT_FOCUS EQUAL -1)
  message(FATAL_ERROR "HUD event modal accessibility contract missing button focus")
endif()
foreach(NEEDLE "move_target=\"hud_kingdom_panel\"" "move_target=\"hud_build_panel\"" "edge_margin=\"52dp 12dp 54dp 12dp\"" "hud.jobs.action_help" "closeBuildMenu" "buildMenuOpen_" "hud_tool_plant_tree" "hud_tool_suspend_job" "hud_tool_raise_priority" "hud.launch.inventory" "hud_keyboard_commands" "data-build-component" "c-hud-build-material-select" "selectBuildMaterial" "c-hud-build-empty")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "HUD build panel interaction missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "hud_build_categories_page" "hud_build_types_page" "hud_build_type_list" "hud_build_back" "data-build-type" "buildCategoryPage_" "backToBuildCategories" "c-hud-build-rail-heading")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT STYLE MATCHES "${NEEDLE}" AND NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Build category/type rail contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "l-hud-sidebar" "l-hud-sidebar-center" "l-hud-sidebar-page" "l-hud-sidebar-actions" "c-hud-sidebar-back" "common.back")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT STYLE MATCHES "${NEEDLE}")
    message(FATAL_ERROR "In-sidebar action-menu contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "backToSidebar" "visible(\"hud_sidebar_root\"" "is-submenu-open" "presentation_==Presentation::Full")
  string(FIND "${BINDING}" "${NEEDLE}" SIDEBAR_BINDING_POS)
  if(SIDEBAR_BINDING_POS EQUAL -1)
    message(FATAL_ERROR "In-sidebar action-menu binding missing ${NEEDLE}")
  endif()
endforeach()
if(NOT STYLE MATCHES "\\.l-hud-sidebar[ \t\r\n]*\\{[ \t\r\n]*height: auto;[ \t\r\n]*max-height: 84%;")
  message(FATAL_ERROR "HUD sidebar must size to the active menu while retaining a viewport-safe maximum")
endif()
if(STYLE MATCHES "\\.l-hud-sidebar[ \t\r\n]*\\{[ \t\r\n]*height: 84%;")
  message(FATAL_ERROR "HUD sidebar must not reserve a fixed percentage height")
endif()
if(NOT STYLE MATCHES "\\.l-hud-tools[ \t\r\n]*\\{[^}]*width: 170dp;[^}]*max-width: 170dp;")
  message(FATAL_ERROR "HUD sidebar must retain a concrete background and hit-test width")
endif()
if(NOT STYLE MATCHES "\\.l-hud-sidebar[ \t\r\n]*\\{[^}]*overflow-y: auto;[^}]*display: block;")
  message(FATAL_ERROR "HUD sidebar must use content-sized block flow with viewport overflow")
endif()
if(NOT STYLE MATCHES "\\.l-hud-sidebar \\.l-hud-sidebar-page[ \t\r\n]*\\{[^}]*height: auto;[^}]*max-height: none;[^}]*display: block;[^}]*overflow: visible;")
  message(FATAL_ERROR "HUD sidebar pages must contribute their content height to the shelf box")
endif()
if(NOT STYLE MATCHES "\\.l-hud-sidebar-center[ \t\r\n]*\\{[^}]*top: 0;[^}]*bottom: 0;[^}]*display: flex;[^}]*flex-direction: column;[^}]*justify-content: center;")
  message(FATAL_ERROR "HUD sidebar must use a full-height flex wrapper for true vertical centering")
endif()
if(NOT STYLE MATCHES "\\.l-hud-tools[ \t\r\n]*\\{[^}]*position: relative;[^}]*flex: 0 0 auto;[^}]*transform: translate\\(-100%, 0\\);")
  message(FATAL_ERROR "HUD sidebar must remain content-sized and hide only on the horizontal axis")
endif()
if(NOT STYLE MATCHES "\\.l-hud-sidebar-edge:hover \\+ \\.l-hud-sidebar-center \\.l-hud-tools,[ \t\r\n]*\\.l-hud-tools:hover[ \t\r\n]*\\{[ \t\r\n]*transform: translate\\(0, 0\\);")
  message(FATAL_ERROR "HUD sidebar edge and panel hover must restore the hidden shelf")
endif()
if(STYLE MATCHES "\\.l-hud-sidebar\\.is-submenu-open[ \t\r\n]*\\{")
  message(FATAL_ERROR "An open submenu must retain auto-hide instead of being pinned visible")
endif()
string(FIND "${BINDING}" "if ( controller_->state().tool.active ) controller_->cancelTool();" SIDEBAR_BACK_CANCEL_POS)
if(SIDEBAR_BACK_CANCEL_POS EQUAL -1)
  message(FATAL_ERROR "Sidebar Back must deactivate an active world tool")
endif()
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../content/rmlui/screens/orders_tools.rcss" ORDERS_TOOLS_STYLE)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../content/rmlui/screens/orders_tools.rml" ORDERS_TOOLS_RML)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../src/gui/ui/runtime/RmlUiDetachedWindow.cpp" DETACHED_WINDOW)
foreach(NEEDLE "#hud_orders_tools_panel" "#hud_mine_menu" "width: 260dp" "width: 242dp" "l-hud-designations-menu" "width: 300dp" "width: 282dp" "max-width: none")
  string(FIND "${ORDERS_TOOLS_STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Detached orders-tools layout contract missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${ORDERS_TOOLS_RML}" "<handle" DETACHED_HANDLE_POS)
if(DETACHED_HANDLE_POS EQUAL -1)
  message(FATAL_ERROR "Detached fixed-size tool windows must expose native drag handles")
endif()
string(FIND "${ORDERS_TOOLS_RML}" "move_target=" DETACHED_MOVE_TARGET_POS)
if(NOT DETACHED_MOVE_TARGET_POS EQUAL -1)
  message(FATAL_ERROR "Detached tool handles must not move the RmlUi panel internally")
endif()
foreach(NEEDLE "c-title-bar__mark--mine" "c-title-bar__mark--agriculture" "c-title-bar__mark--designations" "c-title-bar__mark--jobs" "c-title-bar__mark--build" "id=\"hud_mine_drag_handle\" class=\"c-title-bar__drag-handle\"")
  string(FIND "${ORDERS_TOOLS_RML}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Detached order-window header contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "c-title-bar__mark" "flex: 1 1 auto" "justify-content: center" "#hud_hint_strip { display: none; }")
  string(FIND "${ORDERS_TOOLS_STYLE}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Detached order-window chrome contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "m_moving = true" "setMouseGrabEnabled( true )" "updateMove( event->globalPosition() )" "setPosition( m_moveStartWindow + delta )" "hud_orders_tools_panel")
  string(FIND "${DETACHED_WINDOW}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Detached window drag fallback contract missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${BINDING}" "visible(\"hud_build_panel\",s.acceptsWorldActions && buildMenuOpen_)" BUILD_VISIBILITY)
if(BUILD_VISIBILITY EQUAL -1)
  message(FATAL_ERROR "Build panel must remain independently visible from Mine")
endif()
string(FIND "${BINDING}" "visible(\"hud_sidebar_root\"" SIDEBAR_ROOT_VISIBILITY)
if(SIDEBAR_ROOT_VISIBILITY EQUAL -1)
  message(FATAL_ERROR "Root sidebar visibility contract missing")
endif()
foreach(NEEDLE "width: 400dp;" "height: 720dp;" "min-height: 420dp;" "flex: 0 0 104dp;" "flex-direction: column;" "flex-wrap: nowrap;" "width: 100%;" "height: auto;" "max-height: none;")
  string(FIND "${STYLE}" "${NEEDLE}" SAFE_AREA_POS)
  if(SAFE_AREA_POS EQUAL -1)
    message(FATAL_ERROR "HUD build panel safe-area contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "data-build-action='FillHole'" "data-build-action='Replace'" "data-build-action='Build'" "hud_build_action_FillHole_" "hud_build_action_Replace_" "hud_build_action_Build_" "disabled='disabled'" "hud.build.action_build" "hud.build.action_place_blueprint" "hud.build.awaiting_resources" "const bool canPlace = true" "const auto blueprint = !row.available" "can-place-blueprint" "pointer-events: auto" "chooseBuildAction" "updatingBuildCatalog_" "renderedBuildCatalog_" "renderedBuildTypes_ != buildTypes" "renderedBuildTypes_ = buildTypes" "hud.build.available" "c-hud-build-availability" "c-hud-build-card.is-unavailable .c-hud-build-action")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT BINDING MATCHES "${NEEDLE}" AND NOT STYLE MATCHES "${NEEDLE}")
    message(FATAL_ERROR "HUD Build action parity missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "gbi.type = row.value( \"Tab\" ).toString()" "gbi.type = row.value( \"ItemGroup\" ).toString()" "gbi.type = row.value( \"Category\" ).toString()")
  string(FIND "${INVENTORY}" "${NEEDLE}" BUILD_TYPE_POS)
  if(BUILD_TYPE_POS EQUAL -1)
    message(FATAL_ERROR "Build data-driven type contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "case HudToolPanel::Build: return QSize( 400, 720 );" "UiWindow.orders.build.compact2" "row.type = item.type.toStdString();")
  string(FIND "${MAIN_WINDOW}" "${NEEDLE}" BUILD_WINDOW_POS)
  if(BUILD_WINDOW_POS EQUAL -1)
    message(FATAL_ERROR "Compact Build window/adapter contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "DB::selectRows( \"Constructions\", \"Type\", m_buildSelection2String.value( buildSelection ) )" "DB::selectRows( \"Workshops\" )" "DB::selectRows( \"Items\", \"Category\", \"Furniture\" )" "DB::selectRows( \"Items\", \"Category\", \"Utility\" )" "Type\", \"WallFloor\"" "Type\", \"RampCorner\"")
  string(FIND "${INVENTORY}" "${NEEDLE}" CATALOG_SCOPE_POS)
  if(CATALOG_SCOPE_POS EQUAL -1)
    message(FATAL_ERROR "Build catalog scope contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "BuildSelection::Furniture,{}" "BuildSelection::Workshop,{}" "BuildSelection::Utility,{}" "BuildSelection::Wall,{}" "BuildSelection::Ramps,{}")
  string(FIND "${BINDING}" "${NEEDLE}" ALL_CATEGORY_POS)
  if(ALL_CATEGORY_POS EQUAL -1)
    message(FATAL_ERROR "Build menu must request the complete category for ${NEEDLE}")
  endif()
endforeach()
string(FIND "${RML}" "alerts" ALERTS)
if(NOT ALERTS EQUAL -1)
  message(FATAL_ERROR "HUD fabricates alert UI")
endif()
message(STATUS "HUD RML contract passed")
