set(ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
file(READ "${ROOT}/src/gui/mainwindow.cpp" MAIN)
file(READ "${ROOT}/src/gui/ui/controllers/hud/HudQtCommandPort.cpp" PORT)
file(READ "${ROOT}/src/game/game.cpp" GAME)
foreach(NEEDLE signalHudSettlement signalHudClock signalUpdatePause signalUpdateGameSpeed signalUpdateRenderOptions signalEvent signalWatchList m_hudController setWatchRows)
  string(FIND "${MAIN}" "${NEEDLE}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing MainWindow HUD integration: ${NEEDLE}")
  endif()
endforeach()
foreach(ACTION onSetPause onSetGameSpeed onSetRenderOptions onCmdBuild onSetSelectionAction onSetSelectionMaterials onCancelSelection onRotateSelection onAnswer tool.set_material SetBuildMaterialPayload)
  string(FIND "${PORT}" "${ACTION}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing queued HUD bridge seam: ${ACTION}")
  endif()
endforeach()
string(FIND "${MAIN}" "setPauseHandler" PAUSE_HANDLER)
if(PAUSE_HANDLER EQUAL -1)
  message(FATAL_ERROR "Missing HUD-to-shell pause route hook")
endif()
foreach(PRODUCER signalHudSettlement signalHudClock)
  string(FIND "${GAME}" "emit ${PRODUCER}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing typed real-data producer: ${PRODUCER}")
  endif()
endforeach()
message(STATUS "HUD integration contract passed")
