file(READ "${CMAKE_CURRENT_LIST_DIR}/../../content/rmlui/screens/game_hud.rml" RML)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../src/gui/ui/screens/hud/HudRmlBinding.cpp" BINDING)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../src/gui/aggregatorinventory.cpp" INVENTORY)
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../content/rmlui/screens/hud.rcss" STYLE)
foreach(ID hud_top_rail hud_watch_rows hud_clock hud_level hud_pause hud_speed_normal hud_speed_fast hud_overlay_designations hud_overlay_jobs hud_overlay_walls hud_overlay_axles hud_tool_shelf hud_open_inventory hud_open_military hud_open_population hud_open_diplomacy hud_tool_build hud_tool_mine hud_tool_agriculture hud_tool_designations hud_tool_jobs hud_tool_cancel hud_hint_strip hud_event_blocker hud_event_ack hud_event_yes hud_event_no hud_kingdom_panel hud_kingdom_drag_handle hud_kingdom_close hud_mine_menu hud_mine_drag_handle hud_mine_heading hud_mine_close hud_mine_remove_floor hud_agriculture_menu hud_agriculture_drag_handle hud_agriculture_close hud_tool_fell_tree hud_tool_plant_tree hud_tool_harvest_tree hud_tool_forage hud_tool_remove_plant hud_designations_menu hud_designations_drag_handle hud_designations_close hud_tool_stockpile hud_tool_farm hud_tool_grove hud_tool_pasture hud_tool_personal_room hud_tool_dormitory hud_tool_dining_hall hud_tool_hospital hud_tool_forbidden hud_tool_guard hud_tool_remove_designation hud_jobs_menu hud_jobs_drag_handle hud_jobs_close hud_tool_suspend_job hud_tool_resume_job hud_tool_cancel_job hud_tool_lower_priority hud_tool_raise_priority hud_build_panel hud_build_categories hud_build_drag_handle hud_build_heading hud_build_deconstruct hud_build_close hud_build_furniture hud_build_workshop hud_build_containers hud_build_utility hud_build_wall hud_build_floor hud_build_stairs hud_build_ramps hud_build_fence hud_build_catalog)
  string(FIND "${RML}" "id=\"${ID}\"" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Missing HUD id ${ID}")
  endif()
endforeach()
foreach(ID hud_pause hud_speed_normal hud_speed_fast hud_overlay_designations hud_overlay_jobs hud_overlay_walls hud_overlay_axles)
  string(FIND "${RML}" "id=\"${ID}\" class=\"c-button\" aria-pressed=\"false\"" PRESSED_POS)
  if(PRESSED_POS EQUAL -1)
    message(FATAL_ERROR "HUD pressed-state contract missing ${ID}")
  endif()
endforeach()
foreach(NEEDLE "c-title-bar" "l-hud-build-tab-row" "width: 84dp" "flex-wrap: wrap" "width: 440dp" "flex: 0 0 200dp" "selectvalue" "selectarrow" "decorator: text" "overflow-y: auto" "scrollbarvertical sliderbar" "c-hud-build-actions" "role=\"dialog\"" "aria-modal=\"true\"" "aria-labelledby=\"hud_event_title\"" "aria-describedby=\"hud_event_body\"")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT STYLE MATCHES "${NEEDLE}")
    message(FATAL_ERROR "HUD build navigation contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "position: relative;" "min-width: 500dp;" "min-height: 300dp;" "justify-content: space-between;")
  string(FIND "${STYLE}" "${NEEDLE}" HUD_LAYOUT_POS)
  if(HUD_LAYOUT_POS EQUAL -1)
    message(FATAL_ERROR "HUD event modal geometry contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(ACTION sim.set_paused sim.set_speed view.change_level view.set_overlay tool.activate tool.cancel tool.rotate tool.choose_build event.respond)
  # Localization keys may legitimately contain the same dotted words (for
  # example hud.tool.cancel). Only authored action attributes are forbidden.
  string(REGEX MATCH "data-action[ \t]*=[ \t]*\"[^\"]*${ACTION}[^\"]*\"" ACTION_MATCH "${RML}")
  if(ACTION_MATCH)
    set(POS 0)
  else()
    set(POS -1)
  endif()
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "RML must not author action string ${ACTION}")
  endif()
endforeach()
string(FIND "${BINDING}" "AddEventListener" DIRECT)
if(DIRECT EQUAL -1)
  message(FATAL_ERROR "HUD lacks direct native callbacks")
endif()
string(FIND "${BINDING}" "aria-pressed" PRESSED_BINDING)
if(PRESSED_BINDING EQUAL -1)
  message(FATAL_ERROR "HUD does not project authoritative pressed state")
endif()
foreach(NEEDLE "aria-hidden" "focusedPrompt_" "hud_event_ack")
  if(NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "HUD event modal accessibility contract missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${BINDING}" "button->Focus(true)" EVENT_FOCUS)
if(EVENT_FOCUS EQUAL -1)
  message(FATAL_ERROR "HUD event modal accessibility contract missing button focus")
endif()
foreach(NEEDLE "move_target=\"hud_kingdom_panel\"" "move_target=\"hud_mine_menu\"" "move_target=\"hud_agriculture_menu\"" "move_target=\"hud_designations_menu\"" "move_target=\"hud_jobs_menu\"" "move_target=\"hud_build_panel\"" "edge_margin=\"52dp 12dp 54dp 12dp\"" "hud.jobs.action_help" "closeBuildMenu" "buildMenuOpen_" "hud_tool_plant_tree" "hud_tool_guard" "hud_tool_suspend_job" "hud_tool_raise_priority" "hud.launch.inventory" "hud_keyboard_commands" "data-build-component" "c-hud-build-material-select" "selectBuildMaterial" "c-hud-build-empty")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "HUD build panel interaction missing ${NEEDLE}")
  endif()
endforeach()
string(FIND "${BINDING}" "visible(\"hud_build_panel\",s.acceptsWorldActions && buildMenuOpen_)" BUILD_VISIBILITY)
if(BUILD_VISIBILITY EQUAL -1)
  message(FATAL_ERROR "Build panel must remain independently visible from Mine")
endif()
string(FIND "${BINDING}" "visible(\"hud_mine_menu\",mineMenuOpen_ && s.acceptsWorldActions)" MINE_VISIBILITY)
if(MINE_VISIBILITY EQUAL -1)
  message(FATAL_ERROR "Mine panel visibility contract missing")
endif()
foreach(NEEDLE "height: 600dp;" "min-height: 600dp;" "max-height: 600dp;" "height: 216dp;" "top: 122dp; bottom: 4dp;" "top: 28dp; bottom: 4dp;" "left: 2dp; right: 2dp;" "height: auto;" "max-height: none;")
  string(FIND "${STYLE}" "${NEEDLE}" SAFE_AREA_POS)
  if(SAFE_AREA_POS EQUAL -1)
    message(FATAL_ERROR "HUD build panel safe-area contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "data-build-action='FillHole'" "data-build-action='Replace'" "data-build-action='Build'" "hud_build_action_FillHole_" "hud_build_action_Replace_" "hud_build_action_Build_" "disabled='disabled'" "hud.build.action_build" "chooseBuildAction" "updatingBuildCatalog_" "renderedBuildCatalog_")
  if(NOT RML MATCHES "${NEEDLE}" AND NOT BINDING MATCHES "${NEEDLE}")
    message(FATAL_ERROR "HUD Build action parity missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "DB::selectRows( \"Constructions\", \"Type\", m_buildSelection2String.value( buildSelection ) )" "DB::selectRows( \"Workshops\" )" "DB::selectRows( \"Items\", \"Category\", \"Furniture\" )" "DB::selectRows( \"Items\", \"Category\", \"Utility\" )" "Type\", \"WallFloor\"" "Type\", \"RampCorner\"")
  string(FIND "${INVENTORY}" "${NEEDLE}" CATALOG_SCOPE_POS)
  if(CATALOG_SCOPE_POS EQUAL -1)
    message(FATAL_ERROR "Build catalog scope contract missing ${NEEDLE}")
  endif()
endforeach()
foreach(NEEDLE "BuildSelection::Furniture,{}" "BuildSelection::Workshop,{}" "BuildSelection::Utility,{}" "BuildSelection::Wall,{}" "BuildSelection::Ramps,{}")
  string(FIND "${BINDING}" "${NEEDLE}" ALL_CATEGORY_POS)
  if(ALL_CATEGORY_POS EQUAL -1)
    message(FATAL_ERROR "Build menu must request the complete category for ${NEEDLE}")
  endif()
endforeach()
string(FIND "${RML}" "alerts" ALERTS)
if(NOT ALERTS EQUAL -1)
  message(FATAL_ERROR "HUD fabricates alert UI")
endif()
message(STATUS "HUD RML contract passed")
