cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(MILITARY "${ROOT}/content/rmlui/windows/military_manager.rml")
set(DIPLOMACY "${ROOT}/content/rmlui/windows/diplomacy_missions.rml")
set(STYLE "${ROOT}/content/rmlui/windows/management6c.rcss")
set(BINDING "${ROOT}/src/gui/ui/screens/management6c/Management6CRmlBinding.cpp")
set(TEXT "${ROOT}/src/gui/ui/screens/management6c/Management6CText.h")

foreach(path IN LISTS MILITARY DIPLOMACY STYLE BINDING TEXT)
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "Missing management 6C artifact: ${path}")
  endif()
endforeach()

file(READ "${MILITARY}" military)
file(READ "${DIPLOMACY}" diplomacy)
file(READ "${STYLE}" style)
file(READ "${BINDING}" binding)
file(READ "${TEXT}" text_catalog)
# The catalog includes the shared Windows 98 window text (Stage 21c).
file(READ "${CMAKE_CURRENT_LIST_DIR}/../../src/gui/ui/localization/UiTextWin98Entries.inc" win98_text)
string(APPEND text_catalog "${win98_text}")

foreach(tab IN ITEMS "military_tab_squads" "military_tab_roles" "military_tab_priorities"
    "military_tab_neighbors" "military_tab_missions" "diplomacy_tab_squads"
    "diplomacy_tab_roles" "diplomacy_tab_priorities" "diplomacy_tab_neighbors" "diplomacy_tab_missions")
  if((tab MATCHES "^military_" AND NOT military MATCHES "id=\"${tab}\"")
      OR (tab MATCHES "^diplomacy_" AND NOT diplomacy MATCHES "id=\"${tab}\""))
    message(FATAL_ERROR "Shared Military and Diplomacy navigation is missing ${tab}")
  endif()
endforeach()

foreach(document IN ITEMS military diplomacy)
  foreach(needle IN ITEMS "/templates/management_window.rml" "<template src=\"management-window\">")
    string(FIND "${${document}}" "${needle}" template_contract)
    if(template_contract LESS 0)
      message(FATAL_ERROR "${document} shared management-window template missing ${needle}")
    endif()
  endforeach()
endforeach()
# Stage 14: Military is a Windows 98 property sheet with connected tabs and a Close button.
foreach(needle IN ITEMS "w98-sheet" "w98-caption" "c-connected-tabs" "role=\"tablist\"" "role=\"tab\"" "aria-selected=\"false\"" "w98-buttonbar" "military_close_button"
    "military_tab_members" "military_tab_uniforms" "military_member_destination" "member_move_to" "role_civilian" "type=\"radio\" name=\"military_attitude\"")
  string(FIND "${military}" "${needle}" sheet_contract)
  if(sheet_contract LESS 0)
    message(FATAL_ERROR "military property-sheet contract missing ${needle}")
  endif()
endforeach()
foreach(needle IN ITEMS "military_views_toggle" "military_rail" "member_move_up" "role_toggle_civilian" "military_confirm_layer")
  string(FIND "${military}" "${needle}" removed)
  if(NOT removed LESS 0)
    message(FATAL_ERROR "military must not keep the replaced control ${needle}")
  endif()
endforeach()
# Stage 15: Diplomacy is a Windows 98 property sheet; missions are planned in the Send Mission wizard.
foreach(needle IN ITEMS "w98-sheet" "w98-caption" "c-connected-tabs" "role=\"tablist\"" "aria-selected=\"false\"" "w98-buttonbar" "diplomacy_close_button"
    "mission_wizard" "w98-wizard" "wizard_back" "wizard_next" "mission_start" "wizard_cancel" "type=\"radio\" name=\"mission_type\"" "type=\"radio\" name=\"mission_action\"")
  string(FIND "${diplomacy}" "${needle}" sheet_contract)
  if(sheet_contract LESS 0)
    message(FATAL_ERROR "diplomacy property-sheet and wizard contract missing ${needle}")
  endif()
endforeach()
if(NOT military MATCHES "<body id=\"military_root\" class=\"[^\"]*is-hidden")
  message(FATAL_ERROR "military_root must initialize hidden")
endif()
if(NOT diplomacy MATCHES "<body id=\"diplomacy_root\" class=\"[^\"]*is-hidden")
  message(FATAL_ERROR "diplomacy_root must initialize hidden")
endif()

if(military MATCHES "on(click|change|keydown)[ \t]*=" OR diplomacy MATCHES "on(click|change|keydown)[ \t]*=")
  message(FATAL_ERROR "RML-authored actions are forbidden; callbacks must be native")
endif()
if(NOT binding MATCHES "applyRmlText.*military_" OR NOT binding MATCHES "applyRmlText.*diplomacy_")
  message(FATAL_ERROR "Both released management 6C documents must receive localized text")
endif()
foreach(document IN ITEMS military diplomacy)
  string(REGEX MATCHALL "data-l10n(-placeholder)?=\"[A-Za-z0-9_.-]+\"" localized_attributes "${${document}}")
  foreach(attribute IN LISTS localized_attributes)
    string(REGEX REPLACE "data-l10n(-placeholder)?=\"([^\"]+)\"" "\\2" key "${attribute}")
    string(FIND "${text_catalog}" "\"${key}\"" found_key)
    if(found_key LESS 0)
      message(FATAL_ERROR "${document} localization key is absent from the owned management 6C catalog: ${key}")
    endif()
  endforeach()
endforeach()
if(NOT military MATCHES "_loading" OR NOT military MATCHES "_error"
    OR NOT diplomacy MATCHES "_loading" OR NOT diplomacy MATCHES "_empty" OR NOT diplomacy MATCHES "_error")
  message(FATAL_ERROR "Each management document needs loading, empty, and error states")
endif()

string(FIND "${style}" ".m6c-root" root_style)
string(FIND "${style}" ".is-hidden { display: none; }" hidden_style)
string(FIND "${style}" "pointer-events: none" root_pointer)
string(FIND "${style}" ".m6c-workbench" workbench_style)
string(FIND "${style}" "pointer-events: auto" workbench_pointer)
if(hidden_style LESS 0 OR root_style LESS 0 OR root_pointer LESS root_style OR workbench_style LESS 0 OR workbench_pointer LESS workbench_style)
  message(FATAL_ERROR "Workbench root must preserve map ownership outside interactive chrome")
endif()

foreach(required IN ITEMS
    "military_squad_rows" "military_role_rows" "military_member_rows" "military_priority_rows"
    "military_uniform_rows" "member_assign_squad"
    "diplomacy_neighbor_rows" "diplomacy_mission_rows" "diplomacy_gnome_rows")
  if(NOT military MATCHES "id=\"${required}\"" AND NOT diplomacy MATCHES "id=\"${required}\"")
    message(FATAL_ERROR "Missing required keyboard/delegation surface: ${required}")
  endif()
endforeach()

foreach(surface IN ITEMS Squads Roles Members Unassigned Priorities UniformSlots Neighbors Missions Gnomes)
  if(NOT binding MATCHES "RowSurface::${surface}" OR NOT binding MATCHES "appendWindowControls[^\n]*RowSurface::${surface}")
    message(FATAL_ERROR "Generated list ${surface} is not explicitly DOM-window bounded")
  endif()
endforeach()
# Uniform, role and destination drop-down lists are rebuilt through the select API (SelectOptions.h).
if(NOT binding MATCHES "setSelectOptions")
  message(FATAL_ERROR "Military drop-down lists must be rebuilt through setSelectOptions")
endif()
if(NOT binding MATCHES "handleWindowPage" OR NOT binding MATCHES "data-window-start")
  message(FATAL_ERROR "Bounded dynamic lists require real native paging controls")
endif()
if(NOT binding MATCHES "renderedRml_\.try_emplace" OR NOT binding MATCHES "cached->second == value")
  message(FATAL_ERROR "Unchanged bounded row windows must not reconstruct their DOM")
endif()

# Deletions use the shared Windows 98 message box (a real modal document with focus restoration).
if(NOT binding MATCHES "win98_message_box.rml" OR NOT binding MATCHES "confirmDestructive" OR NOT binding MATCHES "cancelDestructive")
  message(FATAL_ERROR "Destructive confirmation must use the shared modal message box")
endif()

foreach(required IN ITEMS
    "data-squad" "data-role" "data-creature" "data-priority" "data-uniform-slot"
    "data-neighbor" "data-mission" "data-gnome" "keydown" "Focus\(\)"
    "openMilitary" "openDiplomacy" "closeRoute" "FocusToken")
  if(NOT binding MATCHES "${required}")
    message(FATAL_ERROR "Native binding is missing stable-ID/keyboard/route proof: ${required}")
  endif()
endforeach()

if(diplomacy MATCHES "Alerts|notification history|relationship history[ \t]*</h")
  message(FATAL_ERROR "Unsupported alert/history surfaces must remain absent")
endif()
if(diplomacy MATCHES "mission_type_explore")
  message(FATAL_ERROR "Targeted Explore is not a currently exposed neighbor action")
endif()

function(assert_unique_ids path)
  file(READ "${path}" source)
  string(REGEX MATCHALL "id=\"[A-Za-z0-9_-]+\"" matches "${source}")
  set(seen "")
  foreach(match IN LISTS matches)
    list(FIND seen "${match}" existing)
    if(NOT existing LESS 0)
      message(FATAL_ERROR "Duplicate static RML ID in ${path}: ${match}")
    endif()
    list(APPEND seen "${match}")
  endforeach()
endfunction()
assert_unique_ids("${MILITARY}")
assert_unique_ids("${DIPLOMACY}")

message(STATUS "Management 6C RML contract verified")
