/* SPDX-License-Identifier: AGPL-3.0-or-later */
#pragma once
#include "../../localization/UiText.h"

namespace ingnomia::ui::management6c
{
[[nodiscard]] inline localization::UiText management6cEnglishText()
{
	return localization::UiText( {
		{"common.search","Search"},
		{"management.flow.list_tools","Filter / sort"},
		{"management.military.title","Military & Diplomacy"},
		{"management.navigation.views","Views"},
		{"management.military.window_title","Military"},
		{"management.diplomacy.window_title","Diplomacy"},
		{"management.military.views_label","Military views"},
		{"management.diplomacy.views_label","Diplomacy views"},
		{"management.military.views_help","Open the Military views menu."},
		{"management.diplomacy.views_help","Open the Diplomacy views menu."},
		{"management.military.squads_help","Manage squads, order, members, and roles."},
		{"management.military.roles_help","Edit role names, civilian behavior, and uniform rules."},
		{"management.military.priorities_help","Order targets and choose each response."},
		{"management.diplomacy.neighbors_help","Review discovered neighbors and prepare a mission."},
		{"management.diplomacy.missions_help","Review active and completed mission details."},
		{"management.military.close","Close"},
		{"management.military.squads","Squads"},
		{"management.military.roles_uniforms","Roles & Uniforms"},
		{"management.military.target_priorities","Target priorities"},
		{"management.military.source_order","Original order"},
		{"management.military.squad_order","Squad order"},
		{"management.military.name_order","Name"},
		{"management.military.refresh","Refresh"},
		{"management.military.loading_title","Loading military records"},
		{"management.military.loading_detail","Waiting for the latest military records."},
		{"management.military.empty_title","No military records"},
		{"management.military.empty_detail","No squads, unassigned citizens, or roles were returned."},
		{"management.military.error_title","Military data unavailable"},
		{"management.military.error_detail","The payload was rejected or the bridge is unavailable."},
		{"management.military.retry","Retry"},
		{"management.military.previous_row","Previous row"},
		{"management.military.next_row","Next row"},
		{"management.military.squad","Squad"},
		{"management.military.add_squad","Add squad"},
		{"management.military.move_up","Move up"},
		{"management.military.move_down","Move down"},
		{"management.military.delete","Delete..."},
		{"management.military.squad_name","Squad name"},
		{"management.military.rename","Rename"},
		{"management.military.roster","Roster"},
		{"management.military.move_previous_squad","Move to previous squad"},
		{"management.military.move_next_squad","Move to next squad"},
		{"management.military.remove_from_squad","Remove from squad"},
		{"management.military.unassigned_citizens","Unassigned citizens"},
		{"management.military.unassigned_help","Select a citizen, then assign them to the selected squad or choose a role."},
		{"management.military.roster_help","Select a citizen to change their squad or role."},
		{"management.military.assign_selected_squad","Assign to squad"},
		{"management.military.role","Role"},
		{"management.military.add_role","Add role"},
		{"management.military.toggle_civilian","Civilian"},
		{"management.military.role_name","Role name"},
		{"management.military.selected_citizen","Selected citizen"},
		{"management.military.no_citizen_selected","No citizen selected."},
		{"management.military.assign_selected_role","Assign selected citizen to this role"},
		{"management.military.uniform_slots","Uniform slots"},
		{"management.military.legal_types","Equipment"},
		{"management.military.reported_materials","Material"},
		{"management.military.attitude_flee","Flee"},
		{"management.military.attitude_defend","Defend"},
		{"management.military.attitude_attack","Attack"},
		{"management.military.attitude_hunt","Hunt"},
		{"management.military.confirm_removal","Confirm removal"},
		{"management.military.remove_record","Remove this record?"},
		{"management.military.cancel","Cancel"},
		{"management.military.remove","Remove"},
		{"management.military.search_placeholder","Filter squads"},
		{"management.diplomacy.title","Neighbors and Missions"},
		{"management.diplomacy.heading","Neighbors & Missions"},
		{"management.diplomacy.close","Close"},
		{"management.diplomacy.neighbors","Neighbors"},
		{"management.diplomacy.mission_activity","Missions"},
		{"management.diplomacy.source_order","Original order"},
		{"management.diplomacy.neighbor_order","Neighbor order"},
		{"management.diplomacy.name_type_order","Name/type"},
		{"management.diplomacy.refresh","Refresh"},
		{"management.diplomacy.loading_title","Loading neighbors and missions"},
		{"management.diplomacy.loading_detail","Waiting for masked neighbor data and current mission records."},
		{"management.diplomacy.empty_title","No neighbors or missions"},
		{"management.diplomacy.empty_detail","There are no records to show in this view."},
		{"management.diplomacy.error_title","Diplomacy data unavailable"},
		{"management.diplomacy.error_detail","The payload was rejected or the bridge is unavailable."},
		{"management.diplomacy.retry","Retry"},
		{"management.diplomacy.previous_row","Previous row"},
		{"management.diplomacy.next_row","Next row"},
		{"management.diplomacy.neighbor","Neighbor"},
		{"management.diplomacy.distance","Distance"},
		{"management.diplomacy.type","Type"},
		{"management.diplomacy.attitude","Attitude"},
		{"management.diplomacy.wealth","Wealth"},
		{"management.diplomacy.economy","Economy"},
		{"management.diplomacy.military","Military"},
		{"management.diplomacy.undiscovered_neighbor","Undiscovered neighbor"},
		{"management.diplomacy.masked_detail","Details remain masked by the game."},
		{"management.diplomacy.start_supported_mission","New mission"},
		{"management.diplomacy.spy","Spy"},
		{"management.diplomacy.emissary","Emissary"},
		{"management.diplomacy.raid","Raid"},
		{"management.diplomacy.sabotage","Sabotage"},
		{"management.diplomacy.improve_relations","Improve relations"},
		{"management.diplomacy.insult","Insult"},
		{"management.diplomacy.invite_trader","Invite trader"},
		{"management.diplomacy.invite_ambassador","Invite ambassador"},
		{"management.diplomacy.eligible_gnome","Citizen"},
		{"management.diplomacy.start_mission","Start mission"},
		{"management.diplomacy.mission","Mission"},
		{"management.diplomacy.stable_mission_id","Mission details"},
		{"management.diplomacy.action","Action"},
		{"management.diplomacy.step","Status"},
		{"management.diplomacy.target","Destination"},
		{"management.diplomacy.participants","Participants"},
		{"management.diplomacy.current_timing","Time"},
		{"management.diplomacy.result_reported","Result"},
		{"management.diplomacy.unsupported_history","Cancel, reassignment, and historical relationship records are not reported."},
		{"management.diplomacy.search_placeholder","Filter neighbors"},
		{"management.military.sort","Sort: original order"},
		{"management.military.squad_up","Earlier squad"},
		{"management.military.squad_down","Later squad"},
		{"management.military.civilian_help","Civilian roles retreat to an appropriate area during an alarm."},
		{"management.military.slot","Slot"},
		{"management.diplomacy.go_neighbors","Go to Neighbors"},
		{"management.diplomacy.discovery_help","Discover this kingdom to see its details and send missions."},
		{"management.diplomacy.view_missions","View missions"},
		{"management.military.back","Back to list"},
		{"management.flow.no_role","No role"},
		{"management.flow.unknown_role","Unknown role"},
		{"management.flow.choose_citizen","Select a citizen to change their role or squad."},
		{"management.flow.no_citizen","No citizen selected"},
		{"management.flow.civilian_on","Civilian: on"},
		{"management.flow.civilian_off","Civilian: off"},
		{"management.flow.flee_help","Flee: avoid combat."},
		{"management.flow.defend_help","Defend: hold position."},
		{"management.flow.attack_help","Attack: engage on sight."},
		{"management.flow.hunt_help","Hunt: seek out this target."},
		{"management.flow.none","None"},
		{"management.flow.any","Any"},
		{"management.flow.no_roles","No roles available"},
		{"management.flow.filter_roles","Filter roles"},
		{"management.flow.filter_squads","Filter squads"},
		{"management.flow.filter_neighbors","Filter neighbors"},
		{"management.flow.filter_missions","Filter mission types"},
		{"management.flow.sort_original","Sort: original order"},
		{"management.flow.sort_name","Sort: name"},
		{"management.flow.sort_type","Sort: type"},
		{"management.flow.selected_hidden","Selection is hidden by the filter."},
		{"management.flow.eligible_loading","Loading eligible citizens..."},
		{"management.flow.eligible_error","Could not load citizens. Refresh to try again."},
		{"management.flow.eligible_empty","No eligible citizens are available."},
		{"management.flow.no_missions","No missions"},
		{"management.flow.no_missions_help","Start a mission from a discovered kingdom in Neighbors."},
		{"management.flow.no_neighbors","No neighbors"},
		{"management.flow.no_neighbors_help","No neighboring kingdoms are available yet."},
		{"management.uniform.HeadArmor","Head"},
		{"management.uniform.ChestArmor","Chest"},
		{"management.uniform.ArmArmor","Arms"},
		{"management.uniform.HandArmor","Hands"},
		{"management.uniform.LegArmor","Legs"},
		{"management.uniform.FootArmor","Feet"},
		{"management.uniform.LeftHandHeld","Left hand"},
		{"management.uniform.RightHandHeld","Right hand"},
		{"management.uniform.Back","Back"},
#include "../../localization/UiTextWin98Entries.inc"
	} );
}
} // namespace ingnomia::ui::management6c
