/* SPDX-License-Identifier: AGPL-3.0-or-later */
#pragma once

#include "../../localization/UiText.h"

namespace ingnomia::ui::management6c
{

[[nodiscard]] inline localization::UiText management6cEnglishText()
{
	return localization::UiText( {
		{"management.military.title","Military"},
		{"management.military.close","Close"},
		{"management.military.squads","Squads"},
		{"management.military.roles_uniforms","Roles & Uniforms"},
		{"management.military.target_priorities","Target priorities"},
		{"management.military.source_order","Source order v"},
		{"management.military.name_order","Name order v"},
		{"management.military.refresh","Refresh"},
		{"management.military.loading_title","Loading military records"},
		{"management.military.loading_detail","Waiting for the authoritative game-thread snapshot."},
		{"management.military.empty_title","No military records"},
		{"management.military.empty_detail","No squads, unassigned citizens, or roles were returned."},
		{"management.military.error_title","Military data unavailable"},
		{"management.military.error_detail","The payload was rejected or the bridge is unavailable."},
		{"management.military.retry","Retry"},
		{"management.military.previous_row","Previous row"},
		{"management.military.next_row","Next row"},
		{"management.military.squad","Squad"},
		{"management.military.add_squad","Add squad"},
		{"management.military.move_up","Move up"},
		{"management.military.move_down","Move down"},
		{"management.military.delete","Delete..."},
		{"management.military.squad_name","Squad name"},
		{"management.military.rename","Rename"},
		{"management.military.roster","Roster"},
		{"management.military.move_previous_squad","Move to previous squad"},
		{"management.military.move_next_squad","Move to next squad"},
		{"management.military.remove_from_squad","Remove from squad"},
		{"management.military.unassigned_citizens","Unassigned citizens"},
		{"management.military.unassigned_help","These citizens are not members of a squad. Select one here, then choose a role on the Roles & Uniforms tab."},
		{"management.military.role","Role"},
		{"management.military.add_role","Add role"},
		{"management.military.toggle_civilian","Toggle civilian"},
		{"management.military.role_name","Role name"},
		{"management.military.selected_citizen","Selected citizen"},
		{"management.military.no_citizen_selected","No citizen selected."},
		{"management.military.assign_selected_role","Assign selected citizen to this role"},
		{"management.military.uniform_slots","Uniform slots"},
		{"management.military.legal_types","Legal types"},
		{"management.military.reported_materials","Materials reported for this type"},
		{"management.military.attitude_flee","Flee v"},
		{"management.military.attitude_defend","Defend v"},
		{"management.military.attitude_attack","Attack v"},
		{"management.military.attitude_hunt","Hunt v"},
		{"management.military.confirm_removal","Confirm removal"},
		{"management.military.remove_record","Remove this record?"},
		{"management.military.cancel","Cancel"},
		{"management.military.remove","Remove"},
		{"management.military.search_placeholder","Filter loaded names"},
		{"management.diplomacy.title","Neighbors and Missions"},
		{"management.diplomacy.heading","Neighbors & Missions"},
		{"management.diplomacy.close","Close"},
		{"management.diplomacy.neighbors","Neighbors"},
		{"management.diplomacy.mission_activity","Mission activity"},
		{"management.diplomacy.source_order","Source order v"},
		{"management.diplomacy.name_type_order","Name/type order v"},
		{"management.diplomacy.refresh","Refresh"},
		{"management.diplomacy.loading_title","Loading neighbors and missions"},
		{"management.diplomacy.loading_detail","Waiting for masked neighbor data and current mission records."},
		{"management.diplomacy.empty_title","No current rows"},
		{"management.diplomacy.empty_detail","The authoritative neighbor or mission collection is empty."},
		{"management.diplomacy.error_title","Diplomacy data unavailable"},
		{"management.diplomacy.error_detail","The payload was rejected or the bridge is unavailable."},
		{"management.diplomacy.retry","Retry"},
		{"management.diplomacy.previous_row","Previous row"},
		{"management.diplomacy.next_row","Next row"},
		{"management.diplomacy.neighbor","Neighbor"},
		{"management.diplomacy.distance","Distance"},
		{"management.diplomacy.type","Type"},
		{"management.diplomacy.attitude","Attitude"},
		{"management.diplomacy.wealth","Wealth"},
		{"management.diplomacy.economy","Economy"},
		{"management.diplomacy.military","Military"},
		{"management.diplomacy.undiscovered_neighbor","Undiscovered neighbor"},
		{"management.diplomacy.masked_detail","Details remain masked by the game."},
		{"management.diplomacy.start_supported_mission","Start one supported mission"},
		{"management.diplomacy.spy","Spy v"},
		{"management.diplomacy.emissary","Emissary v"},
		{"management.diplomacy.raid","Raid v"},
		{"management.diplomacy.sabotage","Sabotage v"},
		{"management.diplomacy.improve_relations","Improve relations v"},
		{"management.diplomacy.insult","Insult v"},
		{"management.diplomacy.invite_trader","Invite trader v"},
		{"management.diplomacy.invite_ambassador","Invite ambassador v"},
		{"management.diplomacy.eligible_gnome","Eligible gnome"},
		{"management.diplomacy.start_mission","Start mission"},
		{"management.diplomacy.mission","Mission"},
		{"management.diplomacy.stable_mission_id","Stable mission ID"},
		{"management.diplomacy.action","Action"},
		{"management.diplomacy.step","Step"},
		{"management.diplomacy.target","Target"},
		{"management.diplomacy.participants","Participants"},
		{"management.diplomacy.current_timing","Current timing"},
		{"management.diplomacy.result_reported","Result, when reported"},
		{"management.diplomacy.unsupported_history","Cancel, reassignment, and historical relationship records are not reported."},
		{"management.diplomacy.search_placeholder","Filter discovered names or mission types"},
	} );
}

} // namespace ingnomia::ui::management6c
