get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${ROOT}/src/gui/ui/screens/developer_ui/DebugRmlBinding.cpp" CPP)
file(READ "${ROOT}/content/rmlui/developer_ui/debug_panel.rml" RML)
file(READ "${ROOT}/src/gui/ui/controllers/developer_ui/DebugQtCommandPort.cpp" PORT)
if(NOT CPP MATCHES "INGNOMIA_DEVELOPER_UI" OR NOT CPP MATCHES "return false" OR NOT RML MATCHES "Developer diagnostics")
 message(FATAL_ERROR "debug UI must be development gated")
endif()
if(NOT PORT MATCHES "INGNOMIA_DEVELOPER_UI" OR NOT PORT MATCHES "return false")
 message(FATAL_ERROR "debug command port must be dormant outside developer builds")
endif()
file(READ "${ROOT}/src/gui/ui/state/UiRegistries.cpp" REGISTRY)
if(NOT REGISTRY MATCHES "#if defined\\(INGNOMIA_DEVELOPER_UI\\)[\r\n\t ]+RouteDefinition\\{ \"debug.panel\"" OR NOT REGISTRY MATCHES "#if defined\\(INGNOMIA_DEVELOPER_UI\\)[\r\n\t ]+DocumentDefinition\\{ \"doc.debug_panel\"" OR NOT REGISTRY MATCHES "#if defined\\(INGNOMIA_DEVELOPER_UI\\)[\r\n\t ]+NamedDefinition\\{ \"ui_debug\"")
 message(FATAL_ERROR "debug registry entries must remain immediately developer guarded")
endif()
if(RML MATCHES "ui_hud|route.game|hud_")
 message(FATAL_ERROR "debug document leaked player route concepts")
endif()
