if(NOT DEFINED PROOF_LOG OR NOT EXISTS "${PROOF_LOG}")
  message(FATAL_ERROR "PROOF_LOG must name the native --management-6b-self-test log")
endif()
file(READ "${PROOF_LOG}" LOG)
foreach(NEEDLE "MANAGEMENT_6B_SELF_TEST_PASS" "PopulationMutationQueued=true" "InventoryWatchQueued=true" "ScheduleKeyboardAlternative=true" "StaleEpochRejected=true" "SelectionStable=true" "InputOwnership=true" "LifecycleClean=true")
  if(NOT LOG MATCHES "${NEEDLE}")
    message(FATAL_ERROR "Native management 6B proof missing ${NEEDLE}")
  endif()
endforeach()
string(TOLOWER "${LOG}" LOG_LOWER)
if(LOG_LOWER MATCHES "rmlui.*(error|warning)" OR LOG_LOWER MATCHES "failed to (load|open)")
  message(FATAL_ERROR "Native management 6B proof contains RmlUi/resource warnings")
endif()
message(STATUS "Management 6B native proof log verified")
