cmake_minimum_required(VERSION 3.16)

set(SPIKE_ROOT "${CMAKE_CURRENT_LIST_DIR}")
file(READ "${SPIKE_ROOT}/CMakeLists.txt" SPIKE_CMAKE)
file(READ "${SPIKE_ROOT}/../../cmake/RmlUiDependencies.cmake" DEPENDENCY_CMAKE)
file(READ "${SPIKE_ROOT}/src/main.cpp" SPIKE_SOURCE)
file(READ "${SPIKE_ROOT}/../../src/gui/ui/runtime/IngnomiaRmlUiRenderer.cpp" RENDERER_SOURCE)
file(READ "${SPIKE_ROOT}/../../src/gui/ui/runtime/RmlUiQtInputAdapter.cpp" INPUT_SOURCE)
file(READ "${SPIKE_ROOT}/assets/spike.rml" SPIKE_RML)
file(READ "${SPIKE_ROOT}/assets/spike.rcss" SPIKE_RCSS)

function(require_text variable pattern description)
    if(NOT "${${variable}}" MATCHES "${pattern}")
        message(FATAL_ERROR "Missing spike contract: ${description}")
    endif()
endfunction()

require_text(DEPENDENCY_CMAKE "2230d1a6e8e0848ed87a5761e2a5160b2a175ba4" "immutable RmlUi 6.2 commit")
require_text(DEPENDENCY_CMAKE "42608f77f20749dd6ddc9e0536788eaad70ea4b5" "immutable FreeType 2.13.3 commit")
require_text(DEPENDENCY_CMAKE "FETCHCONTENT_SOURCE_DIR_FREETYPE" "FreeType offline source override")
require_text(DEPENDENCY_CMAKE "FETCHCONTENT_SOURCE_DIR_RMLUI" "RmlUi offline source override")
require_text(SPIKE_CMAKE "RMLUI_GL3_CUSTOM_LOADER" "existing GLAD custom-loader boundary")
require_text(SPIKE_SOURCE "QOpenGLContext" "Qt-owned OpenGL context")
require_text(SPIKE_SOURCE "SetDimensions" "physical context resize")
require_text(SPIKE_SOURCE "SetDensityIndependentPixelRatio" "DPI and user scaling")
require_text(SPIKE_SOURCE "ProcessTextInput" "UTF-8 text input")
require_text(SPIKE_SOURCE "ProcessMouseWheel" "wheel input")
require_text(SPIKE_SOURCE "BeginFrame" "RmlUi GL frame begin")
require_text(SPIKE_SOURCE "EndFrame" "RmlUi GL frame end")
require_text(SPIKE_SOURCE "--self-test" "deterministic framebuffer self-test")
require_text(RENDERER_SOURCE "glUseProgram" "explicit upstream GL program restoration")
require_text(RENDERER_SOURCE "glBindFramebuffer" "explicit upstream framebuffer restoration")
require_text(INPUT_SOURCE "PointerOwner" "positive-semantic pointer ownership")
require_text(SPIKE_SOURCE "i < 100" "repeated document lifecycle probe")
require_text(SPIKE_SOURCE "Rml::Shutdown" "explicit RmlUi shutdown")
require_text(SPIKE_RML "data-event-click=\"increment" "click callback")
require_text(SPIKE_RML "data-value=\"input_text\"" "two-way text binding")
require_text(SPIKE_RCSS "pointer-events: none" "map-pass-through root")
require_text(SPIKE_RCSS "overflow-y: auto" "scroll and clipping region")
require_text(SPIKE_RCSS "nav: auto" "spatial navigation")

message(STATUS "Isolated RmlUi Qt/OpenGL spike source contract passed")
