if(NOT DEFINED PROOF_LOG OR NOT EXISTS "${PROOF_LOG}")
 message(FATAL_ERROR "PROOF_LOG must name the native --developer-ui-self-test log")
endif()
file(READ "${PROOF_LOG}" LOG)
foreach(NEEDLE "DEVELOPER_UI_SELF_TEST_PASS" "TypedDebugAction=true" "StableRowKeyboard=true" "SearchStable=true" "StaleEpochRejected=true" "MeasuredCounters=true" "InputOwnership=true" "LifecycleClean=true" "Lifecycle load/unload cycles: 100" "OpenGL state/error warnings: 0")
 if(NOT LOG MATCHES "${NEEDLE}")
  message(FATAL_ERROR "Developer UI proof missing ${NEEDLE}")
 endif()
endforeach()
string(TOLOWER "${LOG}" LOWER)
if(LOWER MATCHES "rmlui.*(error|warning)" OR LOWER MATCHES "failed to (load|open)")
 message(FATAL_ERROR "Developer UI proof contains RmlUi/resource warnings")
endif()
message(STATUS "Developer UI native proof verified")
