cmake_minimum_required(VERSION 3.16)

get_filename_component(INGNOMIA_REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/content/JSON/tutorial/scenario_v2.json" SCENARIO)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/content/rmlui/screens/main_menu.rml" MAIN_MENU)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/content/rmlui/screens/game_hud.rml" HUD)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/src/gui/ui/actions/UiActionRegistry.cpp" ACTIONS)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/src/game/gamemanager.cpp" GAME_MANAGER)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/src/game/tutorialmanager.cpp" TUTORIAL_MANAGER)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/src/gui/ui/localization/UiTextStaticEntries.inc" TUTORIAL_TEXT)

function(require_text source pattern description)
	if(NOT "${${source}}" MATCHES "${pattern}")
		message(FATAL_ERROR "Tutorial contract missing: ${description}")
	endif()
endfunction()

require_text(SCENARIO "\"scenarioId\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"scenario_v2\"" "scenario id")
require_text(SCENARIO "\"scenarioVersion\"[ \\t\\r\\n]*:[ \\t\\r\\n]*2" "scenario version")
require_text(SCENARIO "\"seed\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"133693463\"" "fixed numeric seed")
require_text(SCENARIO "\"flatness\"[ \\t\\r\\n]*:[ \\t\\r\\n]*0" "flat tutorial ground")
require_text(SCENARIO "\"startingGnomes\"[ \\t\\r\\n]*:[ \\t\\r\\n]*5" "five starting gnomes")
require_text(SCENARIO "\"ambientEvents\"[ \\t\\r\\n]*:[ \\t\\r\\n]*false" "ambient event suppression")
foreach(LANDMARK camp harvest mine workshop)
	require_text(SCENARIO "\"${LANDMARK}\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\\{" "${LANDMARK} landmark")
	require_text(SCENARIO "\"${LANDMARK}\"[^\\n]*\"z\"[ \\t]*:[ \\t]*70" "${LANDMARK} surface level")
endforeach()
require_text(SCENARIO "\"trees\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\\[" "tree landmarks")
require_text(SCENARIO "\"trees\"[^\\n]*\"z\"[ \\t]*:[ \\t]*70" "tree surface level")
require_text(SCENARIO "\"matureCrop\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"Strawberry\"" "staged mature crop")
require_text(SCENARIO "\"matureTrees\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"PineTree\"" "staged mature trees")
require_text(GAME_MANAGER "setSeed\\( \"133693463\" \\)" "runtime numeric seed")
require_text(GAME_MANAGER "setFlatness\\( 0 \\)" "runtime flat ground")
foreach(ITEM Pickaxe FellingAxe RawWood RawStone Bed Chair Table Knife Bread Grain Seed)
	require_text(SCENARIO "\"item\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"${ITEM}\"" "starter item ${ITEM}")
endforeach()
require_text(MAIN_MENU "id=\"shell-tutorial\"" "main-menu tutorial button")
if(MAIN_MENU MATCHES "GameManager|EventConnector|onStartTutorial")
	message(FATAL_ERROR "Tutorial main-menu RML must dispatch through the shell action bridge")
endif()
foreach(ID hud_tutorial_panel tutorial_title tutorial_progress tutorial_explanation tutorial_objective tutorial_steps tutorial_checklist tutorial_warning tutorial-continue tutorial-skip tutorial-restart tutorial-hints tutorial-finish)
require_text(HUD "id=\"${ID}\"" "HUD tutorial element ${ID}")
endforeach()
if(HUD MATCHES "GameManager|EventConnector|onTutorial")
	message(FATAL_ERROR "Tutorial HUD RML must dispatch through typed UI actions")
endif()
# Stage 17: the tutorial is a Windows 98 palette with book-title-caps commands.
foreach(LABEL ">Continue<" ">Finish<" ">Skip<" ">Restart<")
require_text(HUD "${LABEL}" "tutorial command ${LABEL}")
endforeach()
file(READ "${INGNOMIA_REPOSITORY_ROOT}/content/rmlui/screens/hud.rcss" HUD_STYLE)
require_text(HUD_STYLE "l-hud-tutorial[^\n]*pointer-events: ?auto" "tutorial panel accepts pointer input")
foreach(ACTION app.start_tutorial tutorial.advance tutorial.skip tutorial.restart tutorial.toggle_hints tutorial.finish)
require_text(ACTIONS "\"${ACTION}\"" "UI action ${ACTION}")
endforeach()
if(GAME_MANAGER MATCHES "startTutorial\(\)[^}]*Global::newGameSettings->")
	message(FATAL_ERROR "Interactive tutorial must not mutate normal new-game settings")
endif()

foreach(KEY tutorial.explanation.farming tutorial.steps.farming.designate tutorial.steps.farming.crop tutorial.steps.farming.queue tutorial.steps.farming.plant)
	require_text(TUTORIAL_TEXT "${KEY}" "farm lesson text ${KEY}")
endforeach()
require_text(TUTORIAL_TEXT "click the Plots tab" "farm planner navigation")
require_text(TUTORIAL_TEXT "set Per plot to 2" "per-plot planting queue instruction")
require_text(TUTORIAL_MANAGER "TutorialFact::CropQueued" "farm queue completion check")

message(STATUS "Interactive tutorial scenario/UI contract passed")
