cmake_minimum_required(VERSION 3.16)

get_filename_component(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${REPOSITORY_ROOT}/CMakeLists.txt" ROOT_CMAKE)
file(READ "${REPOSITORY_ROOT}/src/gui/mainwindow.h" WINDOW_HEADER)
file(READ "${REPOSITORY_ROOT}/src/gui/mainwindow.cpp" WINDOW_SOURCE)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/runtime/RmlUiHost.cpp" HOST_SOURCE)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/runtime/RmlUiQtInputAdapter.cpp" INPUT_ADAPTER_SOURCE)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/screens/inspector/InspectorRmlBinding.cpp" INSPECTOR_BINDING)

function(require_text variable pattern description)
    if(NOT "${${variable}}" MATCHES "${pattern}")
        message(FATAL_ERROR "Missing production RmlUi wiring contract: ${description}")
    endif()
endfunction()

function(require_order variable first second description)
    string(FIND "${${variable}}" "${first}" first_position)
    string(FIND "${${variable}}" "${second}" second_position)
    if(first_position EQUAL -1 OR second_position EQUAL -1 OR NOT first_position LESS second_position)
        message(FATAL_ERROR "Invalid production RmlUi wiring order: ${description}")
    endif()
endfunction()

if(ROOT_CMAKE MATCHES "INGNOMIA_ENABLE_RMLUI_MAINWINDOW")
    message(FATAL_ERROR "Root build must expose only the production RmlUi MainWindow path")
endif()
require_text(WINDOW_HEADER "unique_ptr<ingnomia::ui::RmlUiHost>" "MainWindow owns the host")
require_text(WINDOW_SOURCE "initializeRmlUi\\(\\)" "host initialization")
require_text(WINDOW_SOURCE "shutdownRmlUi\\(\\)" "host shutdown")
require_text(WINDOW_HEADER "closeEvent\\( QCloseEvent" "native close boundary declaration")
require_text(WINDOW_SOURCE "MainWindow::closeEvent" "native close boundary implementation")
require_text(WINDOW_SOURCE "event->ignore\\(\\).*QCoreApplication::quit" "native close preserves the GL surface")
require_text(WINDOW_SOURCE "createShellBinding\\(\\)" "outer-shell binding ownership")
require_text(WINDOW_SOURCE "shellBinding->initialize" "registered app-shell and route document load")
require_text(WINDOW_SOURCE "width\\(\\) \\* devicePixelRatio\\(\\)" "physical framebuffer width")
require_text(WINDOW_SOURCE "densityIndependentPixelRatio" "DPR and UI-scale propagation")
require_text(WINDOW_SOURCE "QEvent::InputMethod" "IME commit routing")
require_text(WINDOW_SOURCE "input\\(\\).committedText" "Unicode committed text routing")
require_text(INPUT_ADAPTER_SOURCE "code < 0x20u" "committed text rejects C0 editing controls")
require_text(INPUT_ADAPTER_SOURCE "code >= 0x7fu.*code <= 0x9fu" "committed text rejects Delete and C1 controls")
require_text(WINDOW_SOURCE "input\\(\\).keyDown" "keyboard routing")
require_text(WINDOW_SOURCE "input\\(\\).mouseButtonDown" "pointer routing")
require_text(WINDOW_SOURCE "PointerOwner::World" "stable world gesture ownership")
require_text(WINDOW_SOURCE "input\\(\\).mouseWheel" "wheel first refusal")
require_text(WINDOW_SOURCE "input\\(\\).cancelInteraction" "focus-loss cancellation")
require_text(WINDOW_SOURCE "escapeLayer == ingnomia::ui::accessibility::EscapeLayer::ActiveTool" "active-tool Escape cancellation")
require_text(INSPECTOR_BINDING "const bool open = liveInspection_ \\|\\| s.kind != InspectorKind::None;" "tile selections keep the inspector panel visible")
require_text(WINDOW_SOURCE "m_rmlUiHost->update\\(\\).*m_rmlUiHost->render\\(\\)" "UI update/render sequence")
require_text(HOST_SOURCE "UnloadAllDocuments\\(\\).*RemoveContext.*Rml::Shutdown" "document/context/core teardown order")

require_order(WINDOW_SOURCE "gladLoadGL" "if ( !initializeRmlUi()" "GLAD must initialize before RmlUi")
require_order(WINDOW_SOURCE "m_renderer->initializeGL();" "if ( !initializeRmlUi()" "world renderer must initialize before RmlUi")
require_order(WINDOW_SOURCE "shutdownRmlUi();" "delete m_context;" "RmlUi must shut down before Qt destroys GL context")
require_order(WINDOW_SOURCE "m_renderer->paintWorld();" "m_rmlUiHost->render()" "world must render before RmlUi")

message(STATUS "Production MainWindow RmlUi wiring contract passed")
