cmake_minimum_required(VERSION 3.16)

get_filename_component(INGNOMIA_REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/content/JSON/tutorial/scenario_v1.json" SCENARIO)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/content/rmlui/screens/main_menu.rml" MAIN_MENU)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/content/rmlui/screens/game_hud.rml" HUD)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/src/gui/ui/actions/UiActionRegistry.cpp" ACTIONS)
file(READ "${INGNOMIA_REPOSITORY_ROOT}/src/game/gamemanager.cpp" GAME_MANAGER)

function(require_text source pattern description)
	if(NOT "${${source}}" MATCHES "${pattern}")
		message(FATAL_ERROR "Tutorial contract missing: ${description}")
	endif()
endfunction()

require_text(SCENARIO "\"scenarioId\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"scenario_v1\"" "scenario id")
require_text(SCENARIO "\"scenarioVersion\"[ \\t\\r\\n]*:[ \\t\\r\\n]*1" "scenario version")
require_text(SCENARIO "\"seed\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"ingnomia-tutorial-v1\"" "fixed seed")
require_text(SCENARIO "\"startingGnomes\"[ \\t\\r\\n]*:[ \\t\\r\\n]*5" "five starting gnomes")
require_text(SCENARIO "\"ambientEvents\"[ \\t\\r\\n]*:[ \\t\\r\\n]*false" "ambient event suppression")
require_text(SCENARIO "\"migration\"" "migration block")
require_text(SCENARIO "\"amount\"[ \\t\\r\\n]*:[ \\t\\r\\n]*3" "three-person migration")
require_text(SCENARIO "\"location\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"migration\"" "migration landmark location")
foreach(LANDMARK camp farm mine workshop kitchen migration)
	require_text(SCENARIO "\"${LANDMARK}\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\\{" "${LANDMARK} landmark")
endforeach()
require_text(SCENARIO "\"matureCrop\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"Strawberry\"" "staged mature crop")
foreach(ITEM Pickaxe FellingAxe RawWood RawStone Bed Chair Table Knife Bread Grain Seed)
	require_text(SCENARIO "\"item\"[ \\t\\r\\n]*:[ \\t\\r\\n]*\"${ITEM}\"" "starter item ${ITEM}")
endforeach()
require_text(MAIN_MENU "id=\"shell-tutorial\"" "main-menu tutorial button")
if(MAIN_MENU MATCHES "GameManager|EventConnector|onStartTutorial")
	message(FATAL_ERROR "Tutorial main-menu RML must dispatch through the shell action bridge")
endif()
foreach(ID hud_tutorial_panel tutorial_title tutorial_progress tutorial_explanation tutorial_objective tutorial_steps tutorial_checklist tutorial_warning tutorial-continue tutorial-skip tutorial-restart tutorial-hints tutorial-finish)
require_text(HUD "id=\"${ID}\"" "HUD tutorial element ${ID}")
endforeach()
if(HUD MATCHES "GameManager|EventConnector|onTutorial")
	message(FATAL_ERROR "Tutorial HUD RML must dispatch through typed UI actions")
endif()
foreach(KEY tutorial.action.continue tutorial.action.skip tutorial.action.restart tutorial.action.hints tutorial.action.finish)
require_text(HUD "data-l10n=\"${KEY}\"" "localized tutorial action ${KEY}")
endforeach()
file(READ "${INGNOMIA_REPOSITORY_ROOT}/content/rmlui/screens/hud.rcss" HUD_STYLE)
require_text(HUD_STYLE "l-hud-tutorial[^\n]*pointer-events:auto" "tutorial panel accepts pointer input")
foreach(ACTION app.start_tutorial tutorial.advance tutorial.skip tutorial.restart tutorial.toggle_hints tutorial.finish)
require_text(ACTIONS "\"${ACTION}\"" "UI action ${ACTION}")
endforeach()
if(GAME_MANAGER MATCHES "startTutorial\(\)[^}]*Global::newGameSettings->")
	message(FATAL_ERROR "Interactive tutorial must not mutate normal new-game settings")
endif()

message(STATUS "Interactive tutorial scenario/UI contract passed")
