cmake_minimum_required(VERSION 3.16)

get_filename_component(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${REPOSITORY_ROOT}/src/gui/mainwindow.cpp" MAIN_SOURCE)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/designer/UiDesignerModel.h" MODEL_HEADER)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/designer/UiDesignerRmlBinding.cpp" BINDING_SOURCE)
file(READ "${REPOSITORY_ROOT}/content/rmlui/developer_ui/designer_overlay.rml" DESIGNER_RML)
file(READ "${REPOSITORY_ROOT}/content/rmlui/developer_ui/designer_overlay.rcss" DESIGNER_RCSS)
file(READ "${REPOSITORY_ROOT}/tools/run-rmlui-dev.ps1" LAUNCHER)

function(require_text variable pattern description)
    if(NOT "${${variable}}" MATCHES "${pattern}")
        message(FATAL_ERROR "Missing UI designer contract: ${description}")
    endif()
endfunction()

require_text(MAIN_SOURCE "INGNOMIA_UI_DESIGNER" "compile/runtime opt-in")
require_text(MAIN_SOURCE "Qt::Key_F6" "designer shortcut")
require_text(MAIN_SOURCE "selectAt" "design-mode element selection")
require_text(MODEL_HEADER "projectJson" "portable project representation")
require_text(MODEL_HEADER "undo" "undo contract")
require_text(BINDING_SOURCE "developer_ui/designer_overlay.rml" "designer document path")
require_text(BINDING_SOURCE "GetElementAtPoint" "live RmlUi picking")
require_text(BINDING_SOURCE "CreateElement" "component insertion")
require_text(BINDING_SOURCE "INGNOMIA_UI_DESIGNER_PROJECT" "project save override")
require_text(BINDING_SOURCE "exportHandoff" "agent handoff export")
require_text(DESIGNER_RML "designer_component_input" "component palette")
require_text(DESIGNER_RML "designer_width" "property inspector")
require_text(DESIGNER_RML "designer_surface" "active surface label")
require_text(DESIGNER_RCSS "pointer-events: none" "non-invasive overlay root")
require_text(LAUNCHER "Designer" "designer launcher switch")

message(STATUS "RmlUi UI designer contract passed")
