cmake_minimum_required(VERSION 3.16)

get_filename_component(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${REPOSITORY_ROOT}/src/gui/mainwindow.cpp" MAIN_SOURCE)
file(READ "${REPOSITORY_ROOT}/src/gui/mainwindow.h" MAIN_HEADER)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/runtime/RmlUiDetachedWindow.h" WINDOW_HEADER)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/runtime/RmlUiDetachedWindow.cpp" WINDOW_SOURCE)
file(READ "${REPOSITORY_ROOT}/content/rmlui/developer_ui/designer_overlay.rml" DESIGNER_RML)

function(require_text variable pattern description)
    if(NOT "${${variable}}" MATCHES "${pattern}")
        message(FATAL_ERROR "Missing detached UI designer contract: ${description}")
    endif()
endfunction()

require_text(MAIN_HEADER "UiDesignerRmlBinding> designer" "designer ownership in detached surfaces")
require_text(MAIN_SOURCE "createDetachedUiDesigner" "detached designer construction")
require_text(MAIN_SOURCE "wireDetachedUiDesigner" "detached input wiring")
require_text(MAIN_SOURCE "m_uiDesignerActive" "focused surface tracking")
require_text(MAIN_SOURCE "designer->reloadDocument" "designer reload lifecycle")
require_text(MAIN_SOURCE "designer->shutdown" "designer teardown before context destruction")
require_text(WINDOW_HEADER "setDesignerFocusHandler" "detached focus hook")
require_text(WINDOW_HEADER "setDesignerKeyHandler" "detached key hook")
require_text(WINDOW_HEADER "setDesignerMousePressHandler" "detached mouse hook")
require_text(WINDOW_SOURCE "focusInEvent" "detached focus activation")
require_text(WINDOW_SOURCE "m_designerKeyHandler" "detached key interception")
require_text(WINDOW_SOURCE "m_designerMousePressHandler" "detached selection interception")
require_text(DESIGNER_RML "designer_surface" "surface identity in the detached overlay")

message(STATUS "Detached RmlUi UI designer contract passed")
