cmake_minimum_required(VERSION 3.16)

get_filename_component(REPOSITORY_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(READ "${REPOSITORY_ROOT}/src/gui/mainwindow.cpp" WINDOW_SOURCE)
file(READ "${REPOSITORY_ROOT}/src/main.cpp" MAIN_SOURCE)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/runtime/RmlUiHost.h" HOST_HEADER)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/runtime/RmlUiHost.cpp" HOST_SOURCE)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/runtime/QtRmlFileInterface.cpp" FILE_SOURCE)
file(READ "${REPOSITORY_ROOT}/src/gui/ui/screens/inspector/InspectorRmlBinding.cpp" INSPECTOR_SOURCE)
file(READ "${REPOSITORY_ROOT}/tools/run-rmlui-dev.ps1" DEV_LAUNCHER)

function(require_text variable pattern description)
    if(NOT "${${variable}}" MATCHES "${pattern}")
        message(FATAL_ERROR "Missing RmlUi hot-reload contract: ${description}")
    endif()
endfunction()

function(require_order variable first second description)
    string(FIND "${${variable}}" "${first}" first_position)
    string(FIND "${${variable}}" "${second}" second_position)
    if(first_position EQUAL -1 OR second_position EQUAL -1 OR NOT first_position LESS second_position)
        message(FATAL_ERROR "Invalid RmlUi hot-reload order: ${description}")
    endif()
endfunction()

require_text(WINDOW_SOURCE "INGNOMIA_RMLUI_ASSET_ROOT" "source asset override")
require_text(WINDOW_SOURCE "INGNOMIA_UI_DEV_MODE" "explicit development mode")
require_text(MAIN_SOURCE "INGNOMIA_AUTOMATE_UI_FIXTURE_HOLD" "interactive fixture hold mode")
require_text(MAIN_SOURCE "scheduleUiFixture" "readiness-driven fixture scheduling")
require_text(MAIN_SOURCE "ui_fixture_stockpile_geometry inline=" "stockpile geometry runtime evidence")
require_text(WINDOW_SOURCE "showInspectorStockpileFixture" "deterministic stockpile inspector fixture")
require_text(WINDOW_SOURCE "development mode is watching staged content" "staged-content development warning")
require_text(WINDOW_SOURCE "setDocumentReloadHandler" "binding lifecycle callback")
require_text(WINDOW_SOURCE "requestDocumentReload" "manual full reload")
require_text(WINDOW_SOURCE "Qt::Key_F5" "manual reload shortcut")
require_text(WINDOW_SOURCE "Qt::Key_F7" "debugger shortcut")
require_text(WINDOW_SOURCE "Qt::Key_F8" "development framebuffer recapture shortcut")
require_text(WINDOW_SOURCE "reloadDocument\\( \\*m_inspectorController, true \\)" "inspector UI state preservation")
require_text(WINDOW_SOURCE "processHotReload" "frame-boundary reload processing")
require_text(HOST_HEADER "fallbackAssetRoot" "packaged generated-asset fallback")
require_text(HOST_HEADER "QFileSystemWatcher" "source file watcher")
require_text(HOST_SOURCE "ReloadStyleSheet" "stylesheet-only reload")
require_text(HOST_SOURCE "Rml::ReleaseTextures" "texture cache reload")
require_text(HOST_SOURCE "rmlui_hot_reload success=" "automation evidence for live reloads")
require_text(HOST_SOURCE "suffix == \"rml\"" "document reload classification")
require_text(FILE_SOURCE "m_fallbackAssetRoot" "fallback file resolution")
require_text(INSPECTOR_SOURCE "preserveUiState" "binding-owned view restoration")
require_text(INSPECTOR_SOURCE "stockpileItemIconInline" "stockpile icon and label geometry assertion")
require_text(INSPECTOR_SOURCE "UpdateDocument" "current layout before geometry inspection")
require_text(DEV_LAUNCHER "INGNOMIA_RMLUI_ASSET_ROOT" "source-root launcher override")
require_text(DEV_LAUNCHER "stockpile" "stockpile development fixture")
require_text(DEV_LAUNCHER "CapturePath" "fixture framebuffer capture option")

require_order(WINDOW_SOURCE "processHotReload();" "m_rmlUiHost->update();" "reloads must run before the RmlUi update")
require_order(HOST_SOURCE "m_reloadDocumentsPending" "ReloadStyleSheet" "a full document reload takes precedence over stylesheet refresh")
require_order(HOST_SOURCE "Rml::SetSystemInterface" "Rml::Initialise" "interfaces must be installed before core initialization")
require_order(HOST_SOURCE "m_debugBinding.reset" "Rml::RemoveContext" "bindings and their listeners must be released before contexts")
require_order(HOST_SOURCE "Rml::RemoveContext" "Rml::Shutdown" "contexts must be removed before core shutdown")
require_order(HOST_SOURCE "Rml::Shutdown" "Rml::SetRenderInterface( nullptr )" "application interfaces must outlive core shutdown")

message(STATUS "RmlUi hot-reload contract passed")
