cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED UI_THEME_SOURCE_ROOT OR NOT DEFINED UI_THEME_OUTPUT_DIR)
    message(FATAL_ERROR "Set UI_THEME_SOURCE_ROOT and UI_THEME_OUTPUT_DIR")
endif()

set(UI_THEME_STYLE_DIR "${UI_THEME_SOURCE_ROOT}/content/rmlui/styles")
if(NOT DEFINED UI_THEME_TOKEN_FILE)
    set(UI_THEME_TOKEN_FILE "${UI_THEME_STYLE_DIR}/tokens.json")
endif()
if(NOT EXISTS "${UI_THEME_TOKEN_FILE}")
    message(FATAL_ERROR "Theme token source does not exist: ${UI_THEME_TOKEN_FILE}")
endif()

# Keep the token object flat so this generator stays compatible with the
# project's CMake 3.16 minimum (string(JSON) arrived in CMake 3.19).
file(STRINGS "${UI_THEME_TOKEN_FILE}" theme_lines)
set(in_rcss_tokens FALSE)
set(theme_keys)
set(theme_values)
foreach(line IN LISTS theme_lines)
    if(line MATCHES "^[ \t]*\"rcss_tokens\"[ \t]*:[ \t]*\\{")
        set(in_rcss_tokens TRUE)
    elseif(in_rcss_tokens AND line MATCHES "^[ \t]*\\}")
        set(in_rcss_tokens FALSE)
    elseif(in_rcss_tokens AND line MATCHES "\"([A-Za-z0-9_.-]+)\"[ \t]*:[ \t]*\"([^\"]+)\"")
        list(APPEND theme_keys "${CMAKE_MATCH_1}")
        # CMake lists use semicolons as separators. Preserve JSON string
        # values such as CSS text-decorator character references until after
        # the value is retrieved by its parallel key index.
        string(REPLACE ";" "__UI_THEME_SEMICOLON__" theme_value "${CMAKE_MATCH_2}")
        list(APPEND theme_values "${theme_value}")
    endif()
endforeach()
if(NOT theme_keys)
    message(FATAL_ERROR "No flat rcss_tokens entries found in ${UI_THEME_TOKEN_FILE}")
endif()

file(MAKE_DIRECTORY "${UI_THEME_OUTPUT_DIR}")
foreach(name IN ITEMS base components accessibility management_window)
    set(template_path "${UI_THEME_STYLE_DIR}/${name}.rcss.in")
    set(output_path "${UI_THEME_OUTPUT_DIR}/${name}.rcss")
    if(NOT EXISTS "${template_path}")
        message(FATAL_ERROR "Missing generated stylesheet template: ${template_path}")
    endif()
    file(READ "${template_path}" generated_text)
    string(REGEX MATCHALL "\\{\\{[A-Za-z0-9_.-]+\\}\\}" markers "${generated_text}")
    foreach(marker IN LISTS markers)
        string(REGEX REPLACE "^\\{\\{([^}]+)\\}\\}$" "\\1" token_name "${marker}")
        list(FIND theme_keys "${token_name}" token_index)
        if(token_index EQUAL -1)
            message(FATAL_ERROR "Unknown RCSS theme token '${token_name}' in ${template_path}")
        endif()
        list(GET theme_values ${token_index} token_value)
        string(REPLACE "__UI_THEME_SEMICOLON__" ";" token_value "${token_value}")
        string(REPLACE "${marker}" "${token_value}" generated_text "${generated_text}")
    endforeach()
    if(generated_text MATCHES "\\{\\{[^}]+\\}\\}")
        message(FATAL_ERROR "Unexpanded theme marker remains in ${template_path}")
    endif()
    set(generated_text "/* Generated from ${name}.rcss.in and tokens.json. Edit the source inputs. */\n\n${generated_text}")
    file(WRITE "${output_path}" "${generated_text}")
endforeach()
